ALTER TABLE public.agt_operations_log
  DROP CONSTRAINT IF EXISTS agt_operations_log_event_type_check;

ALTER TABLE public.agt_operations_log
  ADD CONSTRAINT agt_operations_log_event_type_check CHECK (
    event_type = ANY (ARRAY[
      'POLICY_IMPORT', 'POLICY_PUBLISH', 'POLICY_APPROVE',
      'BLUEPRINT_APPROVE', 'BLUEPRINT_PUBLISH', 'BLUEPRINT_ROLLBACK',
      'EVIDENCE_INGEST', 'EVIDENCE_EXPORT', 'BUNDLE_EXPORT',
      'EVIDENCE_PRUNE', 'EVIDENCE_ERASURE', 'SIMULATION_RUN',
      'TRUST_SCORE_CHANGE', 'TRUST_POLICY_BREACH', 'CONTEXT_BUDGET_BREACH',
      'ECONOMIC_BUDGET_BREACH', 'ECONOMIC_USAGE_INGEST', 'IDENTITY_CHANGE',
      'TOKEN_ISSUED', 'TOKEN_REVOKED', 'TOKEN_REFRESHED',
      'ESCALATION_OPENED', 'ESCALATION_CLAIMED', 'ESCALATION_RESOLVED',
      'AGENT_TRIAGE', 'AGENT_RECOMMENDATION', 'SIMULATION_GUIDANCE',
      'GRC_DESTINATION_CONFIGURED', 'NOTIFICATION_SENT', 'NOTIFICATION_FAILED',
      'VERIFICATION_RUN', 'ACTION_RECEIPT_ISSUED', 'COMPLIANCE_EXPORT'
    ]::text[])
  );
