/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a governance decision as evidence
         * @description Records an agent runtime governance decision in the evidence store. Supports both standard mode (caller supplies policyRefs, artifactHash, policyContext) and gateway mode (server resolves policy context via revision-at-time lookup). Duplicate `decisionId` submissions return 200 with `deduplicated: true` and are suppressed.
         */
        post: operations["ingestEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/git-checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a Git checkpoint and diff
         * @description Accepts framework-agnostic, normalized Git checkpoint and diff metadata. The server resolves policy context at the checkpoint timestamp and persists the result as evidence. It never executes Git or reads a client repository.
         */
        post: operations["ingestGitCheckpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate a gateway decision
         * @description Evaluates a governance decision against the active policy bundle and returns an outcome (`PROCEED`, `ESCALATE`, or `ABORT`). When the gateway is disabled the response always returns `PROCEED`. Decisions that trigger `shouldQueue: true` are placed in the escalation queue.
         */
        post: operations["gatewayDecide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve an escalation queue item
         * @description Closes an open escalation queue item with a resolution outcome (`PROCEED`, `ESCALATE`, or `ABORT`). Requires web session authentication — this operation represents a human-in-the-loop decision.
         */
        post: operations["gatewayResolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List open escalation queue items
         * @description Returns open escalation queue items for the authenticated workspace. Results are ordered by creation time descending.
         */
        get: operations["listEscalations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway/escalations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get gateway decision escalation status
         * @description Checks the current status of an escalation queue item by its decision ID.
         */
        get: operations["getEscalationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway-ingest/portkey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a Portkey gateway webhook
         * @description Accepts a raw Portkey webhook payload, normalizes it into Spctre runtime evidence, resolves policy context at event time, and records provenance-gap metadata when context cannot be fully resolved.
         */
        post: operations["ingestPortkeyGatewayEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway-ingest/helicone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a Helicone gateway webhook
         * @description Accepts a raw Helicone webhook payload and stores it as Spctre runtime evidence with provider metadata and revision-at-time provenance.
         */
        post: operations["ingestHeliconeGatewayEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gateway-ingest/litellm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a LiteLLM gateway webhook
         * @description Accepts a raw LiteLLM webhook payload and stores it as Spctre runtime evidence with provider metadata and revision-at-time provenance.
         */
        post: operations["ingestLiteLLMGatewayEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate an access/refresh token pair
         * @description Exchanges a valid refresh token for a fresh short-lived access token and rolling refresh token. The previous access token is revoked and the previous refresh token is marked rotated.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current service token
         * @description Revokes the bearer access token used for the request and any active refresh token linked to it. Successful revocation returns 204 with no body.
         */
        post: operations["revokeToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trust/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a trust-score observation
         * @description Records a trust-score observation for an agent, computes score delta against the prior observation, and appends a trust-score operations-log event.
         */
        post: operations["ingestTrustScore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trust/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate trust and context-budget governance
         * @description Evaluates trust score and context-token state against enabled calibration policies, returning an ALLOW/WARN/REVIEW/ESCALATE action plus a gateway risk hint.
         */
        post: operations["evaluateTrustGovernance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trust/context-budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a context-budget telemetry event
         * @description Records context token growth, summarization, source mix, or budget breach telemetry. Budget breaches are written to the operations log.
         */
        post: operations["ingestContextBudgetEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundle/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the latest published policy bundle
         * @description Returns the latest published policy bundle for the authenticated workspace. Without `format`, the response is the raw AGT-compatible JSON bundle. With `format`, the response is an export envelope containing a target artifact and manifest. Use `preview=true` with no format to inspect all target manifests without downloading artifacts.
         */
        get: operations["getBundleLatest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compliance/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the compliance packet
         * @description Generates and returns the latest compliance packet for the workspace as a JSON attachment. Optionally annotated for a specific framework (`soc2`, `iso27001`, `hipaa`, `gdpr`, `pci-dss`, `nist-ai-rmf`, `public-sector`, `eu-ai-act`).
         */
        get: operations["exportCompliance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate a policy decision
         * @description Evaluates a connector + action pair against the latest published policy bundle without persisting a record. Useful for CI/CD checks and policy simulation.
         */
        post: operations["evaluatePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List verification results
         * @description Returns verification results for the workspace, optionally filtered by revisionId or artifactHash.
         */
        get: operations["listVerifications"];
        put?: never;
        /**
         * Ingest a verification result
         * @description Records the outcome of a policy verification run (lint, evidence coverage check, red-team, or custom) against a specific policy artifact.
         */
        post: operations["ingestVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an approval by ID
         * @description Returns the approval record for a specific revision approval ID.
         */
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI 3.1 specification
         * @description Returns this OpenAPI specification document.
         */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/forensic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forensic archival evidence query
         * @description Query the full tenant event log for forensic replay and archival analysis. Returns up to 10,000 records per request with cursor-based pagination.
         */
        get: operations["forensicEvidenceQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluate/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk simulation against the full tenant event log
         * @description Runs a policy simulation against the tenant's complete historical evidence log. Useful for impact analysis before publishing a new policy revision.
         */
        post: operations["bulkSimulate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scim/v2/Users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SCIM 2.0 — list users
         * @description SCIM 2.0 user provisioning endpoint for IdP integration.
         */
        get: operations["scimListUsers"];
        put?: never;
        /**
         * SCIM 2.0 — create user
         * @description Provision a new user via SCIM 2.0.
         */
        post: operations["scimCreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiMeta: {
            /**
             * @description Correlation ID echoed from X-Request-ID or generated server-side.
             * @example req_01j1x2y3z4
             */
            traceId: string;
            /**
             * @description API version string.
             * @example 2026-01
             */
            version: string;
            /**
             * Format: date-time
             * @description ISO timestamp of the response.
             */
            ts: string;
        };
        ApiError: {
            /** @description Human-readable error message. */
            error: string;
            /** @description Field-level validation issues (present on 400 responses). */
            issues?: {
                path?: string;
                message?: string;
            }[];
            meta: components["schemas"]["ApiMeta"];
        };
        Pagination: {
            total: number;
            limit: number;
            offset: number;
        };
        /** @enum {string} */
        RuntimeStack: "AWS_BEDROCK" | "GOOGLE_ADK" | "AZURE_AI" | "LANGCHAIN" | "LANGGRAPH" | "CREWAI" | "AUTOGEN" | "OPENAI_AGENTS" | "OMNIGENT" | "OPENCODE" | "CLAUDE_CODE" | "HERMES" | "OPENCLAW" | "NEMOCLAW" | "CLAUDE_COWORK" | "ODYSSEUS" | "PAPERCLIP" | "LOCAL" | "CUSTOM";
        /**
         * @description The invocation origin of the agent tool call.
         * @enum {string}
         */
        TriggerKind: "interactive" | "scheduled" | "mobile_dispatch" | "inbound_webhook" | "routine" | "gateway_message";
        /**
         * @description Whether the evidence record originates from the agent layer (L7 tool calls) or sandbox layer (L3/L4 network policy).
         * @enum {string}
         */
        EvidenceLayer: "agent" | "sandbox";
        /** @enum {string} */
        RuntimeDecisionStatus: "ALLOW" | "DENY" | "WARN" | "ESCALATE";
        RuntimeTarget: {
            stack: components["schemas"]["RuntimeStack"];
            /** @description Specific adapter within the stack. */
            adapter?: string;
            environment?: string;
            /** @description Runtime sandbox/deployment name for sandbox-layer policy and evidence queries. */
            sandboxName?: string;
            /** @description Inference router/provider identifier for model-routing policy and evidence queries. */
            inferenceProvider?: string;
        };
        RuntimePolicyContext: {
            /** @enum {string} */
            scope: "ORGANIZATION" | "WORKSPACE" | "ENVIRONMENT" | "CONNECTOR" | "COMPANY";
            branchId: string;
            revisionId: string;
            artifactHash: string;
            packId?: string;
            packVersion?: string;
            packOwner?: string;
        };
        EvidenceIngestRequest: {
            /** @description Unique ID for this governance decision (idempotency key). */
            decisionId: string;
            /** @description Optional tenant boundary hint. Empty string is treated as omitted. The x-spctre-tenant-id header takes precedence when both are present; otherwise inferred from the bearer token when omitted. */
            tenantId?: string;
            /** @description Optional workspace boundary hint. Empty string is treated as omitted. The x-spctre-workspace-id header takes precedence when both are present; otherwise inferred from the bearer token when omitted. */
            workspaceId?: string;
            environment: string;
            runtimeTarget: components["schemas"]["RuntimeTarget"];
            agentId: string;
            connector: string;
            action: string;
            status: components["schemas"]["RuntimeDecisionStatus"];
            reason: string;
            /** @description Required when ingestMode is omitted or 'standard'. Omit only when ingestMode is 'gateway'. */
            policyRefs?: string[];
            /** @description SHA-256 hash of the policy bundle artifact. Required in standard mode. */
            artifactHash?: string;
            /** @description Required in standard mode; server resolves it in gateway mode. */
            policyContext?: components["schemas"]["RuntimePolicyContext"][];
            latencyMs?: number;
            /**
             * Format: date-time
             * @description Decision timestamp. Defaults to server time when omitted.
             */
            createdAt?: string;
            /** @description Arbitrary key-value metadata attached to the evidence record. */
            rawEvidence?: {
                [key: string]: unknown;
            };
            consequence?: string;
            customerTier?: string;
            confidence?: number;
            amountUsd?: number;
            dataSensitivity?: string;
            trustScore?: number;
            contextBudget?: number;
            sourceType?: string;
            /** @description Execution trace for forensic replay. */
            executionTrace?: unknown;
            engineVersion?: string;
            /**
             * @description Use 'gateway' when posting from a gateway adapter; the server resolves policyRefs, artifactHash, and policyContext automatically.
             * @enum {string}
             */
            ingestMode?: "standard" | "gateway";
            /** @description The explicitly declared intent or purpose of the tool call. */
            toolIntent?: string;
            /** @description A high-level plan summary explicitly provided by the runtime. */
            planSummary?: string;
            /** @description The structured arguments passed to the tool. */
            toolParameters?: {
                [key: string]: unknown;
            };
            triggerKind?: components["schemas"]["TriggerKind"];
            layer?: components["schemas"]["EvidenceLayer"];
            /** @description Execution surface identity plus sandbox/inference-router evidence references. */
            executionContext?: {
                backend?: string;
                sessionId?: string;
                sandboxName?: string;
                inferenceProvider?: string;
                sandboxPolicyRef?: string;
                inferenceRouterRef?: string;
            } & {
                [key: string]: unknown;
            };
            /** @description Agent ID of the parent when this evidence originates from a subagent. */
            parentAgentId?: string;
            /** @description Distributed trace identifier linking related agent decisions across subagents. */
            traceId?: string;
            /** @description Orchestrator-platform reference (e.g. Paperclip companyId, issueId, goalId). */
            orchestratorRef?: {
                platform: string;
                companyId?: string;
                issueId?: string;
                goalId?: string;
            } & {
                [key: string]: unknown;
            };
            /**
             * @description Plugin provenance dimension.
             * @enum {string}
             */
            pluginSource?: "public_marketplace" | "corporate_marketplace" | "corporate_private" | "user_built";
            /** @description Prompt-level governance surface: active skills, instruction files, and prompt policy refs present when the decision was made. */
            skillContext?: {
                activeSkills?: string[];
                instructionFiles?: string[];
                promptPolicyRefs?: string[];
                promptSurface?: string;
            } & {
                [key: string]: unknown;
            };
            /** @description Source identifier for inbound webhook triggers (present when triggerKind is inbound_webhook). */
            webhookSource?: string;
            /** @description Trust level assigned by the orchestration platform (e.g. Paperclip trust preset). */
            trustLevel?: string;
            /** @description Catalog or skill provenance provider (e.g. Paperclip catalog-provenance identifier). */
            catalogProvider?: string;
        };
        EvidenceIngestResponse: {
            /** @description The persisted evidence record (canonical shape). */
            evidence: Record<string, never>;
            /** @description Gateway evaluation result, if the gateway is enabled. */
            gateway?: {
                /** @enum {string} */
                outcome?: "PROCEED" | "ESCALATE" | "ABORT";
                reason?: string;
                /** @enum {string} */
                riskLevel?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                shouldQueue?: boolean;
            };
            /** @description True when a record with the same decisionId already exists (200 response). */
            deduplicated?: boolean;
            meta: components["schemas"]["ApiMeta"];
        };
        /** @description Framework-agnostic Git checkpoint and diff evidence. Clients submit normalized Git facts; the server does not execute Git or access a caller repository. */
        GitCheckpointIngestRequest: {
            /** @description Stable checkpoint submission key. Reuse it to safely retry. */
            idempotencyKey: string;
            environment: string;
            status: components["schemas"]["RuntimeDecisionStatus"];
            reason: string;
            checkpoint: {
                id: string;
                /** Format: date-time */
                createdAt: string;
                repository: {
                    id: string;
                    remoteUrl?: string;
                };
                ref?: string;
                baseCommit?: string;
                headCommit: string;
                diff: {
                    /** @enum {string} */
                    format: "unified" | "name-status" | "none";
                    content?: string;
                    sha256?: string;
                    files?: {
                        path: string;
                        /** @enum {string} */
                        status?: "added" | "modified" | "deleted" | "renamed" | "copied" | "unmerged";
                        previousPath?: string;
                    }[];
                };
            };
            agent?: {
                id?: string;
                adapter?: string;
            };
            /** @description Optional client connector label; defaults to git. */
            connector?: string;
            /** @description Optional action label; defaults to checkpoint.ingest. */
            action?: string;
            /** @description Caller-supplied references retained as metadata. Policy context is resolved server-side. */
            policyRefs?: string[];
            metadata?: {
                [key: string]: unknown;
            };
        };
        GatewayDecisionRequest: {
            decisionId: string;
            /** @description Optional tenant boundary hint. Empty string is treated as omitted. The x-spctre-tenant-id header takes precedence when both are present; otherwise inferred from the bearer token when omitted. */
            tenantId?: string;
            /** @description Optional workspace boundary hint. Empty string is treated as omitted. The x-spctre-workspace-id header takes precedence when both are present; otherwise inferred from the bearer token when omitted. */
            workspaceId?: string;
            artifactHash: string;
            policyContext: components["schemas"]["RuntimePolicyContext"][];
            reason?: string;
            consequence?: string;
            customerTier?: string;
            confidence?: number;
            amountUsd?: number;
            dataSensitivity?: string;
            trustScore?: number;
            contextBudget?: number;
            /** @enum {string} */
            riskLevel?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** @description The explicitly declared intent or purpose of the tool call. */
            toolIntent?: string;
            /** @description A high-level plan summary explicitly provided by the runtime. */
            planSummary?: string;
            /** @description The structured arguments passed to the tool. */
            toolParameters?: {
                [key: string]: unknown;
            };
            connector?: string;
            action?: string;
            /** @description Runtime agent identity used to link this decision to cross-surface evidence and governance history. */
            agentId?: string;
            /** @description Stable runtime session identifier used for Blueprint loop safeguards. */
            sessionId?: string;
        };
        CredentialGrant: {
            credentialType: string;
            injectedParameter: string;
            credentialValue: string;
            /** Format: date-time */
            expiresAt: string;
        };
        GatewayDecision: {
            /** @enum {string} */
            outcome: "PROCEED" | "ESCALATE" | "ABORT";
            reason: string;
            /** @enum {string} */
            riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            shouldQueue: boolean;
            slaHours?: number;
            credentialGrant?: components["schemas"]["CredentialGrant"];
        };
        GatewayDecisionResponse: {
            gatewayEnabled: boolean;
            mode: string;
            persisted: boolean;
            queued: boolean;
            decision: components["schemas"]["GatewayDecision"];
            meta: components["schemas"]["ApiMeta"];
        };
        GatewayResolveRequest: {
            queueId: string;
            /** @enum {string} */
            resolutionOutcome: "PROCEED" | "ESCALATE" | "ABORT";
            resolutionNote?: string;
            agentGuidance?: string;
        };
        /** @description Raw provider webhook payload from Portkey, Helicone, or LiteLLM. Spctre normalizes provider-specific fields into runtime evidence. */
        GatewayWebhookRequest: {
            [key: string]: unknown;
        };
        GatewayIngestResponse: {
            decisionId: string;
            /** @description True when Spctre could not fully link the gateway event to a published policy revision or connector mapping. */
            provenanceGap: boolean;
            /** @description True when the provider event was already ingested. */
            deduplicated: boolean;
            meta: components["schemas"]["ApiMeta"];
        };
        TokenRefreshRequest: {
            refreshToken: string;
        };
        TokenRefreshResponse: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            meta: components["schemas"]["ApiMeta"];
        };
        TrustScoreIngestRequest: {
            agentId: string;
            environment: string;
            runtimeStack: components["schemas"]["RuntimeStack"];
            trustScore: number;
            /** @enum {string} */
            source: "EVIDENCE_INGEST" | "POLICY_EVALUATION" | "MANUAL" | "IDENTITY_EVENT" | "SYSTEM";
            sourceRef?: string;
            reason?: string;
        };
        TrustEvaluateRequest: {
            trustScore?: number;
            contextTokens?: number;
            budgetLimit?: number;
            agentClass?: string;
            environment?: string;
            connector?: string;
            /** @enum {string} */
            consequenceTier?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            sessionId?: string;
            agentId?: string;
            runtimeStack?: components["schemas"]["RuntimeStack"];
        };
        ContextBudgetIngestRequest: {
            sessionId: string;
            agentId: string;
            environment: string;
            runtimeStack: components["schemas"]["RuntimeStack"];
            /** @enum {string} */
            eventType: "TOKEN_GROWTH" | "SUMMARIZATION_EVENT" | "CONTEXT_SOURCE_MIX" | "BUDGET_BREACH";
            tokenCount: number;
            tokenDelta?: number;
            contextSourceMix?: Record<string, never>;
            budgetLimit?: number;
            budgetUtilization?: number;
            /** @enum {string} */
            governanceAction?: "ALLOW" | "WARN" | "ESCALATE" | "REVIEW";
            policyRef?: string;
        };
        /** @description An open escalation queue item awaiting human review. */
        EscalationQueueItem: {
            id?: string;
            decisionId?: string;
            outcome?: string;
            riskLevel?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            slaDeadlineAt?: string;
            resolutionOutcome?: string | null;
            /** Format: date-time */
            resolvedAt?: string | null;
            agentGuidance?: string | null;
        };
        EscalationStatusResponse: {
            decisionId: string;
            /** @enum {string} */
            status: "PENDING" | "IN_REVIEW" | "RESOLVED" | "EXPIRED";
            /** @enum {string|null} */
            resolutionOutcome?: "PROCEED" | "ESCALATE" | "ABORT" | null;
            resolutionNote?: string | null;
            agentGuidance?: string | null;
            /** Format: date-time */
            slaDueAt?: string | null;
            /** Format: date-time */
            resolvedAt?: string | null;
            /** @description Immutable, redacted decision arguments. Present only when the escalation is RESOLVED with a PROCEED outcome. */
            approvedToolParameters?: {
                [key: string]: unknown;
            };
            credentialGrant?: components["schemas"]["CredentialGrant"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** @description The latest published policy bundle for the workspace. Response headers carry `x-spctre-branch-id`, `x-spctre-revision-id`, `x-spctre-artifact-hash`, and `x-spctre-published-at`. */
        BundleResponse: Record<string, never>;
        /** @enum {string} */
        BundleExportFormat: "spctre-json" | "opa-rego" | "opa-bundle" | "cedar" | "mcp-proxy-config";
        BundleExportManifest: {
            format: components["schemas"]["BundleExportFormat"];
            target: string;
            /** @enum {string} */
            compatibilityLevel: "NATIVE" | "LOSSLESS_PRESERVED" | "PARTIAL_SEMANTIC_MAP";
            semanticWarnings: string[];
            blockingWarnings: string[];
            verificationTargets: string[];
            artifactHash: string;
            compiledArtifactHash: string;
            /** Format: date-time */
            generatedAt: string;
            provenance: {
                tenantId: string;
                workspaceId: string | null;
                branchId: string;
                revisionId: string;
                sourceHash: string;
                sourceFormat: string;
                sourcePath?: string;
                targetStacks: Record<string, never>[];
            };
            ruleCount: number;
        };
        BundleExportEnvelope: {
            /** @description Target artifact. String for text formats, object for JSON/bundle formats. */
            artifact: string | Record<string, never>;
            manifest: components["schemas"]["BundleExportManifest"];
            meta: components["schemas"]["ApiMeta"];
        };
        BundleExportPreviewResponse: {
            formats: components["schemas"]["BundleExportManifest"][];
            meta: components["schemas"]["ApiMeta"];
        };
        BundleExportBlockedResponse: {
            error: string;
            manifest: components["schemas"]["BundleExportManifest"];
            meta: components["schemas"]["ApiMeta"];
        };
        BundleExportVerification: {
            ok: boolean;
            expectedHash: string;
            actualHash: string | null;
            issues: string[];
        };
        BundleExportVerificationFailedResponse: {
            error: string;
            verification: components["schemas"]["BundleExportVerification"];
            manifest: components["schemas"]["BundleExportManifest"];
            meta: components["schemas"]["ApiMeta"];
        };
        ComplianceExportResponse: {
            /** @example spctre/v1 */
            schemaVersion: string;
            /** Format: date-time */
            exportedAt: string;
            artifact: Record<string, never>;
            approvals?: Record<string, never>[];
            timeline?: Record<string, never>[];
            summary: {
                evidenceCount?: number;
                approvalCount?: number;
                policyRefCount?: number;
                deniedDecisionCount?: number;
                warnedDecisionCount?: number;
                simulationEventCount?: number;
                packageSections?: string[];
                resolvedEscalationCount?: number;
            };
            escalations: Record<string, never>[];
            verificationResults: Record<string, never> | null;
            frameworkAnnotation: Record<string, never> | null;
            retentionPlan: Record<string, never> | null;
        };
        EvaluateRequest: {
            connector: string;
            action: string;
            /** @description Optional domain tags used for additional policy matching. */
            domains?: string[];
            /** @description The explicitly declared intent or purpose of the tool call. */
            toolIntent?: string;
            /** @description A high-level plan summary explicitly provided by the runtime. */
            planSummary?: string;
            /** @description The structured arguments passed to the tool. */
            toolParameters?: {
                [key: string]: unknown;
            };
        };
        EvaluateResponse: {
            connector: string;
            action: string;
            domains?: string[];
            branchId?: string;
            revisionId?: string;
            artifactHash?: string;
            /** Format: date-time */
            publishedAt?: string;
            /** @description Policy evaluation result from the published bundle. */
            result: Record<string, never>;
            meta: components["schemas"]["ApiMeta"];
        };
        VerificationIngestRequest: {
            artifactHash: string;
            /** @enum {string} */
            verificationType: "AGT_VERIFY" | "AGT_VERIFY_EVIDENCE" | "AGT_LINT_POLICY" | "AGT_REDTEAM" | "AGT_REPLAY" | "CUSTOM";
            /** @enum {string} */
            outcome: "PASS" | "FAIL" | "WARN";
            revisionId?: string;
            runtimeVersion?: string;
            argumentsHash?: string;
            approverDid?: string;
            policyVersion?: string;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            agtVersion?: string;
            agtPoliciesVersion?: string;
            cedarPolicyVersion?: string;
            policyEngineVersion?: string;
            /** Format: date-time */
            compatibilityCheckedAt?: string;
            /** @enum {string} */
            compatibilityCheckOutcome?: "PASS" | "FAIL" | "WARN";
            escrowSignerId?: string;
            escrowKeyId?: string;
            outcomeHash?: string;
            escrowSignature?: string;
            /** @enum {string} */
            escrowVerificationOutcome?: "PASS" | "FAIL" | "WARN";
            /** Format: date-time */
            escrowVerifiedAt?: string;
            /** @description Arbitrary verification summary payload. */
            summary?: Record<string, never>;
        };
        VerificationIngestResponse: {
            ok: boolean;
            id?: string;
            /** @enum {string} */
            outcome: "PASS" | "FAIL" | "WARN";
            meta: components["schemas"]["ApiMeta"];
        };
        ApprovalResponse: {
            /** @description The approval record for the requested revision. */
            approval: Record<string, never>;
            meta: components["schemas"]["ApiMeta"];
        };
    };
    responses: {
        /** @description Authentication required or token invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Token lacks the required scope for this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Request body failed schema validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Database or upstream dependency unavailable. */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description This endpoint requires the Spctre Cloud plan. OSS tenants receive this structured error rather than a 404. */
        CloudOnly: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"] & {
                    /**
                     * @description Required plan tier.
                     * @enum {string}
                     */
                    plan?: "cloud";
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ingestEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceIngestRequest"];
            };
        };
        responses: {
            /** @description Duplicate submission — evidence with this decisionId already exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceIngestResponse"];
                };
            };
            /** @description Evidence ingested successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceIngestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    ingestGitCheckpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitCheckpointIngestRequest"];
            };
        };
        responses: {
            /** @description Duplicate submission suppressed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceIngestResponse"];
                };
            };
            /** @description Checkpoint evidence ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceIngestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    gatewayDecide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayDecisionRequest"];
            };
        };
        responses: {
            /** @description Decision evaluated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayDecisionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    gatewayResolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayResolveRequest"];
            };
        };
        responses: {
            /** @description Escalation resolved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        meta?: components["schemas"]["ApiMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listEscalations: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Escalation queue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        queue?: components["schemas"]["EscalationQueueItem"][];
                        count?: number;
                        /** Format: date-time */
                        generatedAt?: string;
                        pagination?: components["schemas"]["Pagination"];
                        meta?: components["schemas"]["ApiMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getEscalationStatus: {
        parameters: {
            query: {
                /** @description The unique gateway decision ID. */
                decisionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Escalation status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EscalationStatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    ingestPortkeyGatewayEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayWebhookRequest"];
            };
        };
        responses: {
            /** @description Duplicate gateway event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayIngestResponse"];
                };
            };
            /** @description Gateway event ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayIngestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["BadRequest"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    ingestHeliconeGatewayEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayWebhookRequest"];
            };
        };
        responses: {
            /** @description Duplicate gateway event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayIngestResponse"];
                };
            };
            /** @description Gateway event ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayIngestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["BadRequest"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    ingestLiteLLMGatewayEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayWebhookRequest"];
            };
        };
        responses: {
            /** @description Duplicate gateway event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayIngestResponse"];
                };
            };
            /** @description Gateway event ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayIngestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["BadRequest"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional client-generated key for retrying a refresh request. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description Token pair rotated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    ingestTrustScore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrustScoreIngestRequest"];
            };
        };
        responses: {
            /** @description Trust score ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    evaluateTrustGovernance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrustEvaluateRequest"];
            };
        };
        responses: {
            /** @description Trust governance evaluated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    ingestContextBudgetEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextBudgetIngestRequest"];
            };
        };
        responses: {
            /** @description Context-budget event ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getBundleLatest: {
        parameters: {
            query?: {
                /** @description Optional target export format. Omit for the raw AGT-compatible bundle. */
                format?: components["schemas"]["BundleExportFormat"];
                /** @description When true and format is omitted, returns manifests for all supported export targets without artifacts. */
                preview?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest published bundle, export envelope, or preview manifest list. */
            200: {
                headers: {
                    "x-spctre-branch-id"?: string;
                    "x-spctre-revision-id"?: string;
                    "x-spctre-artifact-hash"?: string;
                    "x-spctre-published-at"?: string;
                    "x-spctre-export-format"?: string;
                    "x-spctre-export-ok"?: "true" | "false";
                    "x-spctre-export-verified"?: "true" | "false";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleResponse"] | components["schemas"]["BundleExportEnvelope"] | components["schemas"]["BundleExportPreviewResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Requested export target is blocked because semantics cannot be safely preserved. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleExportBlockedResponse"];
                };
            };
            /** @description Export artifact failed local manifest verification before handoff. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleExportVerificationFailedResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    exportCompliance: {
        parameters: {
            query?: {
                /** @description Framework to annotate the export for. When omitted the raw packet is returned without framework-specific annotations. */
                framework?: "soc2" | "iso27001" | "hipaa" | "gdpr" | "pci-dss" | "nist-ai-rmf" | "public-sector" | "eu-ai-act";
                /** @description Export format. PDF export is plan-gated. */
                format?: "json" | "pdf";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compliance packet. */
            200: {
                headers: {
                    "x-spctre-artifact-hash"?: string;
                    "x-spctre-revision-id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceExportResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    evaluatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Evaluation result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listVerifications: {
        parameters: {
            query?: {
                revisionId?: string;
                artifactHash?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results?: Record<string, never>[];
                        count?: number;
                        /** Format: date-time */
                        generatedAt?: string;
                        pagination?: components["schemas"]["Pagination"];
                        meta?: components["schemas"]["ApiMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    ingestVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationIngestRequest"];
            };
        };
        responses: {
            /** @description Verification result ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationIngestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The approval ID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approval record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3.1 spec. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    forensicEvidenceQuery: {
        parameters: {
            query?: {
                /** @description Start of the time window (inclusive). */
                from?: string;
                /** @description End of the time window (exclusive). */
                to?: string;
                /** @description Pagination cursor from a previous response. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forensic evidence page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["CloudOnly"];
        };
    };
    bulkSimulate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The policy revision to simulate against the historical log. */
                    revisionId: string;
                    /** Format: date-time */
                    fromDate?: string;
                    /** Format: date-time */
                    toDate?: string;
                };
            };
        };
        responses: {
            /** @description Simulation job accepted. Poll the returned jobId for results. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        jobId?: string;
                        meta?: components["schemas"]["ApiMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["CloudOnly"];
        };
    };
    scimListUsers: {
        parameters: {
            query?: {
                filter?: string;
                startIndex?: number;
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SCIM ListResponse. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/scim+json": Record<string, never>;
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["CloudOnly"];
        };
    };
    scimCreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/scim+json": Record<string, never>;
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/scim+json": Record<string, never>;
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["CloudOnly"];
        };
    };
}
