import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  MACHINE_API_PATH_PATTERNS,
  MACHINE_API_PATH_PREFIXES,
  MACHINE_API_PATHS,
  PUBLIC_PATH_PREFIXES,
  PUBLIC_PATHS,
  SERVICE_API_PATH_PREFIXES,
  SERVICE_API_PATHS,
  SERVICE_API_PATH_PATTERNS,
} from "@/lib/proxy-paths";

// The control plane's half of the contract with the MCP server.
//
// packages/mcp-server/control-plane-dependencies.json is generated by running
// that server's handlers against a recording context, so it states what the
// server actually calls rather than what anyone believes it calls. This asserts
// the control plane can serve each of those calls: the route exists, it accepts
// the declared service-token scope, and both proxy gates let a machine caller
// through.
//
// Every one of these was broken at some point, and each failed the same quiet
// way — a 401 or 403 from the proxy that looked like an ordinary auth error,
// while the MCP server cached the failure and fell back to its env-var
// allowlists. Checking one endpoint at a time is how it took four rounds to
// find them all.

const MANIFEST = join(
  process.cwd(),
  "..",
  "..",
  "packages",
  "mcp-server",
  "control-plane-dependencies.json",
);

interface Dependency {
  method: "GET" | "POST";
  path: string;
  scope: string;
}

const manifest = JSON.parse(readFileSync(MANIFEST, "utf8")) as {
  dependencies: Dependency[];
  unimplemented: Array<{ path: string; reason: string }>;
};

/** Paths knowingly not served yet, asserted below to be exactly this set. */
const UNIMPLEMENTED = new Set(manifest.unimplemented.map((entry) => entry.path));

/** `/api/agents/{id}/audit` → `app/api/agents/[id]/audit/route.ts`. */
function routeFileFor(path: string): string {
  const relative = path.replace(/^\/api\//, "").replace(/\{(\w+)\}/g, "[$1]");
  return join(process.cwd(), "app", "api", relative, "route.ts");
}

/** A concrete path, since the gates match strings rather than templates. */
function concrete(path: string): string {
  return path.replace(/\{(\w+)\}/g, "sample-id");
}

function reachablePastSessionGate(pathname: string): boolean {
  return (
    PUBLIC_PATHS.has(pathname) ||
    PUBLIC_PATH_PREFIXES.some((prefix) => pathname.startsWith(prefix)) ||
    SERVICE_API_PATHS.has(pathname) ||
    SERVICE_API_PATH_PREFIXES.some((prefix) => pathname.startsWith(prefix)) ||
    pathname === "/api/auth" ||
    pathname.startsWith("/api/auth/") ||
    SERVICE_API_PATH_PATTERNS.some((pattern) => pattern.test(pathname))
  );
}

function exemptFromSourceIpGate(pathname: string): boolean {
  return (
    MACHINE_API_PATHS.has(pathname) ||
    MACHINE_API_PATH_PREFIXES.some((prefix) => pathname.startsWith(prefix)) ||
    MACHINE_API_PATH_PATTERNS.some((pattern) => pattern.test(pathname))
  );
}

/** Scopes the handler will accept, including any reached through a helper. */
function declaredScopes(routeFile: string): string[] {
  let source = readFileSync(routeFile, "utf8");

  // One level of re-export shim, as the /api/v1 twins use.
  const shim = source.match(/export \* from "([^"]+)"/);
  if (shim && source.trim().split("\n").length <= 3) {
    const target = join(routeFile, "..", `${shim[1]}.ts`);
    if (existsSync(target)) source = readFileSync(target, "utf8");
  }

  const direct = [
    ...source.matchAll(/serviceTokenScope:\s*"([a-z:]+)"/g),
    ...source.matchAll(/authenticateServiceToken\([^,]+,\s*"([a-z:]+)"/g),
  ].map((match) => match[1]);
  if (direct.length) return [...new Set(direct)];

  // Routes that delegate authentication to a shared helper or domain service.
  // Follow local imports one level rather than reporting a false negative.
  const imports = [...source.matchAll(/from "(@\/[^"]+|\.\.?\/[^"]+)"/g)].map((match) => match[1]);
  const scopes = new Set<string>();
  for (const specifier of imports) {
    const base = specifier.startsWith("@/")
      ? join(process.cwd(), specifier.slice(2))
      : join(routeFile, "..", specifier);
    for (const candidate of [`${base}.ts`, join(base, "index.ts")]) {
      if (!existsSync(candidate)) continue;
      const helper = readFileSync(candidate, "utf8");
      for (const match of helper.matchAll(/authenticateServiceToken\([^,]+,\s*"([a-z:]+)"/g)) {
        scopes.add(match[1]);
      }
    }
  }
  return [...scopes];
}

const served = manifest.dependencies.filter((dependency) => !UNIMPLEMENTED.has(dependency.path));

describe("MCP dependency contract", () => {
  it("declares dependencies at all", () => {
    // The manifest is read from another package, so an empty or malformed file
    // would make every assertion below vacuously pass.
    expect(manifest.dependencies.length).toBeGreaterThan(10);
  });

  it("implements every dependency", () => {
    const missing = served
      .filter((dependency) => !existsSync(routeFileFor(dependency.path)))
      .map((dependency) => dependency.path);

    expect(missing).toEqual([]);
  });

  it("accepts the declared scope on every dependency", () => {
    const mismatched = served
      .filter((dependency) => existsSync(routeFileFor(dependency.path)))
      .filter(
        (dependency) => !declaredScopes(routeFileFor(dependency.path)).includes(dependency.scope),
      )
      .map((dependency) => ({
        path: dependency.path,
        declared: dependency.scope,
        accepts: declaredScopes(routeFileFor(dependency.path)),
      }));

    expect(mismatched).toEqual([]);
  });

  it("reaches every dependency past the session gate", () => {
    const stranded = served
      .filter((dependency) => !reachablePastSessionGate(concrete(dependency.path)))
      .map((dependency) => dependency.path);

    expect(stranded).toEqual([]);
  });

  it("exempts every dependency from the source-IP allowlist", () => {
    // The MCP server runs on Cloud Run and egresses from an address that can
    // never be an operator address.
    const blocked = served
      .filter((dependency) => !exemptFromSourceIpGate(concrete(dependency.path)))
      .map((dependency) => dependency.path);

    expect(blocked).toEqual([]);
  });

  it("holds the unimplemented list to exactly what is known", () => {
    // Excusing a dependency from the assertions above is a decision, so the
    // excuse list is pinned. It is empty now that GET /api/evidence/{id}
    // exists; a new excuse cannot be added without changing this line.
    expect([...UNIMPLEMENTED]).toEqual([]);
  });
});
