# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.
#
# This adapter governs the public Google Antigravity Python SDK
# (github.com/google-antigravity/antigravity-sdk-python):
#   pip install google-antigravity
#   .spctre/spctre-python python your_agent.py
#
# Patch targets (verified against the SDK source):
#   ToolRunner.execute(self, tool_name, **kwargs)          — single tool call
#   ToolRunner.process_tool_calls(self, tool_calls)        — concurrent batch;
#     returns ToolResult(name=..., result=..., error=...) per call and does not
#     route through execute(), so patching both never double-emits.
# Token usage (types.UsageMetadata) is attached to conversation steps, not tool
# results. The adapter therefore also patches the public Conversation.receive_steps
# iterator and emits one usage record after each completed turn.

import asyncio
import importlib
import importlib.metadata
import json
import os
import threading
import time
import urllib.request
import uuid
from urllib.parse import quote

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_GATEWAY_URL = os.environ.get("SPCTRE_GATEWAY_URL", _SPCTRE_URL).rstrip("/")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_WORKSPACE = os.environ.get("SPCTRE_WORKSPACE", "__SPCTRE_WORKSPACE_ID__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_SESSION_ID = os.environ.get("SPCTRE_SESSION_ID") or f"antigravity-sdk-{os.getpid()}"
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)
_SPCTRE_MODE = os.environ.get("SPCTRE_ANTIGRAVITY_SDK_MODE", "observe").lower()
_SPCTRE_OUTAGE_POLICY = os.environ.get("SPCTRE_GATEWAY_OUTAGE_POLICY", "fail-closed").lower()
_SPCTRE_GATEWAY_TIMEOUT = max(5, int(os.environ.get("SPCTRE_GATEWAY_TIMEOUT", "1800")))
_SPCTRE_GATEWAY_POLL_INTERVAL = max(2, int(os.environ.get("SPCTRE_GATEWAY_POLL_INTERVAL", "10")))
_SPCTRE_EXPECTED_SDK_VERSION = os.environ.get("SPCTRE_ANTIGRAVITY_SDK_EXPECTED_VERSION", "").strip()
_SPCTRE_PENDING_GATEWAY_DECISIONS = {}


def _spctre_emit(
    action,
    status,
    reason,
    latency_ms=0,
    prompt_tokens=None,
    completion_tokens=None,
    total_tokens=None,
):
    if not _SPCTRE_KEY:
        return
    has_context = bool(_SPCTRE_POLICY_CONTEXT and _SPCTRE_POLICY_CONTEXT[0].get("artifactHash"))
    policy_refs = (
        ["system.governance_active"]
        if action == "governance_active"
        else ([f"google-antigravity.tool.{action}"] if has_context else ["gateway.provenance-gap"])
    )
    payload = {
        "decisionId": f"antigravity-sdk-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": "CUSTOM", "adapter": "spctre-antigravity-sdk-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": "google-antigravity",
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": policy_refs,
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "antigravity-sdk-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "antigravity-sdk-hook",
        "ingestMode": "gateway",
        "rawEvidence": {
            "_source": "gateway",
            "_gateway_provider": "antigravity-sdk-hook",
            "_framework": "antigravity-sdk",
        },
    }
    if prompt_tokens is not None:
        payload["promptTokens"] = prompt_tokens
        payload["rawEvidence"]["promptTokens"] = prompt_tokens
    if completion_tokens is not None:
        payload["completionTokens"] = completion_tokens
        payload["rawEvidence"]["completionTokens"] = completion_tokens
    if total_tokens is not None:
        payload["totalTokens"] = total_tokens
        payload["rawEvidence"]["totalTokens"] = total_tokens
    elif prompt_tokens is not None and completion_tokens is not None:
        payload["totalTokens"] = prompt_tokens + completion_tokens
        payload["rawEvidence"]["totalTokens"] = prompt_tokens + completion_tokens
    try:
        request = urllib.request.Request(
            f"{_SPCTRE_URL}/api/v1/evidence",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {_SPCTRE_KEY}",
                "x-spctre-source": "gateway",
            },
            method="POST",
        )
        urllib.request.urlopen(request, timeout=3)
    except Exception:
        pass


def _spctre_emit_async(
    action,
    status,
    reason,
    latency_ms=0,
    prompt_tokens=None,
    completion_tokens=None,
    total_tokens=None,
):
    threading.Thread(
        target=_spctre_emit,
        args=(action, status, reason, latency_ms, prompt_tokens, completion_tokens, total_tokens),
        daemon=False,
    ).start()


def _spctre_action(name):
    return str(name or "unknown_tool").lower().replace(" ", "_").replace("-", "_")


def _spctre_install_antigravity_sdk_hooks():
    try:
        module = importlib.import_module("google.antigravity.tools.tool_runner")
        ToolRunner = getattr(module, "ToolRunner", None)
        if ToolRunner is None or getattr(ToolRunner, "_spctre_patched", False):
            return

        original_execute = getattr(ToolRunner, "execute", None)
        original_process_tool_calls = getattr(ToolRunner, "process_tool_calls", None)
        if not callable(original_execute) or not callable(original_process_tool_calls):
            return

        async def _patched_execute(self, tool_name, **kwargs):
            action = _spctre_action(tool_name)
            start = time.monotonic()
            try:
                result = await original_execute(self, tool_name, **kwargs)
                _spctre_emit_async(
                    action,
                    "ALLOW",
                    f"Tool {tool_name} invoked successfully.",
                    int((time.monotonic() - start) * 1000),
                )
                return result
            except Exception as exc:
                _spctre_emit_async(
                    action,
                    "DENY",
                    f"Tool {tool_name} raised {type(exc).__name__}: {exc}",
                    int((time.monotonic() - start) * 1000),
                )
                raise

        async def _patched_process_tool_calls(self, tool_calls):
            start = time.monotonic()
            try:
                results = await original_process_tool_calls(self, tool_calls)
                for result in results:
                    action = _spctre_action(getattr(result, "name", None))
                    status = "DENY" if getattr(result, "error", None) else "ALLOW"
                    _spctre_emit_async(
                        action,
                        status,
                        "Tool call batch completed.",
                        int((time.monotonic() - start) * 1000),
                    )
                return results
            except Exception as exc:
                _spctre_emit_async(
                    "tool_call_batch",
                    "DENY",
                    f"Tool call batch raised {type(exc).__name__}: {exc}",
                    int((time.monotonic() - start) * 1000),
                )
                raise

        ToolRunner.execute = _patched_execute
        ToolRunner.process_tool_calls = _patched_process_tool_calls
        ToolRunner._spctre_patched = True
        _spctre_emit_async(
            "governance_active",
            "ALLOW",
            "Google Antigravity SDK ToolRunner governance adapter patched and active.",
        )
    except Exception:
        pass


def _spctre_usage_value(usage, field):
    value = getattr(usage, field, None)
    return value if isinstance(value, int) else 0


def _spctre_session_id(tool_call):
    """Use a native conversation/run ID when the SDK exposes one."""
    for key in ("session_id", "sessionId", "conversation_id", "conversationId", "run_id", "runId"):
        value = getattr(tool_call, key, None)
        if value:
            return str(value)
    return _SPCTRE_SESSION_ID


def _spctre_gateway_decide(tool_call):
    if not _SPCTRE_KEY:
        raise RuntimeError("SPCTRE_API_TOKEN is required for Antigravity SDK enforcement.")
    tool_name = getattr(tool_call, "name", None)
    tool_input = getattr(tool_call, "args", None)
    if not isinstance(tool_input, dict):
        tool_input = {}
    decision_id = getattr(tool_call, "id", None) or f"antigravity-sdk-{uuid.uuid4()}"
    payload = {
        "decisionId": decision_id,
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "antigravity-sdk-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "connector": "google-antigravity",
        "agentId": _SPCTRE_AGENT,
        "sessionId": _spctre_session_id(tool_call),
        "action": _spctre_action(tool_name),
        "toolIntent": str(tool_name or "unknown_tool"),
        "toolParameters": tool_input,
    }
    request = urllib.request.Request(
        f"{_SPCTRE_GATEWAY_URL}/api/v1/gateway/decide",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {_SPCTRE_KEY}"},
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=3) as response:
        body = json.loads(response.read().decode() or "{}")
    decision = body.get("decision") if isinstance(body, dict) else {}
    return (
        str(decision.get("outcome") or "ABORT").upper(),
        str(decision.get("reason") or "Spctre gateway did not provide a reason."),
        decision_id,
        bool(body.get("queued")) if isinstance(body, dict) else False,
    )


def _spctre_wait_for_resolution(decision_id):
    deadline = time.monotonic() + _SPCTRE_GATEWAY_TIMEOUT
    url = f"{_SPCTRE_GATEWAY_URL}/api/v1/gateway/escalations/status?decisionId={quote(str(decision_id))}"
    while time.monotonic() < deadline:
        request = urllib.request.Request(
            url, headers={"Authorization": f"Bearer {_SPCTRE_KEY}"}, method="GET"
        )
        try:
            with urllib.request.urlopen(request, timeout=3) as response:
                body = json.loads(response.read().decode() or "{}")
            if body.get("status") == "RESOLVED":
                outcome = str(body.get("resolutionOutcome") or "ABORT").upper()
                reason = str(
                    body.get("resolutionNote")
                    or body.get("agentGuidance")
                    or f"Spctre escalation resolved: {outcome}."
                )
                return outcome == "PROCEED", reason
            if body.get("status") == "EXPIRED":
                return False, "Spctre escalation expired; fail-closed."
        except Exception:
            pass
        time.sleep(_SPCTRE_GATEWAY_POLL_INTERVAL)
    return False, "Spctre escalation timed out; fail-closed."


def _spctre_install_antigravity_enforcement_hook():
    """Attach a gateway gate and native ask_user policy to each Agent config."""
    if _SPCTRE_MODE != "enforce":
        return
    try:
        if _SPCTRE_EXPECTED_SDK_VERSION:
            installed_version = importlib.metadata.version("google-antigravity")
            if installed_version != _SPCTRE_EXPECTED_SDK_VERSION:
                raise RuntimeError(
                    f"google-antigravity {installed_version} does not match required {_SPCTRE_EXPECTED_SDK_VERSION}."
                )
        agent_module = importlib.import_module("google.antigravity.agent")
        hooks_module = importlib.import_module("google.antigravity.hooks")
        types_module = importlib.import_module("google.antigravity.types")
        policy_module = importlib.import_module("google.antigravity.hooks.policy")
        Agent = getattr(agent_module, "Agent", None)
        HookResult = getattr(types_module, "HookResult", None)
        hook_decorator = getattr(hooks_module, "pre_tool_call_decide", None)
        ask_user = getattr(policy_module, "ask_user", None)
        if (
            Agent is None
            or HookResult is None
            or not callable(hook_decorator)
            or not callable(ask_user)
            or getattr(Agent, "_spctre_enforcement_patched", False)
        ):
            return

        @hook_decorator
        async def _spctre_pre_tool_call_decide(tool_call):
            tool_name = getattr(tool_call, "name", None)
            try:
                outcome, reason, decision_id, queued = await asyncio.to_thread(
                    _spctre_gateway_decide, tool_call
                )
            except Exception as exc:
                if _SPCTRE_OUTAGE_POLICY == "fail-open":
                    _spctre_emit_async(
                        _spctre_action(tool_name),
                        "WARN",
                        f"Gateway unavailable; fail-open allowed execution ({type(exc).__name__}).",
                    )
                    return HookResult(allow=True)
                outcome, reason, decision_id, queued = (
                    "ABORT",
                    f"Spctre gateway unavailable; fail-closed ({type(exc).__name__}).",
                    None,
                    False,
                )

            if outcome == "PROCEED":
                _SPCTRE_PENDING_GATEWAY_DECISIONS[getattr(tool_call, "id", None) or decision_id] = (
                    outcome,
                    reason,
                    decision_id,
                    queued,
                )
                return HookResult(allow=True, message=reason)
            if outcome == "ESCALATE" and queued:
                allowed, resolution_reason = await asyncio.to_thread(
                    _spctre_wait_for_resolution, decision_id
                )
                if allowed:
                    _SPCTRE_PENDING_GATEWAY_DECISIONS[
                        getattr(tool_call, "id", None) or decision_id
                    ] = ("PROCEED", resolution_reason, decision_id, False)
                    return HookResult(allow=True, message=resolution_reason)
                _spctre_emit_async(_spctre_action(tool_name), "ESCALATE", resolution_reason)
                return HookResult(allow=False, message=resolution_reason)
            status = "ESCALATE" if outcome == "ESCALATE" else "DENY"
            _spctre_emit_async(_spctre_action(tool_name), status, reason)
            return HookResult(allow=False, message=reason)

        async def _spctre_ask_user(tool_call):
            key = getattr(tool_call, "id", None)
            pending = _SPCTRE_PENDING_GATEWAY_DECISIONS.pop(key, None)
            if pending is None:
                try:
                    pending = await asyncio.to_thread(_spctre_gateway_decide, tool_call)
                except Exception as exc:
                    if _SPCTRE_OUTAGE_POLICY == "fail-open":
                        return True
                    _spctre_emit_async(
                        _spctre_action(getattr(tool_call, "name", None)),
                        "DENY",
                        f"Spctre gateway unavailable; fail-closed ({type(exc).__name__}).",
                    )
                    return False
            outcome, reason, decision_id, queued = pending
            if outcome == "PROCEED":
                return True
            if outcome == "ESCALATE" and queued and decision_id:
                allowed, resolution_reason = await asyncio.to_thread(
                    _spctre_wait_for_resolution, decision_id
                )
                _spctre_emit_async(
                    _spctre_action(getattr(tool_call, "name", None)),
                    "ALLOW" if allowed else "ESCALATE",
                    resolution_reason,
                )
                return allowed
            _spctre_emit_async(_spctre_action(getattr(tool_call, "name", None)), "DENY", reason)
            return False

        original_init = getattr(Agent, "__init__", None)
        if not callable(original_init):
            return

        def _patched_init(self, config, *args, **kwargs):
            hooks = list(getattr(config, "hooks", []) or [])
            hooks.append(_spctre_pre_tool_call_decide)
            policies = list(getattr(config, "policies", []) or [])
            policies.append(
                ask_user("*", handler=_spctre_ask_user, name="spctre_gateway_human_review")
            )
            model_copy = getattr(config, "model_copy", None)
            if not callable(model_copy):
                raise RuntimeError(
                    "Antigravity AgentConfig does not support model_copy; refusing unverified enforcement install."
                )
            return original_init(
                self, model_copy(update={"hooks": hooks, "policies": policies}), *args, **kwargs
            )

        Agent.__init__ = _patched_init
        Agent._spctre_enforcement_patched = True
        _spctre_emit_async(
            "governance_active",
            "ALLOW",
            "Google Antigravity SDK native gateway and ask_user policy installed.",
        )
    except Exception as exc:
        # Observe-mode telemetry is intentionally best-effort, but an explicit
        # enforcement opt-in must never degrade to an unpatched runtime.
        raise RuntimeError(
            "Unable to install Google Antigravity SDK enforcement; refusing ungoverned startup."
        ) from exc


def _spctre_install_antigravity_usage_hook():
    """Capture turn totals through public Conversation APIs, not tool results."""
    try:
        module = importlib.import_module("google.antigravity.conversation.conversation")
        Conversation = getattr(module, "Conversation", None)
        if Conversation is None or getattr(Conversation, "_spctre_usage_patched", False):
            return
        original_receive_steps = getattr(Conversation, "receive_steps", None)
        if not callable(original_receive_steps):
            return

        async def _patched_receive_steps(self, *args, **kwargs):
            before = self.total_usage
            start = time.monotonic()
            async for step in original_receive_steps(self, *args, **kwargs):
                yield step
            after = self.total_usage
            prompt_tokens = max(
                0,
                _spctre_usage_value(after, "prompt_token_count")
                - _spctre_usage_value(before, "prompt_token_count"),
            )
            completion_tokens = max(
                0,
                (
                    _spctre_usage_value(after, "candidates_token_count")
                    + _spctre_usage_value(after, "thoughts_token_count")
                )
                - (
                    _spctre_usage_value(before, "candidates_token_count")
                    + _spctre_usage_value(before, "thoughts_token_count")
                ),
            )
            total_tokens = max(
                0,
                _spctre_usage_value(after, "total_token_count")
                - _spctre_usage_value(before, "total_token_count"),
            )
            if total_tokens or prompt_tokens or completion_tokens:
                _spctre_emit_async(
                    "llm_turn",
                    "ALLOW",
                    "Antigravity SDK turn completed with token usage.",
                    int((time.monotonic() - start) * 1000),
                    prompt_tokens,
                    completion_tokens,
                    total_tokens,
                )

        Conversation.receive_steps = _patched_receive_steps
        Conversation._spctre_usage_patched = True
    except Exception:
        pass


_spctre_install_antigravity_sdk_hooks()
_spctre_install_antigravity_usage_hook()
_spctre_install_antigravity_enforcement_hook()
