# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.
#
# Use the generated wrapper to enable zero-change AutoGen governance:
#   .spctre/spctre-python python your_agent.py

import importlib
import json
import os
import threading
import time
import urllib.request
import uuid

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_WORKSPACE = os.environ.get("SPCTRE_WORKSPACE", "__SPCTRE_WORKSPACE_ID__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)


def _spctre_emit(
    connector, action, status, reason, latency_ms=0, prompt_tokens=None, completion_tokens=None
):
    if not _SPCTRE_KEY:
        return
    has_context = bool(_SPCTRE_POLICY_CONTEXT and _SPCTRE_POLICY_CONTEXT[0].get("artifactHash"))
    policy_refs = (
        ["system.governance_active"]
        if action == "governance_active"
        else ([f"autogen.tool.{action}"] if has_context else ["gateway.provenance-gap"])
    )
    payload = {
        "decisionId": f"autogen-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": "AUTOGEN", "adapter": "spctre-autogen-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": "autogen",
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": policy_refs,
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "autogen-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "autogen-hook",
        "ingestMode": "gateway",
        "rawEvidence": {
            "_source": "gateway",
            "_gateway_provider": "autogen-hook",
            "_framework": "autogen",
        },
    }
    if prompt_tokens is not None:
        payload["promptTokens"] = prompt_tokens
        payload["rawEvidence"]["promptTokens"] = prompt_tokens
    if completion_tokens is not None:
        payload["completionTokens"] = completion_tokens
        payload["rawEvidence"]["completionTokens"] = completion_tokens
    if prompt_tokens is not None and completion_tokens is not None:
        payload["totalTokens"] = prompt_tokens + completion_tokens
        payload["rawEvidence"]["totalTokens"] = prompt_tokens + completion_tokens
    try:
        req = urllib.request.Request(
            f"{_SPCTRE_URL}/api/evidence",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {_SPCTRE_KEY}",
                "x-spctre-source": "gateway",
            },
            method="POST",
        )
        urllib.request.urlopen(req, timeout=3)
    except Exception:
        pass  # Evidence emission is non-fatal; agent continues regardless.


def _extract_autogen_usage(result):
    """Extract token counts from an AutoGen v0.4 CreateResult or v0.2 reply."""
    try:
        usage = getattr(result, "usage", None)
        if usage is not None:
            if hasattr(usage, "prompt_tokens"):
                return usage.prompt_tokens, usage.completion_tokens
            if isinstance(usage, dict):
                return usage.get("prompt_tokens"), usage.get("completion_tokens")
        if isinstance(result, dict):
            us = result.get("usage_summary") or result.get("usage")
            if us and isinstance(us, dict):
                return us.get("prompt_tokens"), us.get("completion_tokens")
    except Exception:
        pass
    return None, None


def _spctre_install_autogen_hook():
    # AutoGen v0.4+ (autogen-agentchat / autogen-core)
    try:
        module = importlib.import_module("autogen_core.tools")
        FunctionTool = getattr(module, "FunctionTool", None)

        if FunctionTool is not None and not getattr(FunctionTool, "_spctre_patched", False):
            _original_run_json = getattr(FunctionTool, "run_json", None)
            if not callable(_original_run_json):
                raise AttributeError("FunctionTool.run_json is not callable")

            async def _patched_run_json(self, args, cancellation_token):
                tool_name = getattr(self, "name", None) or type(self).__name__
                action = tool_name.lower().replace(" ", "_").replace("-", "_")
                start = time.monotonic()
                try:
                    result = await _original_run_json(self, args, cancellation_token)
                    latency_ms = int((time.monotonic() - start) * 1000)
                    threading.Thread(
                        target=_spctre_emit,
                        args=(
                            "autogen",
                            action,
                            "ALLOW",
                            f"Tool {tool_name} invoked successfully.",
                            latency_ms,
                        ),
                        daemon=False,
                    ).start()
                    return result
                except Exception as exc:
                    latency_ms = int((time.monotonic() - start) * 1000)
                    threading.Thread(
                        target=_spctre_emit,
                        args=(
                            "autogen",
                            action,
                            "DENY",
                            f"Tool {tool_name} raised {type(exc).__name__}: {exc}",
                            latency_ms,
                        ),
                        daemon=False,
                    ).start()
                    raise

            FunctionTool.run_json = _patched_run_json
            FunctionTool._spctre_patched = True
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "autogen",
                    "governance_active",
                    "ALLOW",
                    "AutoGen governance adapter patched and active.",
                    0,
                ),
                daemon=False,
            ).start()
            return  # v0.4 hook installed; skip v0.2 path.
    except Exception:
        pass

    # AutoGen v0.2 (pyautogen)
    try:
        module = importlib.import_module("autogen")
        ConversableAgent = getattr(module, "ConversableAgent", None)
        if ConversableAgent is None:
            return

        if not getattr(ConversableAgent, "_spctre_patched", False):
            _original_execute_function = getattr(ConversableAgent, "execute_function", None)
            if not callable(_original_execute_function):
                return  # API shape not recognized; hook inactive.

            def _patched_execute_function(self, func_call, verbose=False):
                tool_name = (
                    func_call.get("name", "unknown") if isinstance(func_call, dict) else "unknown"
                )
                action = tool_name.lower().replace(" ", "_").replace("-", "_")
                start = time.monotonic()
                try:
                    success, result = _original_execute_function(self, func_call, verbose)
                    latency_ms = int((time.monotonic() - start) * 1000)
                    status = "ALLOW" if success else "DENY"
                    reason = f"Tool {tool_name} executed with success={success}."
                    threading.Thread(
                        target=_spctre_emit,
                        args=("autogen", action, status, reason, latency_ms),
                        daemon=False,
                    ).start()
                    return success, result
                except Exception as exc:
                    latency_ms = int((time.monotonic() - start) * 1000)
                    threading.Thread(
                        target=_spctre_emit,
                        args=(
                            "autogen",
                            action,
                            "DENY",
                            f"Tool {tool_name} raised {type(exc).__name__}: {exc}",
                            latency_ms,
                        ),
                        daemon=False,
                    ).start()
                    raise

            ConversableAgent.execute_function = _patched_execute_function
            ConversableAgent._spctre_patched = True
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "autogen",
                    "governance_active",
                    "ALLOW",
                    "AutoGen governance adapter patched and active.",
                    0,
                ),
                daemon=False,
            ).start()
    except Exception:
        pass  # Neither autogen_core nor autogen installed; hook inactive.


def _spctre_install_autogen_model_hook():
    """Patch autogen_core ChatCompletionClient.create to capture token usage."""
    try:
        module = importlib.import_module("autogen_core.models")
        ChatCompletionClient = getattr(module, "ChatCompletionClient", None)
        if ChatCompletionClient is None:
            return

        if getattr(ChatCompletionClient, "_spctre_model_patched", False):
            return

        _original_create = getattr(ChatCompletionClient, "create", None)
        if not callable(_original_create):
            return

        async def _patched_create(self, *args, **kwargs):
            start = time.monotonic()
            result = await _original_create(self, *args, **kwargs)
            latency_ms = int((time.monotonic() - start) * 1000)
            prompt_tokens, completion_tokens = _extract_autogen_usage(result)
            if prompt_tokens is not None or completion_tokens is not None:
                threading.Thread(
                    target=_spctre_emit,
                    args=(
                        "autogen",
                        "llm_call",
                        "ALLOW",
                        "AutoGen model create completed.",
                        latency_ms,
                        prompt_tokens,
                        completion_tokens,
                    ),
                    daemon=False,
                ).start()
            return result

        ChatCompletionClient.create = _patched_create
        ChatCompletionClient._spctre_model_patched = True
    except Exception:
        pass  # autogen_core.models not available; hook best-effort.


_spctre_install_autogen_hook()
_spctre_install_autogen_model_hook()
