# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.

import json
import os
import threading
import time
import urllib.request
import uuid

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)


def _spctre_emit(action, status, reason, latency_ms=0):
    if not _SPCTRE_KEY:
        return
    payload = {
        "decisionId": f"azure-ai-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": "AZURE_AI", "adapter": "spctre-azure-ai-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": "azure-ai",
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": [f"azure-ai.{action}"]
        if _SPCTRE_POLICY_CONTEXT
        else ["gateway.provenance-gap"],
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "azure-ai-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "azure-ai-hook",
        "ingestMode": "gateway",
        "rawEvidence": {
            "_source": "gateway",
            "_gateway_provider": "azure-ai-hook",
            "_framework": "azure-ai",
        },
    }
    try:
        req = urllib.request.Request(
            f"{_SPCTRE_URL}/api/v1/evidence",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {_SPCTRE_KEY}",
                "x-spctre-source": "gateway",
            },
            method="POST",
        )
        urllib.request.urlopen(req, timeout=3)
    except Exception:
        pass


def _patch_method(cls, method_name, action):
    original = getattr(cls, method_name, None)
    if original is None or getattr(original, "_spctre_patched", False):
        return

    def patched(self, *args, **kwargs):
        start = time.monotonic()
        try:
            result = original(self, *args, **kwargs)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    action,
                    "ALLOW",
                    f"Azure AI {action} completed.",
                    int((time.monotonic() - start) * 1000),
                ),
                daemon=False,
            ).start()
            return result
        except Exception as exc:
            threading.Thread(
                target=_spctre_emit,
                args=(
                    action,
                    "DENY",
                    f"Azure AI {action} raised {type(exc).__name__}: {exc}",
                    int((time.monotonic() - start) * 1000),
                ),
                daemon=False,
            ).start()
            raise

    patched._spctre_patched = True
    setattr(cls, method_name, patched)


def _spctre_patch_azure_openai():
    try:
        from openai.resources.chat.completions import Completions

        _patch_method(Completions, "create", "chat.completions.create")
    except Exception:
        pass


_spctre_patch_azure_openai()
