# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.

import json
import os
import threading
import time
import urllib.request
import uuid

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__"))


def _spctre_emit(action, status, reason, latency_ms=0):
    if not _SPCTRE_KEY:
        return
    payload = {
        "decisionId": f"bedrock-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": "AWS_BEDROCK", "adapter": "spctre-bedrock-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": "bedrock",
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": [f"bedrock.{action}"] if _SPCTRE_POLICY_CONTEXT else ["gateway.provenance-gap"],
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "bedrock-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "bedrock-hook",
        "ingestMode": "gateway",
        "rawEvidence": {"_source": "gateway", "_gateway_provider": "bedrock-hook", "_framework": "bedrock"},
    }
    try:
        req = urllib.request.Request(
            f"{_SPCTRE_URL}/api/evidence",
            data=json.dumps(payload).encode(),
            headers={"Content-Type": "application/json", "Authorization": f"Bearer {_SPCTRE_KEY}", "x-spctre-source": "gateway"},
            method="POST",
        )
        urllib.request.urlopen(req, timeout=3)
    except Exception:
        pass


def _spctre_patch_boto3():
    try:
        import botocore.client
    except Exception:
        return
    original = getattr(botocore.client.BaseClient, "_make_api_call", None)
    if original is None or getattr(botocore.client.BaseClient, "_spctre_patched", False):
        return

    def patched(self, operation_name, api_params):
        service_name = getattr(getattr(self, "meta", None), "service_model", None)
        service_id = getattr(service_name, "service_id", "")
        is_bedrock = "bedrock" in str(service_id).lower()
        start = time.monotonic()
        try:
            result = original(self, operation_name, api_params)
            if is_bedrock and operation_name in ("InvokeModel", "Converse", "ConverseStream"):
                threading.Thread(target=_spctre_emit, args=(operation_name.lower(), "ALLOW", f"Bedrock {operation_name} completed.", int((time.monotonic() - start) * 1000)), daemon=False).start()
            return result
        except Exception as exc:
            if is_bedrock:
                threading.Thread(target=_spctre_emit, args=(operation_name.lower(), "DENY", f"Bedrock {operation_name} raised {type(exc).__name__}: {exc}", int((time.monotonic() - start) * 1000)), daemon=False).start()
            raise

    botocore.client.BaseClient._make_api_call = patched
    botocore.client.BaseClient._spctre_patched = True


_spctre_patch_boto3()
