# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.
#
# This adapter patches ClaudeAgentOptions so every Python Claude Agent SDK
# session receives native PreToolUse, PostToolUse, and PostToolUseFailure hooks.

import asyncio
import importlib
import inspect
import json
import os
import threading
import time
import urllib.request
import uuid

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_GATEWAY_URL = os.environ.get("SPCTRE_GATEWAY_URL", _SPCTRE_URL).rstrip("/")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)
_SPCTRE_TOOL_STARTS = {}
_SPCTRE_MODE = os.environ.get("SPCTRE_CLAUDE_AGENT_SDK_MODE", "observe").lower()
_SPCTRE_OUTAGE_POLICY = os.environ.get("SPCTRE_GATEWAY_OUTAGE_POLICY", "fail-closed").lower()
_SPCTRE_SESSION_ID = os.environ.get("SPCTRE_SESSION_ID") or f"claude-agent-sdk-{os.getpid()}"


def _spctre_action(name):
    return str(name or "unknown_tool").lower().replace(" ", "_").replace("-", "_")


def _spctre_session_id(context=None):
    """Prefer the SDK run/session identity; preserve a stable process fallback."""
    for key in ("session_id", "sessionId", "conversation_id", "conversationId", "run_id", "runId"):
        value = context.get(key) if isinstance(context, dict) else getattr(context, key, None)
        if value:
            return str(value)
    return _SPCTRE_SESSION_ID


def _spctre_emit(action, status, reason, latency_ms=0):
    if not _SPCTRE_KEY:
        return
    has_context = bool(_SPCTRE_POLICY_CONTEXT and _SPCTRE_POLICY_CONTEXT[0].get("artifactHash"))
    payload = {
        "decisionId": f"claude-agent-sdk-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": "CUSTOM", "adapter": "spctre-claude-agent-sdk-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": "claude-agent-sdk",
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": ["system.governance_active"]
        if action == "governance_active"
        else ([f"claude-agent-sdk.tool.{action}"] if has_context else ["gateway.provenance-gap"]),
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "claude-agent-sdk-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "claude-agent-sdk-hook",
        "ingestMode": "gateway",
        "rawEvidence": {
            "_source": "gateway",
            "_gateway_provider": "claude-agent-sdk-hook",
            "_framework": "claude-agent-sdk",
        },
    }
    try:
        request = urllib.request.Request(
            f"{_SPCTRE_URL}/api/v1/evidence",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {_SPCTRE_KEY}",
                "x-spctre-source": "gateway",
            },
            method="POST",
        )
        urllib.request.urlopen(request, timeout=3)
    except Exception:
        pass


def _spctre_emit_async(*args):
    threading.Thread(target=_spctre_emit, args=args, daemon=False).start()


def _spctre_gateway_decide(tool_name, tool_input, tool_use_id, context=None):
    if not _SPCTRE_KEY:
        raise RuntimeError("SPCTRE_API_TOKEN is required for Claude Agent SDK enforcement.")
    payload = {
        "decisionId": tool_use_id or f"claude-agent-sdk-{uuid.uuid4()}",
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "claude-agent-sdk-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "connector": "claude-agent-sdk",
        "agentId": _SPCTRE_AGENT,
        "sessionId": _spctre_session_id(context),
        "action": _spctre_action(tool_name),
        "toolIntent": str(tool_name or "unknown_tool"),
        "toolParameters": tool_input if isinstance(tool_input, dict) else {},
    }
    request = urllib.request.Request(
        f"{_SPCTRE_GATEWAY_URL}/api/v1/gateway/decide",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {_SPCTRE_KEY}"},
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=3) as response:
        body = json.loads(response.read().decode() or "{}")
    decision = body.get("decision") if isinstance(body, dict) else {}
    return str(decision.get("outcome") or "ABORT").upper(), str(
        decision.get("reason") or "Spctre gateway did not provide a reason."
    )


async def _spctre_pre_tool_use(input_data, tool_use_id, context):
    _SPCTRE_TOOL_STARTS[tool_use_id or str(uuid.uuid4())] = time.monotonic()
    if _SPCTRE_MODE != "enforce":
        return {}
    tool_name = input_data.get("tool_name") if isinstance(input_data, dict) else None
    tool_input = input_data.get("tool_input") if isinstance(input_data, dict) else {}
    try:
        outcome, reason = await asyncio.to_thread(
            _spctre_gateway_decide, tool_name, tool_input, tool_use_id, context
        )
    except Exception as exc:
        if _SPCTRE_OUTAGE_POLICY == "fail-open":
            _spctre_emit_async(
                _spctre_action(tool_name),
                "WARN",
                f"Gateway unavailable; fail-open allowed execution ({type(exc).__name__}).",
            )
            return {}
        outcome, reason = (
            "ABORT",
            f"Spctre gateway unavailable; fail-closed ({type(exc).__name__}).",
        )

    if outcome == "PROCEED":
        return {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "allow",
                "permissionDecisionReason": reason,
            }
        }
    if outcome == "ESCALATE":
        _spctre_emit_async(_spctre_action(tool_name), "ESCALATE", reason)
        return {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "ask",
                "permissionDecisionReason": reason,
            }
        }
    _spctre_emit_async(_spctre_action(tool_name), "DENY", reason)
    return {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }
    return {}


async def _spctre_post_tool_use(input_data, tool_use_id, context):
    key = tool_use_id or ""
    start = _SPCTRE_TOOL_STARTS.pop(key, time.monotonic())
    tool_name = input_data.get("tool_name") if isinstance(input_data, dict) else None
    _spctre_emit_async(
        _spctre_action(tool_name),
        "ALLOW",
        f"Tool {tool_name} completed.",
        int((time.monotonic() - start) * 1000),
    )
    return {}


async def _spctre_post_tool_use_failure(input_data, tool_use_id, context):
    key = tool_use_id or ""
    start = _SPCTRE_TOOL_STARTS.pop(key, time.monotonic())
    tool_name = input_data.get("tool_name") if isinstance(input_data, dict) else None
    _spctre_emit_async(
        _spctre_action(tool_name),
        "DENY",
        f"Tool {tool_name} failed.",
        int((time.monotonic() - start) * 1000),
    )
    return {}


def _spctre_install_claude_agent_sdk_hooks():
    try:
        module = importlib.import_module("claude_agent_sdk")
        Options = getattr(module, "ClaudeAgentOptions", None)
        HookMatcher = getattr(module, "HookMatcher", None)
        if Options is None or HookMatcher is None or getattr(Options, "_spctre_patched", False):
            return
        original_init = getattr(Options, "__init__", None)
        if not callable(original_init):
            return
        signature = inspect.signature(original_init)

        def _patched_init(self, *args, **kwargs):
            bound = signature.bind_partial(self, *args, **kwargs)
            hooks = dict(bound.arguments.get("hooks") or {})
            hooks["PreToolUse"] = list(hooks.get("PreToolUse") or []) + [
                HookMatcher(matcher=None, hooks=[_spctre_pre_tool_use])
            ]
            hooks["PostToolUse"] = list(hooks.get("PostToolUse") or []) + [
                HookMatcher(matcher=None, hooks=[_spctre_post_tool_use])
            ]
            hooks["PostToolUseFailure"] = list(hooks.get("PostToolUseFailure") or []) + [
                HookMatcher(matcher=None, hooks=[_spctre_post_tool_use_failure])
            ]
            bound.arguments["hooks"] = hooks
            return original_init(*bound.args, **bound.kwargs)

        Options.__init__ = _patched_init
        Options._spctre_patched = True
        _spctre_emit_async(
            "governance_active", "ALLOW", "Claude Agent SDK native governance hooks installed."
        )
    except Exception:
        pass


_spctre_install_claude_agent_sdk_hooks()
