# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.
#
# Use the generated wrapper to enable zero-change CrewAI governance:
#   .spctre/spctre-python python your_agent.py

import hashlib
import importlib
import inspect
import json
import os
import threading
import time
import urllib.request
import uuid

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_WORKSPACE = os.environ.get("SPCTRE_WORKSPACE", "__SPCTRE_WORKSPACE_ID__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)


def _spctre_argument_hash(args, kwargs):
    try:
        encoded = json.dumps(
            {"args": repr(args), "kwargs": repr(kwargs)},
            sort_keys=True,
            default=str,
        ).encode()
        return "sha256:" + hashlib.sha256(encoded).hexdigest()
    except Exception:
        return None


def _spctre_emit(
    connector,
    action,
    status,
    reason,
    latency_ms=0,
    prompt_tokens=None,
    completion_tokens=None,
    argument_hash=None,
    error_type=None,
):
    if not _SPCTRE_KEY:
        return
    if action == "governance_active":
        policy_refs = ["system.governance_active"]
    else:
        policy_refs = (
            _SPCTRE_POLICY_CONTEXT[0]["artifactHash"]
            and [f"crewai.tool.{action}"]
            or ["gateway.provenance-gap"]
        )
    payload = {
        "decisionId": f"crewai-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": "CREWAI", "adapter": "spctre-crewai-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": connector,
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": policy_refs,
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "crewai-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "crewai-hook",
        "ingestMode": "gateway",
        "rawEvidence": {
            "_source": "gateway",
            "_gateway_provider": "crewai-hook",
            "_framework": "crewai",
        },
    }
    if argument_hash is not None:
        payload["rawEvidence"]["argumentHash"] = argument_hash
    if error_type is not None:
        payload["rawEvidence"]["errorType"] = error_type
    if prompt_tokens is not None:
        payload["promptTokens"] = prompt_tokens
        payload["rawEvidence"]["promptTokens"] = prompt_tokens
    if completion_tokens is not None:
        payload["completionTokens"] = completion_tokens
        payload["rawEvidence"]["completionTokens"] = completion_tokens
    if prompt_tokens is not None and completion_tokens is not None:
        payload["totalTokens"] = prompt_tokens + completion_tokens
        payload["rawEvidence"]["totalTokens"] = prompt_tokens + completion_tokens
    try:
        req = urllib.request.Request(
            f"{_SPCTRE_URL}/api/v1/evidence",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {_SPCTRE_KEY}",
                "x-spctre-source": "gateway",
            },
            method="POST",
        )
        urllib.request.urlopen(req, timeout=3)
    except Exception:
        pass  # Evidence emission is non-fatal; agent continues regardless.


def _extract_crewai_usage(response):
    """Extract token counts from a CrewAI LLM response (ChatCompletion or similar)."""
    try:
        usage = getattr(response, "usage", None)
        if usage is not None:
            if hasattr(usage, "prompt_tokens"):
                return usage.prompt_tokens, usage.completion_tokens
            if isinstance(usage, dict):
                return usage.get("prompt_tokens"), usage.get("completion_tokens")
        tu = getattr(response, "token_usage", None)
        if tu and isinstance(tu, dict):
            return tu.get("prompt_tokens"), tu.get("completion_tokens")
    except Exception:
        pass
    return None, None


def _spctre_install_crewai_hook():
    try:
        module = importlib.import_module("crewai.tools")
    except Exception:
        return  # crewai not installed; hook inactive.

    BaseTool = getattr(module, "BaseTool", None)
    if BaseTool is None:
        return  # API shape not recognized; hook inactive.

    if getattr(BaseTool, "_spctre_patched", False):
        return  # Already patched (e.g. from a nested import).

    _original_run = getattr(BaseTool, "_run", None)
    _original_arun = getattr(BaseTool, "_arun", None)
    if not callable(_original_run) and not callable(_original_arun):
        return  # API shape not recognized; hook inactive.

    def _tool_action(self):
        tool_name = getattr(self, "name", None) or type(self).__name__
        return tool_name, tool_name.lower().replace(" ", "_").replace("-", "_")

    def _patched_run(self, *args, **kwargs):
        tool_name, action = _tool_action(self)
        argument_hash = _spctre_argument_hash(args, kwargs)
        start = time.monotonic()
        try:
            result = _original_run(self, *args, **kwargs)
            latency_ms = int((time.monotonic() - start) * 1000)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "crewai",
                    action,
                    "ALLOW",
                    f"Tool {tool_name} executed successfully.",
                    latency_ms,
                    None,
                    None,
                    argument_hash,
                ),
                daemon=False,
            ).start()
            return result
        except Exception as exc:
            latency_ms = int((time.monotonic() - start) * 1000)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "crewai",
                    action,
                    "DENY",
                    f"Tool {tool_name} raised {type(exc).__name__}: {exc}",
                    latency_ms,
                    None,
                    None,
                    argument_hash,
                    type(exc).__name__,
                ),
                daemon=False,
            ).start()
            raise

    async def _patched_arun(self, *args, **kwargs):
        tool_name, action = _tool_action(self)
        argument_hash = _spctre_argument_hash(args, kwargs)
        start = time.monotonic()
        try:
            result = _original_arun(self, *args, **kwargs)
            if inspect.isawaitable(result):
                result = await result
            latency_ms = int((time.monotonic() - start) * 1000)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "crewai",
                    action,
                    "ALLOW",
                    f"Async tool {tool_name} executed successfully.",
                    latency_ms,
                    None,
                    None,
                    argument_hash,
                ),
                daemon=False,
            ).start()
            return result
        except Exception as exc:
            latency_ms = int((time.monotonic() - start) * 1000)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "crewai",
                    action,
                    "DENY",
                    f"Async tool {tool_name} raised {type(exc).__name__}: {exc}",
                    latency_ms,
                    None,
                    None,
                    argument_hash,
                    type(exc).__name__,
                ),
                daemon=False,
            ).start()
            raise

    if callable(_original_run):
        BaseTool._run = _patched_run
    if callable(_original_arun):
        BaseTool._arun = _patched_arun
    BaseTool._spctre_patched = True
    threading.Thread(
        target=_spctre_emit,
        args=(
            "crewai",
            "governance_active",
            "ALLOW",
            "CrewAI governance adapter patched and active.",
            0,
        ),
        daemon=False,
    ).start()


def _spctre_install_crewai_llm_hook():
    """Patch crewai.LLM.call to capture token usage from the LLM response."""
    try:
        module = importlib.import_module("crewai.llm")
        LLM = getattr(module, "LLM", None)
        if LLM is None:
            return

        if getattr(LLM, "_spctre_llm_patched", False):
            return

        _original_call = getattr(LLM, "call", None)
        if not callable(_original_call):
            return

        def _patched_call(self, *args, **kwargs):
            start = time.monotonic()
            result = _original_call(self, *args, **kwargs)
            latency_ms = int((time.monotonic() - start) * 1000)
            prompt_tokens, completion_tokens = _extract_crewai_usage(result)
            if prompt_tokens is not None or completion_tokens is not None:
                threading.Thread(
                    target=_spctre_emit,
                    args=(
                        "crewai",
                        "llm_call",
                        "ALLOW",
                        "CrewAI LLM call completed.",
                        latency_ms,
                        prompt_tokens,
                        completion_tokens,
                    ),
                    daemon=False,
                ).start()
            return result

        LLM.call = _patched_call
        LLM._spctre_llm_patched = True
    except Exception:
        pass  # crewai.LLM not available in this version; hook best-effort.


_spctre_install_crewai_hook()
_spctre_install_crewai_llm_hook()
