# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.
#
# Use the generated wrapper to enable zero-change Google ADK governance:
#   .spctre/spctre-python python your_agent.py

import importlib
import json
import os
import threading
import time
import urllib.request
import uuid

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_WORKSPACE = os.environ.get("SPCTRE_WORKSPACE", "__SPCTRE_WORKSPACE_ID__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)


def _spctre_emit(
    connector, action, status, reason, latency_ms=0, prompt_tokens=None, completion_tokens=None
):
    if not _SPCTRE_KEY:
        return
    has_context = bool(_SPCTRE_POLICY_CONTEXT and _SPCTRE_POLICY_CONTEXT[0].get("artifactHash"))
    policy_refs = (
        ["system.governance_active"]
        if action == "governance_active"
        else ([f"google-adk.tool.{action}"] if has_context else ["gateway.provenance-gap"])
    )
    payload = {
        "decisionId": f"google-adk-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": "GOOGLE_ADK", "adapter": "spctre-google-adk-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": "google-adk",
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": policy_refs,
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "google-adk-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "google-adk-hook",
        "ingestMode": "gateway",
        "rawEvidence": {
            "_source": "gateway",
            "_gateway_provider": "google-adk-hook",
            "_framework": "google-adk",
        },
    }
    if prompt_tokens is not None:
        payload["promptTokens"] = prompt_tokens
        payload["rawEvidence"]["promptTokens"] = prompt_tokens
    if completion_tokens is not None:
        payload["completionTokens"] = completion_tokens
        payload["rawEvidence"]["completionTokens"] = completion_tokens
    if prompt_tokens is not None and completion_tokens is not None:
        payload["totalTokens"] = prompt_tokens + completion_tokens
        payload["rawEvidence"]["totalTokens"] = prompt_tokens + completion_tokens
    try:
        req = urllib.request.Request(
            f"{_SPCTRE_URL}/api/v1/evidence",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {_SPCTRE_KEY}",
                "x-spctre-source": "gateway",
            },
            method="POST",
        )
        urllib.request.urlopen(req, timeout=3)
    except Exception:
        pass  # Evidence emission is non-fatal; agent continues regardless.


def _extract_google_adk_usage(response):
    """Extract token counts from a Google ADK LlmResponse or GenerateContentResponse."""
    try:
        # LlmResponse.usage_metadata (google-adk >= 0.3)
        um = getattr(response, "usage_metadata", None)
        if um is not None:
            prompt = getattr(um, "prompt_token_count", None)
            completion = getattr(um, "candidates_token_count", None)
            if prompt is not None or completion is not None:
                return prompt, completion
        # Raw GenerateContentResponse.usage_metadata dict
        if isinstance(um, dict):
            return um.get("promptTokenCount"), um.get("candidatesTokenCount")
    except Exception:
        pass
    return None, None


def _spctre_install_google_adk_hook():
    BaseTool = None
    # Try the stable public import path first, then the internal module path.
    for module_name in ("google.adk.tools", "google.adk.tools.base_tool"):
        try:
            module = importlib.import_module(module_name)
        except Exception:
            continue
        BaseTool = getattr(module, "BaseTool", None)
        if BaseTool is not None:
            break
    if BaseTool is None:
        return  # google-adk not installed; hook inactive.

    if getattr(BaseTool, "_spctre_patched", False):
        return

    # run_async is the primary async execution method in Google ADK BaseTool.
    _original_run_async = getattr(BaseTool, "run_async", None)
    if _original_run_async is None:
        return  # API shape not recognized; hook inactive.

    async def _patched_run_async(self, *, args, tool_context):
        tool_name = getattr(self, "name", None) or type(self).__name__
        action = tool_name.lower().replace(" ", "_").replace("-", "_")
        start = time.monotonic()
        try:
            result = await _original_run_async(self, args=args, tool_context=tool_context)
            latency_ms = int((time.monotonic() - start) * 1000)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "google-adk",
                    action,
                    "ALLOW",
                    f"Tool {tool_name} invoked successfully.",
                    latency_ms,
                ),
                daemon=False,
            ).start()
            return result
        except Exception as exc:
            latency_ms = int((time.monotonic() - start) * 1000)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "google-adk",
                    action,
                    "DENY",
                    f"Tool {tool_name} raised {type(exc).__name__}: {exc}",
                    latency_ms,
                ),
                daemon=False,
            ).start()
            raise

    BaseTool.run_async = _patched_run_async
    BaseTool._spctre_patched = True
    threading.Thread(
        target=_spctre_emit,
        args=(
            "google-adk",
            "governance_active",
            "ALLOW",
            "Google ADK governance adapter patched and active.",
            0,
        ),
        daemon=False,
    ).start()


def _spctre_install_google_adk_llm_hook():
    """Patch BaseLlm.generate_content_async to capture token usage telemetry."""
    try:
        BaseLlm = None
        for module_name in ("google.adk.models", "google.adk.models.base_llm"):
            try:
                module = importlib.import_module(module_name)
                BaseLlm = getattr(module, "BaseLlm", None)
                if BaseLlm is not None:
                    break
            except Exception:
                continue
        if BaseLlm is None:
            return

        if getattr(BaseLlm, "_spctre_llm_patched", False):
            return

        _original_generate = getattr(BaseLlm, "generate_content_async", None)
        if not callable(_original_generate):
            return

        async def _patched_generate(self, *args, **kwargs):
            start = time.monotonic()
            # generate_content_async is an async generator; collect the last response.
            last_response = None
            async for chunk in _original_generate(self, *args, **kwargs):
                last_response = chunk
                yield chunk
            if last_response is not None:
                latency_ms = int((time.monotonic() - start) * 1000)
                prompt_tokens, completion_tokens = _extract_google_adk_usage(last_response)
                if prompt_tokens is not None or completion_tokens is not None:
                    threading.Thread(
                        target=_spctre_emit,
                        args=(
                            "google-adk",
                            "llm_call",
                            "ALLOW",
                            "Google ADK LLM call completed.",
                            latency_ms,
                            prompt_tokens,
                            completion_tokens,
                        ),
                        daemon=False,
                    ).start()

        BaseLlm.generate_content_async = _patched_generate
        BaseLlm._spctre_llm_patched = True
    except Exception:
        pass  # google-adk LLM internals vary; hook best-effort.


_spctre_install_google_adk_hook()
_spctre_install_google_adk_llm_hook()
