# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.
#
# Use the generated wrapper to enable zero-change LangChain/LangGraph governance:
#   .spctre/spctre-python python your_agent.py

import importlib
import json
import os
import threading
import time
import urllib.request
import uuid

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_WORKSPACE = os.environ.get("SPCTRE_WORKSPACE", "__SPCTRE_WORKSPACE_ID__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)

# Detect LangGraph at import time to set the correct runtimeTarget stack.
try:
    _lg = importlib.import_module("langgraph")
    _SPCTRE_STACK = "LANGGRAPH"
    del _lg
except Exception:
    _SPCTRE_STACK = "LANGCHAIN"


def _spctre_emit(
    connector, action, status, reason, latency_ms=0, prompt_tokens=None, completion_tokens=None
):
    if not _SPCTRE_KEY:
        return
    has_context = bool(_SPCTRE_POLICY_CONTEXT and _SPCTRE_POLICY_CONTEXT[0].get("artifactHash"))
    policy_refs = (
        ["system.governance_active"]
        if action == "governance_active"
        else ([f"langchain.tool.{action}"] if has_context else ["gateway.provenance-gap"])
    )
    payload = {
        "decisionId": f"langchain-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": _SPCTRE_STACK, "adapter": "spctre-langchain-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": connector,
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": policy_refs,
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "langchain-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "langchain-hook",
        "ingestMode": "gateway",
        "rawEvidence": {
            "_source": "gateway",
            "_gateway_provider": "langchain-hook",
            "_framework": "langchain",
            "_stack": _SPCTRE_STACK.lower(),
        },
    }
    if prompt_tokens is not None:
        payload["promptTokens"] = prompt_tokens
        payload["rawEvidence"]["promptTokens"] = prompt_tokens
    if completion_tokens is not None:
        payload["completionTokens"] = completion_tokens
        payload["rawEvidence"]["completionTokens"] = completion_tokens
    if prompt_tokens is not None and completion_tokens is not None:
        payload["totalTokens"] = prompt_tokens + completion_tokens
        payload["rawEvidence"]["totalTokens"] = prompt_tokens + completion_tokens
    try:
        req = urllib.request.Request(
            f"{_SPCTRE_URL}/api/v1/evidence",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {_SPCTRE_KEY}",
                "x-spctre-source": "gateway",
            },
            method="POST",
        )
        urllib.request.urlopen(req, timeout=3)
    except Exception:
        pass  # Evidence emission is non-fatal; agent continues regardless.


def _extract_langchain_usage(result):
    """Extract prompt/completion token counts from a LangChain LLMResult or AIMessage."""
    try:
        # LLMResult.generations[0][0].message.usage_metadata (LangChain >= 0.2)
        if hasattr(result, "generations"):
            gen = result.generations
            if gen and gen[0]:
                msg = getattr(gen[0][0], "message", None)
                if msg:
                    usage = getattr(msg, "usage_metadata", None)
                    if usage and isinstance(usage, dict):
                        return usage.get("input_tokens"), usage.get("output_tokens")
        # AIMessage.usage_metadata (when patching invoke directly)
        usage = getattr(result, "usage_metadata", None)
        if usage and isinstance(usage, dict):
            return usage.get("input_tokens"), usage.get("output_tokens")
        # response_metadata.token_usage (older LangChain)
        meta = getattr(result, "response_metadata", None)
        if meta and isinstance(meta, dict):
            tu = meta.get("token_usage") or meta.get("usage")
            if tu and isinstance(tu, dict):
                return tu.get("prompt_tokens"), tu.get("completion_tokens")
    except Exception:
        pass
    return None, None


def _spctre_install_langchain_hook():
    # Prefer langchain_core (LangChain >=0.1); fall back to langchain for older installs.
    BaseTool = None
    for module_name in ("langchain_core.tools", "langchain.tools"):
        try:
            module = importlib.import_module(module_name)
        except Exception:
            continue
        BaseTool = getattr(module, "BaseTool", None)
        if BaseTool is not None:
            break
    if BaseTool is None:
        return  # Neither installed; hook inactive.

    if getattr(BaseTool, "_spctre_patched", False):
        return  # Already patched (e.g. from a nested import).

    _original_invoke = getattr(BaseTool, "invoke", None)
    if not callable(_original_invoke):
        return  # API shape not recognized; hook inactive.

    def _patched_invoke(self, input, config=None, **kwargs):
        tool_name = getattr(self, "name", None) or type(self).__name__
        action = tool_name.lower().replace(" ", "_").replace("-", "_")
        start = time.monotonic()
        try:
            result = _original_invoke(self, input, config, **kwargs)
            latency_ms = int((time.monotonic() - start) * 1000)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "langchain",
                    action,
                    "ALLOW",
                    f"Tool {tool_name} invoked successfully.",
                    latency_ms,
                ),
                daemon=False,
            ).start()
            return result
        except Exception as exc:
            latency_ms = int((time.monotonic() - start) * 1000)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "langchain",
                    action,
                    "DENY",
                    f"Tool {tool_name} raised {type(exc).__name__}: {exc}",
                    latency_ms,
                ),
                daemon=False,
            ).start()
            raise

    BaseTool.invoke = _patched_invoke

    # Async patch for LangGraph agents that drive tool calls through ainvoke.
    _original_ainvoke = getattr(BaseTool, "ainvoke", None)
    if callable(_original_ainvoke):

        async def _patched_ainvoke(self, input, config=None, **kwargs):
            tool_name = getattr(self, "name", None) or type(self).__name__
            action = tool_name.lower().replace(" ", "_").replace("-", "_")
            start = time.monotonic()
            try:
                result = await _original_ainvoke(self, input, config, **kwargs)
                latency_ms = int((time.monotonic() - start) * 1000)
                threading.Thread(
                    target=_spctre_emit,
                    args=(
                        "langchain",
                        action,
                        "ALLOW",
                        f"Tool {tool_name} invoked (async).",
                        latency_ms,
                    ),
                    daemon=False,
                ).start()
                return result
            except Exception as exc:
                latency_ms = int((time.monotonic() - start) * 1000)
                threading.Thread(
                    target=_spctre_emit,
                    args=(
                        "langchain",
                        action,
                        "DENY",
                        f"Tool {tool_name} raised {type(exc).__name__}: {exc}",
                        latency_ms,
                    ),
                    daemon=False,
                ).start()
                raise

        BaseTool.ainvoke = _patched_ainvoke
    BaseTool._spctre_patched = True
    threading.Thread(
        target=_spctre_emit,
        args=(
            "langchain",
            "governance_active",
            "ALLOW",
            "LangChain governance adapter patched and active.",
            0,
        ),
        daemon=False,
    ).start()


def _spctre_install_langchain_llm_hook():
    """Patch BaseChatModel.generate/agenerate to capture token usage telemetry."""
    BaseChatModel = None
    for module_name in ("langchain_core.language_models.chat_models", "langchain.chat_models.base"):
        try:
            module = importlib.import_module(module_name)
            BaseChatModel = getattr(module, "BaseChatModel", None)
            if BaseChatModel is not None:
                break
        except Exception:
            continue
    if BaseChatModel is None:
        return

    if getattr(BaseChatModel, "_spctre_llm_patched", False):
        return

    _original_generate = getattr(BaseChatModel, "_generate", None)
    if callable(_original_generate):

        def _patched_generate(self, messages, stop=None, run_manager=None, **kwargs):
            start = time.monotonic()
            result = _original_generate(self, messages, stop, run_manager, **kwargs)
            latency_ms = int((time.monotonic() - start) * 1000)
            prompt_tokens, completion_tokens = _extract_langchain_usage(result)
            if prompt_tokens is not None or completion_tokens is not None:
                threading.Thread(
                    target=_spctre_emit,
                    args=(
                        "langchain",
                        "llm_call",
                        "ALLOW",
                        "LangChain LLM call completed.",
                        latency_ms,
                        prompt_tokens,
                        completion_tokens,
                    ),
                    daemon=False,
                ).start()
            return result

        BaseChatModel._generate = _patched_generate

    _original_agenerate = getattr(BaseChatModel, "_agenerate", None)
    if callable(_original_agenerate):

        async def _patched_agenerate(self, messages, stop=None, run_manager=None, **kwargs):
            start = time.monotonic()
            result = await _original_agenerate(self, messages, stop, run_manager, **kwargs)
            latency_ms = int((time.monotonic() - start) * 1000)
            prompt_tokens, completion_tokens = _extract_langchain_usage(result)
            if prompt_tokens is not None or completion_tokens is not None:
                threading.Thread(
                    target=_spctre_emit,
                    args=(
                        "langchain",
                        "llm_call",
                        "ALLOW",
                        "LangChain LLM call completed (async).",
                        latency_ms,
                        prompt_tokens,
                        completion_tokens,
                    ),
                    daemon=False,
                ).start()
            return result

        BaseChatModel._agenerate = _patched_agenerate

    BaseChatModel._spctre_llm_patched = True


_spctre_install_langchain_hook()
_spctre_install_langchain_llm_hook()
