# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.
#
# Import sitecustomize and call spctre_record_action(...) from custom runtimes.

import json
import os
import urllib.request
import uuid

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)


def spctre_record_action(
    connector="custom",
    action="action",
    status="ALLOW",
    reason="Custom runtime action recorded.",
    latency_ms=0,
    raw_evidence=None,
):
    if not _SPCTRE_KEY:
        return
    payload = {
        "decisionId": f"custom-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": "CUSTOM", "adapter": "spctre-local-custom-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": connector,
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": [f"{connector}.{action}"]
        if _SPCTRE_POLICY_CONTEXT
        else ["gateway.provenance-gap"],
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "custom-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "local-custom-hook",
        "ingestMode": "gateway",
        "rawEvidence": {
            "_source": "gateway",
            "_gateway_provider": "local-custom-hook",
            "_framework": "local-custom",
            **(raw_evidence or {}),
        },
    }
    req = urllib.request.Request(
        f"{_SPCTRE_URL}/api/evidence",
        data=json.dumps(payload).encode(),
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {_SPCTRE_KEY}",
            "x-spctre-source": "gateway",
        },
        method="POST",
    )
    urllib.request.urlopen(req, timeout=3)
