// Auto-generated by spctre watch --framework notion-worker
// Do not edit manually - re-run 'spctre watch --framework notion-worker' to refresh.
//
// Deploy this Notion Worker via the Notion CLI:
//   notion worker deploy .spctre/notion-worker.js
//
// The Worker wraps each agent tool call with a Spctre governance pre-check
// (evaluate_policy). On ESCALATE, the review item is surfaced via Notion's
// built-in approval loop. After execution, a spctre.gateway.event.v1 payload
// is posted to ingest_gateway_event for evidence capture.

const SPCTRE_URL = process.env.SPCTRE_URL || "__SPCTRE_CONTROL_PLANE_URL__";
const SPCTRE_KEY = process.env.SPCTRE_API_TOKEN || "__SPCTRE_TOKEN__";
const SPCTRE_WORKSPACE = process.env.SPCTRE_WORKSPACE || "__SPCTRE_WORKSPACE_ID__";
const SPCTRE_AGENT = process.env.SPCTRE_AGENT || "__SPCTRE_AGENT_ID__";
const SPCTRE_ENV = process.env.SPCTRE_ENVIRONMENT || "__SPCTRE_ENVIRONMENT__";
const SPCTRE_ARTIFACT_HASH = process.env.SPCTRE_ARTIFACT_HASH || "__SPCTRE_ARTIFACT_HASH__";

/**
 * Posts a governance evidence record to the Spctre control plane.
 * Uses the /api/gateway/ingest/notion endpoint so the record is stored with
 * gateway source badge and provenance_gap indicator in the Evidence ledger.
 */
async function spctreIngestEvent({ agentId, action, status, reason, toolDeclarations = [], latencyMs = 0, executionId, model = "unknown", costUsd }) {
  if (!SPCTRE_KEY) return;
  const payload = {
    id: executionId || `notion-worker-${Date.now()}-${Math.random().toString(36).slice(2)}`,
    agent_id: agentId || SPCTRE_AGENT,
    action,
    model,
    tools: toolDeclarations.map((name) => ({ name })),
    created_at: new Date().toISOString(),
    latency_ms: latencyMs,
    cost_usd: costUsd,
    metadata: { environment: SPCTRE_ENV },
    _spctre_status: status,
    _spctre_reason: reason,
  };
  try {
    const res = await fetch(`${SPCTRE_URL}/api/gateway-ingest/notion`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-spctre-gateway-secret": SPCTRE_KEY,
        "x-spctre-environment": SPCTRE_ENV,
      },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(5000),
    });
    if (!res.ok) {
      console.warn(`[spctre] evidence ingest returned ${res.status}`);
    }
  } catch {
    // Evidence emission is non-fatal; the Worker continues regardless.
  }
}

/**
 * Calls the Spctre evaluate_policy endpoint before allowing tool execution.
 * Returns { decision: "PROCEED" | "ESCALATE" | "ABORT", escalationId? }.
 */
async function spctreEvaluatePolicy({ agentId, connector, action, environment }) {
  if (!SPCTRE_KEY) return { decision: "PROCEED" };
  try {
    const res = await fetch(`${SPCTRE_URL}/api/evaluate`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${SPCTRE_KEY}`,
      },
      body: JSON.stringify({
        agentId: agentId || SPCTRE_AGENT,
        workspaceId: SPCTRE_WORKSPACE,
        environment: environment || SPCTRE_ENV,
        connector,
        action,
        artifactHash: SPCTRE_ARTIFACT_HASH || "notion-worker-unresolved",
      }),
      signal: AbortSignal.timeout(5000),
    });
    if (!res.ok) return { decision: "PROCEED" };
    return await res.json();
  } catch {
    return { decision: "PROCEED" };
  }
}

/**
 * Governs a single agent tool call:
 * 1. Pre-check: evaluate_policy — ABORT stops execution, ESCALATE defers to Notion approval.
 * 2. Execute the provided fn.
 * 3. Post evidence via ingest_gateway_event regardless of outcome.
 *
 * Usage in your Worker handler:
 *
 *   const result = await spctreGoverned({
 *     agentId: event.agentId,
 *     connector: "notion-worker",
 *     action: "my_tool",
 *     notionApprovalLoopUrl: event.approvalLoopUrl,    // from Notion's event envelope
 *     fn: async () => { return await myTool(event.input); },
 *   });
 */
async function spctreGoverned({ agentId, connector, action, notionApprovalLoopUrl, fn, toolDeclarations = [], model, executionId }) {
  const { decision, escalationId } = await spctreEvaluatePolicy({ agentId, connector, action, environment: SPCTRE_ENV });

  if (decision === "ABORT") {
    await spctreIngestEvent({ agentId, action, status: "DENY", reason: "Spctre policy evaluation returned ABORT; execution blocked.", toolDeclarations, executionId, model });
    return { _spctre_blocked: true, reason: "Governance policy blocked this action. Review the Spctre escalation queue." };
  }

  if (decision === "ESCALATE") {
    await spctreIngestEvent({ agentId, action, status: "WARN", reason: `Spctre policy evaluation returned ESCALATE (escalationId: ${escalationId}); surfaced via Notion approval loop.`, toolDeclarations, executionId, model });
    // Surface the pending review via Notion's built-in approval loop URL when available.
    // The caller should check _spctre_escalated and present notionApprovalLoopUrl to the reviewer.
    return {
      _spctre_escalated: true,
      escalationId,
      approvalLoopUrl: notionApprovalLoopUrl,
      reason: "This action requires human approval. A review request has been submitted.",
    };
  }

  // PROCEED — execute and emit evidence.
  const start = Date.now();
  try {
    const result = await fn();
    const latencyMs = Date.now() - start;
    await spctreIngestEvent({ agentId, action, status: "ALLOW", reason: `Notion Worker executed ${action} successfully.`, toolDeclarations, latencyMs, executionId, model });
    return result;
  } catch (err) {
    const latencyMs = Date.now() - start;
    await spctreIngestEvent({ agentId, action, status: "DENY", reason: `Notion Worker tool ${action} raised ${err?.constructor?.name ?? "Error"}: ${err?.message ?? err}`, toolDeclarations, latencyMs, executionId, model });
    throw err;
  }
}

/**
 * Main Worker handler. Notion Workers export a default handler function.
 *
 * Replace the example tool call below with your actual agent logic:
 *
 *   const result = await spctreGoverned({
 *     agentId: event.agent_id,
 *     connector: "notion-worker",
 *     action: "your_tool_name",
 *     notionApprovalLoopUrl: event.approval_loop_url,
 *     toolDeclarations: ["your_tool_name"],
 *     fn: async () => myTool(event.input),
 *   });
 */
export default async function handler(event) {
  const agentId = event.agent_id || SPCTRE_AGENT;
  const executionId = event.execution_id || event.id;

  // Example: govern a single tool call. Replace this block with your logic.
  const result = await spctreGoverned({
    agentId,
    connector: "notion-worker",
    action: event.action || "worker.execute",
    notionApprovalLoopUrl: event.approval_loop_url,
    toolDeclarations: Array.isArray(event.tools) ? event.tools.map((t) => (typeof t === "string" ? t : t.name)) : [],
    executionId,
    fn: async () => {
      // Replace with your agent tool logic. This placeholder echoes the input back.
      return { ok: true, input: event.input };
    },
  });

  return result;
}
