# Auto-generated by spctre watch --framework omnigent
# Do not edit manually - re-run 'spctre watch --framework omnigent' to refresh.
#
# Register this module in server_config.yaml:
#
# policy_modules:
#   - spctre_policy
#
# policies:
#   spctre_guard:
#     type: function
#     handler: spctre_policy.spctre_policy
#     factory_params:
#       decision_endpoint: "/api/v1/evaluate"
#       outage_policy: "fail-open"
#
# Then launch with:
#   PYTHONPATH=./.spctre:$PYTHONPATH SPCTRE_API_TOKEN=... omnigent server --config server_config.yaml

import asyncio
import json
import os
import re
import sys
import threading
import time
import urllib.request
import uuid
from typing import Any

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__").rstrip("/")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN")
_SPCTRE_TENANT = os.environ.get("SPCTRE_TENANT", "__SPCTRE_TENANT_ID__")
_SPCTRE_WORKSPACE = os.environ.get("SPCTRE_WORKSPACE", "__SPCTRE_WORKSPACE_ID__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)

try:
    from omnigent.policies.schema import PolicyCallable, PolicyEvent, PolicyResponse
except ImportError:
    PolicyEvent = dict
    PolicyResponse = dict
    PolicyCallable = Any

BASH_CONNECTOR_PATTERNS = [
    (re.compile(r"\bstripe\b", re.IGNORECASE), "stripe", ["billing"]),
    (re.compile(r"github\.com\b|(?:^|\s|/)gh\s", re.IGNORECASE), "github", ["vcs"]),
    (re.compile(r"gitlab\.com\b", re.IGNORECASE), "gitlab", ["vcs"]),
    (re.compile(r"\bslack\.com\b|\bslack\s", re.IGNORECASE), "slack", ["messaging"]),
    (re.compile(r"\btwilio\b", re.IGNORECASE), "twilio", ["messaging"]),
    (re.compile(r"\bsendgrid\b", re.IGNORECASE), "sendgrid", ["email"]),
    (re.compile(r"\bsalesforce\b", re.IGNORECASE), "salesforce", ["crm"]),
    (re.compile(r"\bzendesk\b", re.IGNORECASE), "zendesk", ["support"]),
    (re.compile(r"\bpsql\b|\bpg_dump\b|\bpg_restore\b", re.IGNORECASE), "postgres", ["database"]),
    (re.compile(r"\bmysql\b|\bmysqldump\b", re.IGNORECASE), "mysql", ["database"]),
    (re.compile(r"\bmongo\b", re.IGNORECASE), "mongodb", ["database"]),
    (re.compile(r"(?:^|\s)aws\s|awscli\b|s3://", re.IGNORECASE), "aws", ["infrastructure"]),
    (re.compile(r"(?:^|\s)gcloud\s", re.IGNORECASE), "gcp", ["infrastructure"]),
    (re.compile(r"(?:^|\s)kubectl\s", re.IGNORECASE), "kubernetes", ["infrastructure"]),
    (re.compile(r"\bterraform\b", re.IGNORECASE), "terraform", ["infrastructure"]),
    (re.compile(r"\bpulumi\b", re.IGNORECASE), "pulumi", ["infrastructure"]),
    (re.compile(r"(?:^|\s)az\s+[a-z]", re.IGNORECASE), "azure", ["infrastructure"]),
]

SHELL_TOOL_NAMES = {
    "Bash",
    "bash",
    "Shell",
    "shell",
    "terminal",
    "exec_command",
    "shell_command",
    "sys_os_shell",
    "developer__shell",
}

WEB_FETCH_TOOL_NAMES = {"WebFetch", "web_fetch", "web.fetch", "fetch"}
WEB_SEARCH_TOOL_NAMES = {"WebSearch", "web_search", "web.search", "search"}


def _tool_suffix(tool_name: str) -> str:
    suffix = tool_name
    for separator in ("__", "."):
        if separator in suffix:
            suffix = suffix.split(separator)[-1]
    return suffix


def _get(obj: Any, key: str, default: Any = None) -> Any:
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


def _as_dict(value: Any) -> dict:
    if isinstance(value, dict):
        return value
    if value is None:
        return {}
    model_dump = getattr(value, "model_dump", None)
    if callable(model_dump):
        try:
            dumped = model_dump()
            return dumped if isinstance(dumped, dict) else {}
        except Exception:
            return {}
    if hasattr(value, "__dict__"):
        return dict(value.__dict__)
    return {}


def _resolve_governed_action(tool_name: str, tool_input: dict) -> tuple[str, str, list[str]] | None:
    if not tool_name:
        return None

    if tool_name.startswith("mcp__"):
        parts = tool_name.split("__")
        if len(parts) >= 3:
            return parts[1], ".".join(parts[2:]), ["external"]

    tool_suffix = _tool_suffix(tool_name)

    if (
        tool_name in WEB_FETCH_TOOL_NAMES
        or tool_name in WEB_SEARCH_TOOL_NAMES
        or tool_suffix in WEB_FETCH_TOOL_NAMES
        or tool_suffix in WEB_SEARCH_TOOL_NAMES
    ):
        is_search = tool_name in WEB_SEARCH_TOOL_NAMES or tool_suffix in WEB_SEARCH_TOOL_NAMES
        raw = tool_input.get("query") if is_search else tool_input.get("url")
        if not raw or not isinstance(raw, str):
            return "web", "search" if is_search else "fetch", ["external"]
        try:
            from urllib.parse import urlparse

            url = raw if raw.startswith("http") else f"https://{raw}"
            hostname = urlparse(url).hostname or "web"
            return (
                hostname[4:] if hostname.startswith("www.") else hostname,
                "search" if is_search else "fetch",
                ["external"],
            )
        except Exception:
            return "web", "search" if is_search else "fetch", ["external"]

    if tool_name in SHELL_TOOL_NAMES or tool_suffix in SHELL_TOOL_NAMES:
        cmd = tool_input.get("command") or tool_input.get("cmd") or ""
        if not isinstance(cmd, str):
            cmd = ""
        for pattern, connector, domains in BASH_CONNECTOR_PATTERNS:
            if pattern.search(cmd):
                return connector, "execute", domains
        return "shell", "execute", ["os"]

    if tool_name.startswith("sys_os_"):
        return "os", tool_name[7:], ["os"]

    for separator in (".", "__"):
        if separator in tool_name:
            parts = tool_name.split(separator)
            if len(parts) >= 2:
                return parts[0], ".".join(parts[1:]), ["external"]

    return None


def _normalize_event(event: PolicyEvent) -> tuple[str, dict, tuple[str, str, list[str]] | None]:
    event_type = _get(event, "type")
    data = _as_dict(_get(event, "data"))
    tool_name = _get(event, "target") or data.get("name") or data.get("tool") or ""
    tool_input = _as_dict(data.get("arguments") or data.get("input") or data.get("tool_input"))

    if event_type != "tool_call":
        return tool_name, tool_input, None
    return tool_name, tool_input, _resolve_governed_action(str(tool_name), tool_input)


def _http_json(path_or_url: str, payload: dict, timeout_seconds: float) -> dict:
    url = path_or_url if path_or_url.startswith("http") else f"{_SPCTRE_URL}{path_or_url}"
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode(),
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {_SPCTRE_KEY}",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout_seconds) as response:
        body = response.read().decode("utf-8")
        return json.loads(body) if body else {}


def _spctre_evaluate(
    connector: str,
    action: str,
    domains: list[str],
    tool_input: dict,
    decision_endpoint: str,
    timeout_seconds: float,
) -> dict:
    if not _SPCTRE_KEY:
        raise RuntimeError("SPCTRE_API_TOKEN is required for Omnigent policy evaluation.")

    return _http_json(
        decision_endpoint,
        {
            "agentId": _SPCTRE_AGENT,
            "workspaceId": _SPCTRE_WORKSPACE,
            "environment": _SPCTRE_ENV,
            "connector": connector,
            "action": action,
            "domains": domains,
            "artifactHash": _SPCTRE_ARTIFACT_HASH or "omnigent-unresolved",
            "toolIntent": tool_input.get("toolIntent") or tool_input.get("tool_intent"),
            "planSummary": tool_input.get("planSummary") or tool_input.get("plan_summary"),
            "toolParameters": tool_input,
        },
        timeout_seconds,
    )


def _spctre_emit(
    connector: str,
    action: str,
    status: str,
    reason: str,
    decision_id: str,
    policy_refs: list[str],
    latency_ms: int,
    raw_evidence: dict,
    timeout_seconds: float,
    warn_on_failure: bool = False,
) -> None:
    if not _SPCTRE_KEY:
        if warn_on_failure:
            print(
                "Warning: SPCTRE_API_TOKEN is not set; Omnigent governance_active evidence was not emitted.",
                file=sys.stderr,
            )
        return
    payload = {
        "decisionId": decision_id,
        "tenantId": _SPCTRE_TENANT,
        "workspaceId": _SPCTRE_WORKSPACE,
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": "OMNIGENT", "adapter": "spctre-omnigent-policy"},
        "agentId": _SPCTRE_AGENT,
        "connector": connector,
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": policy_refs if policy_refs else ["gateway.provenance-gap"],
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "omnigent-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "omnigent-policy",
        "ingestMode": "gateway",
        "rawEvidence": raw_evidence,
    }
    try:
        _http_json("/api/v1/evidence", payload, timeout_seconds)
    except Exception as exc:
        if warn_on_failure:
            print(
                f"Warning: Omnigent governance_active evidence emit failed ({type(exc).__name__}: {exc}).",
                file=sys.stderr,
            )


def _spctre_emit_background(*args: Any, **kwargs: Any) -> None:
    thread = threading.Thread(target=_spctre_emit, args=args, kwargs=kwargs, daemon=True)
    thread.start()


def _extract_result(response: dict) -> tuple[str, str, list[str], str]:
    result = response.get("result") if isinstance(response, dict) else {}
    if not isinstance(result, dict):
        result = response
    status = str(result.get("status") or result.get("decision") or "ALLOW").upper()
    if status in ("ESCALATED", "REVIEW"):
        status = "ESCALATE"
    if status not in ("ALLOW", "DENY", "WARN", "ESCALATE"):
        status = "ALLOW"
    reason = result.get("reason") or response.get("reason") or f"Spctre returned {status}."
    refs = result.get("matchedRefs") or result.get("policyRefs") or response.get("policyRefs") or []
    if not isinstance(refs, list):
        refs = [str(refs)]
    decision_id = (
        response.get("decisionId") or result.get("decisionId") or f"omnigent-{uuid.uuid4()}"
    )
    return status, str(reason), [str(ref) for ref in refs], str(decision_id)


def spctre_policy(
    decision_endpoint: str = "/api/v1/evaluate",
    outage_policy: str = "fail-open",
    timeout_seconds: float = 5.0,
    emit_evidence: bool = True,
) -> PolicyCallable:
    """Factory: create an Omnigent policy callable backed by Spctre decisions."""
    if emit_evidence:
        _spctre_emit_background(
            "omnigent",
            "governance_active",
            "ALLOW",
            "Omnigent Spctre policy factory activated.",
            "active-" + str(uuid.uuid4()),
            ["system.governance_active"],
            0,
            {"_source": "startup", "_framework": "omnigent"},
            min(timeout_seconds, 2.0),
            warn_on_failure=True,
        )

    async def evaluate(event: PolicyEvent) -> PolicyResponse | None:
        tool_name, tool_input, governed = _normalize_event(event)
        if governed is None:
            return None

        connector, action, domains = governed
        started = time.time()
        raw_evidence = {
            "_source": "gateway",
            "_gateway_provider": "omnigent-policy",
            "_framework": "omnigent",
            "omnigentTarget": tool_name,
        }

        try:
            response = await asyncio.to_thread(
                _spctre_evaluate,
                connector,
                action,
                domains,
                tool_input,
                decision_endpoint,
                timeout_seconds,
            )
            status, reason, policy_refs, decision_id = _extract_result(response)
        except Exception as exc:
            status = "DENY" if outage_policy == "fail-closed" else "WARN"
            reason = f"Spctre decision unavailable ({type(exc).__name__}: {exc}); outage_policy={outage_policy}."
            policy_refs = ["system.spctre_decision_unavailable"]
            decision_id = f"omnigent-outage-{uuid.uuid4()}"

        latency_ms = int((time.time() - started) * 1000)
        if emit_evidence:
            _spctre_emit_background(
                connector,
                action,
                status,
                reason,
                decision_id,
                policy_refs,
                latency_ms,
                raw_evidence,
                timeout_seconds,
            )

        if status == "DENY":
            return {"result": "DENY", "reason": reason}
        if status == "ESCALATE":
            return {"result": "ASK", "reason": reason}
        if status == "WARN":
            return {"result": "ALLOW", "reason": reason}
        return {"result": "ALLOW", "reason": reason}

    return evaluate


POLICY_REGISTRY = [
    {
        "name": "Spctre policy decision bridge",
        "description": "Delegates Omnigent tool-call policy decisions to Spctre and records decision evidence.",
        "handler": "spctre_policy.spctre_policy",
        "kind": "factory",
        "params_schema": {
            "type": "object",
            "properties": {
                "decision_endpoint": {
                    "type": "string",
                    "default": "/api/v1/evaluate",
                    "description": "Spctre policy decision endpoint path or absolute URL.",
                },
                "outage_policy": {
                    "type": "string",
                    "enum": ["fail-open", "fail-closed"],
                    "default": "fail-open",
                    "description": "Policy decision when Spctre is unavailable.",
                },
                "timeout_seconds": {
                    "type": "number",
                    "default": 5.0,
                    "description": "HTTP timeout for Spctre decision and evidence calls.",
                },
                "emit_evidence": {
                    "type": "boolean",
                    "default": True,
                    "description": "Emit Spctre decision evidence from the Omnigent policy.",
                },
            },
        },
    }
]
