# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.
#
# Use the generated wrapper to enable zero-change OpenAI Agents SDK governance:
#   .spctre/spctre-python python your_agent.py

import importlib
import json
import os
import threading
import time
import urllib.request
import uuid

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_WORKSPACE = os.environ.get("SPCTRE_WORKSPACE", "__SPCTRE_WORKSPACE_ID__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)


def _spctre_emit(
    connector, action, status, reason, latency_ms=0, prompt_tokens=None, completion_tokens=None
):
    if not _SPCTRE_KEY:
        return
    has_context = bool(_SPCTRE_POLICY_CONTEXT and _SPCTRE_POLICY_CONTEXT[0].get("artifactHash"))
    policy_refs = (
        ["system.governance_active"]
        if action == "governance_active"
        else ([f"openai-agents.tool.{action}"] if has_context else ["gateway.provenance-gap"])
    )
    payload = {
        "decisionId": f"openai-agents-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        "runtimeTarget": {"stack": "OPENAI_AGENTS", "adapter": "spctre-openai-agents-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": "openai-agents",
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": policy_refs,
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "openai-agents-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "openai-agents-hook",
        "ingestMode": "gateway",
        "rawEvidence": {
            "_source": "gateway",
            "_gateway_provider": "openai-agents-hook",
            "_framework": "openai-agents",
        },
    }
    if prompt_tokens is not None:
        payload["promptTokens"] = prompt_tokens
        payload["rawEvidence"]["promptTokens"] = prompt_tokens
    if completion_tokens is not None:
        payload["completionTokens"] = completion_tokens
        payload["rawEvidence"]["completionTokens"] = completion_tokens
    if prompt_tokens is not None and completion_tokens is not None:
        payload["totalTokens"] = prompt_tokens + completion_tokens
        payload["rawEvidence"]["totalTokens"] = prompt_tokens + completion_tokens
    try:
        req = urllib.request.Request(
            f"{_SPCTRE_URL}/api/evidence",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {_SPCTRE_KEY}",
                "x-spctre-source": "gateway",
            },
            method="POST",
        )
        urllib.request.urlopen(req, timeout=3)
    except Exception:
        pass  # Evidence emission is non-fatal; agent continues regardless.


def _extract_openai_agents_usage(response):
    """Extract token counts from an OpenAI Agents SDK model response."""
    try:
        # ModelResponse.usage (OpenAI Agents SDK >= 0.0.4)
        usage = getattr(response, "usage", None)
        if usage is not None:
            input_tokens = getattr(usage, "input_tokens", None) or getattr(
                usage, "prompt_tokens", None
            )
            output_tokens = getattr(usage, "output_tokens", None) or getattr(
                usage, "completion_tokens", None
            )
            return input_tokens, output_tokens
        # Raw OpenAI ChatCompletion.usage
        if isinstance(usage, dict):
            return usage.get("prompt_tokens"), usage.get("completion_tokens")
    except Exception:
        pass
    return None, None


def _spctre_install_openai_agents_hook():
    try:
        module = importlib.import_module("agents")
    except Exception:
        return  # openai-agents not installed; hook inactive.

    FunctionTool = getattr(module, "FunctionTool", None)
    if FunctionTool is None:
        return  # API shape not recognized; hook inactive.

    if getattr(FunctionTool, "_spctre_patched", False):
        return

    _original_on_invoke_tool = getattr(FunctionTool, "on_invoke_tool", None)
    if not callable(_original_on_invoke_tool):
        return  # API shape not recognized; hook inactive.

    async def _patched_on_invoke_tool(self, ctx, input):
        tool_name = getattr(self, "name", None) or type(self).__name__
        action = tool_name.lower().replace(" ", "_").replace("-", "_")
        start = time.monotonic()
        try:
            result = await _original_on_invoke_tool(self, ctx, input)
            latency_ms = int((time.monotonic() - start) * 1000)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "openai-agents",
                    action,
                    "ALLOW",
                    f"Tool {tool_name} invoked successfully.",
                    latency_ms,
                ),
                daemon=False,
            ).start()
            return result
        except Exception as exc:
            latency_ms = int((time.monotonic() - start) * 1000)
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "openai-agents",
                    action,
                    "DENY",
                    f"Tool {tool_name} raised {type(exc).__name__}: {exc}",
                    latency_ms,
                ),
                daemon=False,
            ).start()
            raise

    FunctionTool.on_invoke_tool = _patched_on_invoke_tool
    FunctionTool._spctre_patched = True
    threading.Thread(
        target=_spctre_emit,
        args=(
            "openai-agents",
            "governance_active",
            "ALLOW",
            "OpenAI Agents governance adapter patched and active.",
            0,
        ),
        daemon=False,
    ).start()


def _spctre_install_openai_agents_model_hook():
    """Patch OpenAI Agents model.get_response to capture token usage telemetry."""
    try:
        module = importlib.import_module("agents.models.openai_responses")
        OpenAIResponsesModel = getattr(module, "OpenAIResponsesModel", None)
        if OpenAIResponsesModel is None:
            module = importlib.import_module("agents.models.openai_chatcompletions")
            OpenAIResponsesModel = getattr(module, "OpenAIChatCompletionsModel", None)
        if OpenAIResponsesModel is None:
            return

        if getattr(OpenAIResponsesModel, "_spctre_model_patched", False):
            return

        _original_get_response = getattr(OpenAIResponsesModel, "get_response", None)
        if not callable(_original_get_response):
            return

        async def _patched_get_response(self, *args, **kwargs):
            start = time.monotonic()
            result = await _original_get_response(self, *args, **kwargs)
            latency_ms = int((time.monotonic() - start) * 1000)
            prompt_tokens, completion_tokens = _extract_openai_agents_usage(result)
            if prompt_tokens is not None or completion_tokens is not None:
                threading.Thread(
                    target=_spctre_emit,
                    args=(
                        "openai-agents",
                        "llm_call",
                        "ALLOW",
                        "OpenAI Agents model call completed.",
                        latency_ms,
                        prompt_tokens,
                        completion_tokens,
                    ),
                    daemon=False,
                ).start()
            return result

        OpenAIResponsesModel.get_response = _patched_get_response
        OpenAIResponsesModel._spctre_model_patched = True
    except Exception:
        pass  # Model internals vary across SDK versions; hook is best-effort.


_spctre_install_openai_agents_hook()
_spctre_install_openai_agents_model_hook()
