# Auto-generated by spctre watch --framework __SPCTRE_FRAMEWORK__
# Do not edit manually - re-run 'spctre watch --framework __SPCTRE_FRAMEWORK__' to refresh.
#
# Use the generated wrapper to enable zero-change Strands Agents governance:
#   .spctre/spctre-python python your_agent.py

import importlib
import json
import os
import threading
import time
import urllib.request
import uuid

_SPCTRE_URL = os.environ.get("SPCTRE_URL", "__SPCTRE_CONTROL_PLANE_URL__")
_SPCTRE_KEY = os.environ.get("SPCTRE_API_TOKEN", "__SPCTRE_TOKEN__")
_SPCTRE_WORKSPACE = os.environ.get("SPCTRE_WORKSPACE", "__SPCTRE_WORKSPACE_ID__")
_SPCTRE_AGENT = os.environ.get("SPCTRE_AGENT", "__SPCTRE_AGENT_ID__")
_SPCTRE_ENV = os.environ.get("SPCTRE_ENVIRONMENT", "__SPCTRE_ENVIRONMENT__")
_SPCTRE_ARTIFACT_HASH = os.environ.get("SPCTRE_ARTIFACT_HASH", "__SPCTRE_ARTIFACT_HASH__")
_SPCTRE_POLICY_CONTEXT = json.loads(
    os.environ.get("SPCTRE_POLICY_CONTEXT", "__SPCTRE_POLICY_CONTEXT_JSON__")
)


def _spctre_emit(
    connector, action, status, reason, latency_ms=0, prompt_tokens=None, completion_tokens=None
):
    if not _SPCTRE_KEY:
        return
    has_context = bool(_SPCTRE_POLICY_CONTEXT and _SPCTRE_POLICY_CONTEXT[0].get("artifactHash"))
    policy_refs = (
        ["system.governance_active"]
        if action == "governance_active"
        else ([f"strands.tool.{action}"] if has_context else ["gateway.provenance-gap"])
    )
    payload = {
        "decisionId": f"strands-{uuid.uuid4()}",
        "environment": _SPCTRE_ENV,
        # Strands is AWS-native but not the same as Bedrock; CUSTOM avoids misrepresentation.
        "runtimeTarget": {"stack": "CUSTOM", "adapter": "spctre-strands-hook"},
        "agentId": _SPCTRE_AGENT,
        "connector": "strands",
        "action": action,
        "status": status,
        "reason": reason,
        "policyRefs": policy_refs,
        "artifactHash": _SPCTRE_ARTIFACT_HASH or "strands-unresolved",
        "policyContext": _SPCTRE_POLICY_CONTEXT,
        "latencyMs": latency_ms,
        "sourceType": "strands-hook",
        "ingestMode": "gateway",
        "rawEvidence": {
            "_source": "gateway",
            "_gateway_provider": "strands-hook",
            "_framework": "strands",
        },
    }
    if prompt_tokens is not None:
        payload["promptTokens"] = prompt_tokens
        payload["rawEvidence"]["promptTokens"] = prompt_tokens
    if completion_tokens is not None:
        payload["completionTokens"] = completion_tokens
        payload["rawEvidence"]["completionTokens"] = completion_tokens
    if prompt_tokens is not None and completion_tokens is not None:
        payload["totalTokens"] = prompt_tokens + completion_tokens
        payload["rawEvidence"]["totalTokens"] = prompt_tokens + completion_tokens
    try:
        req = urllib.request.Request(
            f"{_SPCTRE_URL}/api/v1/evidence",
            data=json.dumps(payload).encode(),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {_SPCTRE_KEY}",
                "x-spctre-source": "gateway",
            },
            method="POST",
        )
        urllib.request.urlopen(req, timeout=3)
    except Exception:
        pass  # Evidence emission is non-fatal; agent continues regardless.


def _extract_strands_usage(result):
    """Extract token counts from a Strands tool handler result or Bedrock stream metrics."""
    try:
        # Strands StreamEvent with metrics dict (Bedrock Converse / InvokeModel)
        metrics = None
        if isinstance(result, dict):
            metrics = result.get("metrics") or result.get("usage")
        else:
            metrics = getattr(result, "metrics", None) or getattr(result, "usage", None)
        if isinstance(metrics, dict):
            input_tokens = (
                metrics.get("inputTokens")
                or metrics.get("input_tokens")
                or metrics.get("prompt_tokens")
            )
            output_tokens = (
                metrics.get("outputTokens")
                or metrics.get("output_tokens")
                or metrics.get("completion_tokens")
            )
            return input_tokens, output_tokens
    except Exception:
        pass
    return None, None


def _spctre_install_strands_hook():
    # Strands Agents (strands-agents on PyPI). Tools defined with @tool are
    # FunctionTool instances whose __call__ executes the wrapped function.
    # The agent drives tool calls through process_tool_call on its event loop handler.
    try:
        module = importlib.import_module("strands.handlers.tool_handler")
        ToolHandler = getattr(module, "ToolHandler", None)

        if ToolHandler is not None and not getattr(ToolHandler, "_spctre_patched", False):
            _original_process = getattr(ToolHandler, "process", None)
            if not callable(_original_process):
                raise AttributeError("ToolHandler.process is not callable")

            async def _patched_process(self, tool_use, **kwargs):
                tool_name = (
                    tool_use.get("name", "unknown")
                    if isinstance(tool_use, dict)
                    else getattr(tool_use, "name", "unknown")
                )
                action = str(tool_name).lower().replace(" ", "_").replace("-", "_")
                start = time.monotonic()
                try:
                    result = await _original_process(self, tool_use, **kwargs)
                    latency_ms = int((time.monotonic() - start) * 1000)
                    prompt_tokens, completion_tokens = _extract_strands_usage(result)
                    threading.Thread(
                        target=_spctre_emit,
                        args=(
                            "strands",
                            action,
                            "ALLOW",
                            f"Tool {tool_name} processed successfully.",
                            latency_ms,
                            prompt_tokens,
                            completion_tokens,
                        ),
                        daemon=False,
                    ).start()
                    return result
                except Exception as exc:
                    latency_ms = int((time.monotonic() - start) * 1000)
                    threading.Thread(
                        target=_spctre_emit,
                        args=(
                            "strands",
                            action,
                            "DENY",
                            f"Tool {tool_name} raised {type(exc).__name__}: {exc}",
                            latency_ms,
                        ),
                        daemon=False,
                    ).start()
                    raise

            ToolHandler.process = _patched_process
            ToolHandler._spctre_patched = True
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "strands",
                    "governance_active",
                    "ALLOW",
                    "Strands governance adapter patched and active.",
                    0,
                ),
                daemon=False,
            ).start()
            return
    except Exception:
        pass

    # Fallback: intercept at the FunctionTool level if ToolHandler is unavailable.
    try:
        module = importlib.import_module("strands.tools.function_tool")
        FunctionTool = getattr(module, "FunctionTool", None)
        if FunctionTool is None:
            return

        if not getattr(FunctionTool, "_spctre_patched", False):
            # noqa B004: this retrieves __call__ to wrap it, not to test
            # callability — the patched implementation invokes
            # _original_call. Rewriting to callable() would drop the
            # reference and break the hook.
            _original_call = getattr(FunctionTool, "__call__", None)  # noqa: B004
            if not callable(_original_call):
                return  # API shape not recognized; hook inactive.

            def _patched_call(self, tool_use, **kwargs):
                tool_name = (
                    getattr(self, "tool_name", None)
                    or getattr(self, "name", None)
                    or type(self).__name__
                )
                action = str(tool_name).lower().replace(" ", "_").replace("-", "_")
                start = time.monotonic()
                try:
                    result = _original_call(self, tool_use, **kwargs)
                    latency_ms = int((time.monotonic() - start) * 1000)
                    prompt_tokens, completion_tokens = _extract_strands_usage(result)
                    threading.Thread(
                        target=_spctre_emit,
                        args=(
                            "strands",
                            action,
                            "ALLOW",
                            f"Tool {tool_name} called successfully.",
                            latency_ms,
                            prompt_tokens,
                            completion_tokens,
                        ),
                        daemon=False,
                    ).start()
                    return result
                except Exception as exc:
                    latency_ms = int((time.monotonic() - start) * 1000)
                    threading.Thread(
                        target=_spctre_emit,
                        args=(
                            "strands",
                            action,
                            "DENY",
                            f"Tool {tool_name} raised {type(exc).__name__}: {exc}",
                            latency_ms,
                        ),
                        daemon=False,
                    ).start()
                    raise

            FunctionTool.__call__ = _patched_call
            FunctionTool._spctre_patched = True
            threading.Thread(
                target=_spctre_emit,
                args=(
                    "strands",
                    "governance_active",
                    "ALLOW",
                    "Strands governance adapter patched and active.",
                    0,
                ),
                daemon=False,
            ).start()
    except Exception:
        pass  # strands-agents not installed; hook inactive.


_spctre_install_strands_hook()
