import * as fs from "node:fs";
import * as path from "node:path";

interface PackScaffoldOptions {
  output?: string;
  connector?: string;
  version: string;
}

type PackScaffoldContext = { name: string; connector: string; version: string; date: string };

type ScaffoldFile = { relativePath: string; content: string };

export async function packScaffold(nameArg: string | undefined, options: PackScaffoldOptions) {
  const context = buildScaffoldContext(nameArg, options);
  const outputDirName = options.output ?? `spctre-pack-${context.name}`;
  const targetDir = path.resolve(process.cwd(), outputDirName);

  console.log(`Scaffolding new Spctre governance pack: "${context.name}"`);
  console.log(`Target directory: ${targetDir}`);

  ensureDirectory(targetDir, "target directory");
  writeScaffoldFiles(targetDir, buildScaffoldFiles(context));

  console.log(`\nSuccess! Governance pack scaffolded in ${outputDirName}`);
  console.log(`To validate your new pack rules, run:`);
  console.log(`  spctre lint ${path.join(outputDirName, "rules.yaml")} --offline`);
}

function buildScaffoldContext(
  nameArg: string | undefined,
  options: PackScaffoldOptions,
): PackScaffoldContext {
  const name = nameArg ? nameArg.trim() : "custom-connector";
  return {
    name,
    connector: (options.connector ?? name).toLowerCase().replace(/[^a-z0-9-_]/g, ""),
    version: options.version.trim() || "1.0.0",
    date: new Date().toISOString().split("T")[0],
  };
}

function buildScaffoldFiles(context: PackScaffoldContext): ScaffoldFile[] {
  return [
    { relativePath: "README.md", content: renderReadme(context) },
    { relativePath: "rules.yaml", content: renderRules(context) },
    { relativePath: "schema.json", content: renderSchema() },
    { relativePath: path.join(".github", "workflows", "lint-pack.yml"), content: renderWorkflow() },
  ];
}

function writeScaffoldFiles(targetDir: string, files: ScaffoldFile[]) {
  try {
    for (const file of files) {
      const fullPath = path.join(targetDir, file.relativePath);
      ensureDirectory(path.dirname(fullPath), path.dirname(file.relativePath));
      fs.writeFileSync(fullPath, file.content, "utf8");
      console.log(`  Created ${file.relativePath}`);
    }
  } catch (error) {
    console.error(`Error: Failed to write scaffold files: ${String(error)}`);
    process.exit(1);
  }
}

function ensureDirectory(directory: string, label: string) {
  try {
    if (!fs.existsSync(directory)) {
      fs.mkdirSync(directory, { recursive: true });
    }
  } catch (error) {
    console.error(`Error: Failed to create ${label}: ${String(error)}`);
    process.exit(1);
  }
}

function renderReadme({ name }: PackScaffoldContext): string {
  return `# Spctre Connector Governance Pack: ${name}

This connector governance pack provides default security and compliance rules for the **${name}** integration in Spctre.

## Contents
- \`rules.yaml\`: AGT-compliant policy rules for this connector.
- \`schema.json\`: Schema validation definition for policy authoring.
- \`.github/workflows/lint-pack.yml\`: GitHub Actions workflow to validate rules on every pull request.

## Rules Overview
This pack defines the following default policy postures:
1. **Deny Unauthenticated Access:** Blocks any tool calls made without credential verification or valid tokens.
2. **Warn on Mutation Actions:** Emits compliance warnings when destructive actions (like delete, update-settings) are executed in production.
3. **Audit Trail Requirement:** Asserts that naming and tracing metadata must accompany all data exfiltration operations.

## Customization
To customize this pack for your organization:
1. Edit \`rules.yaml\` to add or modify rules matching your needs.
2. Run validation locally using Spctre CLI:
   \`\`\`bash
   spctre lint rules.yaml
   \`\`\`
3. Commit and push your changes to run automated CI checks.
`;
}

function renderRules({ name, connector, version, date }: PackScaffoldContext): string {
  return `# Spctre Connector Governance Pack - ${name}
# License: Apache-2.0
#
# Standard AGT-compatible policy definitions for ${connector} integration.

metadata:
  name: "${name} Governance Pack"
  version: "${version}"
  connector: "${connector}"
  author: "Community Contributor"
  owner: "community"
  riskLevel: "MEDIUM"
  riskTags:
    - "${connector}"
    - "third-party"
    - "data-governance"
  category: "Connector Governance"
  compatibilityTargets:
    - "AGT_PREVIEW"
    - "SPCTRE_CONTROL_PLANE"
  reviewRoles:
    - "SECURITY"
    - "COMPLIANCE"
  minimumApprovals: 1
  changelog:
    - version: "${version}"
      date: "${date}"
      summary: "Initial scaffold generated by Spctre CLI."

rules:
  - stable_rule_id: "${connector}.auth.block_unauthenticated"
    title: "Block ${name} operations without explicit authenticated principal context"
    effect: "DENY"
    domains:
      - "${connector}-access"
    connectors:
      - "${connector}"
    actions:
      - "auth.missing_context"
      - "auth.unauthenticated_call"
    immutable: true

  - stable_rule_id: "${connector}.data.warn_sensitive_exfiltration"
    title: "Warn when exfiltrating sensitive data records from ${name} in production"
    effect: "WARN"
    domains:
      - "data-exfiltration"
    connectors:
      - "${connector}"
    actions:
      - "data.export"
      - "data.bulk_read"
    immutable: false

  - stable_rule_id: "${connector}.mutation.block_destructive_actions"
    title: "Block destructive mutation operations on ${name} configuration"
    effect: "DENY"
    domains:
      - "mutation"
    connectors:
      - "${connector}"
    actions:
      - "config.delete"
      - "config.reset"
    immutable: false
`;
}

function renderSchema(): string {
  return `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Spctre Governance Pack Schema",
  "type": "object",
  "required": ["metadata", "rules"],
  "properties": {
    "metadata": {
      "type": "object",
      "required": ["name", "version", "connector"],
      "properties": {
        "name": { "type": "string" },
        "version": { "type": "string" },
        "connector": { "type": "string" },
        "author": { "type": "string" },
        "owner": { "type": "string" },
        "riskLevel": { "type": "string", "enum": ["LOW", "MEDIUM", "HIGH", "CRITICAL"] },
        "riskTags": { "type": "array", "items": { "type": "string" } },
        "category": { "type": "string" },
        "compatibilityTargets": { "type": "array", "items": { "type": "string" } },
        "reviewRoles": { "type": "array", "items": { "type": "string" } },
        "minimumApprovals": { "type": "integer" }
      }
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["stable_rule_id", "title", "effect"],
        "properties": {
          "stable_rule_id": { "type": "string" },
          "title": { "type": "string" },
          "effect": { "type": "string", "enum": ["ALLOW", "DENY", "WARN"] },
          "domains": { "type": "array", "items": { "type": "string" } },
          "connectors": { "type": "array", "items": { "type": "string" } },
          "actions": { "type": "array", "items": { "type": "string" } },
          "immutable": { "type": "boolean" },
          "priority": { "type": "integer" }
        }
      }
    }
  }
}
`;
}

function renderWorkflow(): string {
  return `# GitHub Actions workflow to lint the Spctre connector pack rules.
# This ensures all rules are syntactically valid and comply with the pack catalog.

name: Lint Spctre Governance Pack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Spctre CLI
        run: npm install -g @spctre/cli

      - name: Lint Policy Pack Rules
        run: spctre lint rules.yaml
`;
}
