// Package worker provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package worker

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for BundleExportFormat.
const (
	Cedar          BundleExportFormat = "cedar"
	McpProxyConfig BundleExportFormat = "mcp-proxy-config"
	OpaBundle      BundleExportFormat = "opa-bundle"
	OpaRego        BundleExportFormat = "opa-rego"
	SpctreJSON     BundleExportFormat = "spctre-json"
)

// Valid indicates whether the value is a known member of the BundleExportFormat enum.
func (e BundleExportFormat) Valid() bool {
	switch e {
	case Cedar:
		return true
	case McpProxyConfig:
		return true
	case OpaBundle:
		return true
	case OpaRego:
		return true
	case SpctreJSON:
		return true
	default:
		return false
	}
}

// Defines values for BundleExportManifestCompatibilityLevel.
const (
	LOSSLESSPRESERVED  BundleExportManifestCompatibilityLevel = "LOSSLESS_PRESERVED"
	NATIVE             BundleExportManifestCompatibilityLevel = "NATIVE"
	PARTIALSEMANTICMAP BundleExportManifestCompatibilityLevel = "PARTIAL_SEMANTIC_MAP"
)

// Valid indicates whether the value is a known member of the BundleExportManifestCompatibilityLevel enum.
func (e BundleExportManifestCompatibilityLevel) Valid() bool {
	switch e {
	case LOSSLESSPRESERVED:
		return true
	case NATIVE:
		return true
	case PARTIALSEMANTICMAP:
		return true
	default:
		return false
	}
}

// Defines values for ContextBudgetIngestRequestEventType.
const (
	BUDGETBREACH       ContextBudgetIngestRequestEventType = "BUDGET_BREACH"
	CONTEXTSOURCEMIX   ContextBudgetIngestRequestEventType = "CONTEXT_SOURCE_MIX"
	SUMMARIZATIONEVENT ContextBudgetIngestRequestEventType = "SUMMARIZATION_EVENT"
	TOKENGROWTH        ContextBudgetIngestRequestEventType = "TOKEN_GROWTH"
)

// Valid indicates whether the value is a known member of the ContextBudgetIngestRequestEventType enum.
func (e ContextBudgetIngestRequestEventType) Valid() bool {
	switch e {
	case BUDGETBREACH:
		return true
	case CONTEXTSOURCEMIX:
		return true
	case SUMMARIZATIONEVENT:
		return true
	case TOKENGROWTH:
		return true
	default:
		return false
	}
}

// Defines values for ContextBudgetIngestRequestGovernanceAction.
const (
	ContextBudgetIngestRequestGovernanceActionALLOW    ContextBudgetIngestRequestGovernanceAction = "ALLOW"
	ContextBudgetIngestRequestGovernanceActionESCALATE ContextBudgetIngestRequestGovernanceAction = "ESCALATE"
	ContextBudgetIngestRequestGovernanceActionREVIEW   ContextBudgetIngestRequestGovernanceAction = "REVIEW"
	ContextBudgetIngestRequestGovernanceActionWARN     ContextBudgetIngestRequestGovernanceAction = "WARN"
)

// Valid indicates whether the value is a known member of the ContextBudgetIngestRequestGovernanceAction enum.
func (e ContextBudgetIngestRequestGovernanceAction) Valid() bool {
	switch e {
	case ContextBudgetIngestRequestGovernanceActionALLOW:
		return true
	case ContextBudgetIngestRequestGovernanceActionESCALATE:
		return true
	case ContextBudgetIngestRequestGovernanceActionREVIEW:
		return true
	case ContextBudgetIngestRequestGovernanceActionWARN:
		return true
	default:
		return false
	}
}

// Defines values for EscalationStatusResponseResolutionOutcome.
const (
	EscalationStatusResponseResolutionOutcomeABORT    EscalationStatusResponseResolutionOutcome = "ABORT"
	EscalationStatusResponseResolutionOutcomeESCALATE EscalationStatusResponseResolutionOutcome = "ESCALATE"
	EscalationStatusResponseResolutionOutcomePROCEED  EscalationStatusResponseResolutionOutcome = "PROCEED"
)

// Valid indicates whether the value is a known member of the EscalationStatusResponseResolutionOutcome enum.
func (e EscalationStatusResponseResolutionOutcome) Valid() bool {
	switch e {
	case EscalationStatusResponseResolutionOutcomeABORT:
		return true
	case EscalationStatusResponseResolutionOutcomeESCALATE:
		return true
	case EscalationStatusResponseResolutionOutcomePROCEED:
		return true
	default:
		return false
	}
}

// Defines values for EscalationStatusResponseStatus.
const (
	EXPIRED  EscalationStatusResponseStatus = "EXPIRED"
	INREVIEW EscalationStatusResponseStatus = "IN_REVIEW"
	PENDING  EscalationStatusResponseStatus = "PENDING"
	RESOLVED EscalationStatusResponseStatus = "RESOLVED"
)

// Valid indicates whether the value is a known member of the EscalationStatusResponseStatus enum.
func (e EscalationStatusResponseStatus) Valid() bool {
	switch e {
	case EXPIRED:
		return true
	case INREVIEW:
		return true
	case PENDING:
		return true
	case RESOLVED:
		return true
	default:
		return false
	}
}

// Defines values for EvidenceIngestRequestIngestMode.
const (
	Gateway  EvidenceIngestRequestIngestMode = "gateway"
	Standard EvidenceIngestRequestIngestMode = "standard"
)

// Valid indicates whether the value is a known member of the EvidenceIngestRequestIngestMode enum.
func (e EvidenceIngestRequestIngestMode) Valid() bool {
	switch e {
	case Gateway:
		return true
	case Standard:
		return true
	default:
		return false
	}
}

// Defines values for EvidenceIngestRequestPluginSource.
const (
	CorporateMarketplace EvidenceIngestRequestPluginSource = "corporate_marketplace"
	CorporatePrivate     EvidenceIngestRequestPluginSource = "corporate_private"
	PublicMarketplace    EvidenceIngestRequestPluginSource = "public_marketplace"
	UserBuilt            EvidenceIngestRequestPluginSource = "user_built"
)

// Valid indicates whether the value is a known member of the EvidenceIngestRequestPluginSource enum.
func (e EvidenceIngestRequestPluginSource) Valid() bool {
	switch e {
	case CorporateMarketplace:
		return true
	case CorporatePrivate:
		return true
	case PublicMarketplace:
		return true
	case UserBuilt:
		return true
	default:
		return false
	}
}

// Defines values for EvidenceIngestResponseGatewayOutcome.
const (
	EvidenceIngestResponseGatewayOutcomeABORT    EvidenceIngestResponseGatewayOutcome = "ABORT"
	EvidenceIngestResponseGatewayOutcomeESCALATE EvidenceIngestResponseGatewayOutcome = "ESCALATE"
	EvidenceIngestResponseGatewayOutcomePROCEED  EvidenceIngestResponseGatewayOutcome = "PROCEED"
)

// Valid indicates whether the value is a known member of the EvidenceIngestResponseGatewayOutcome enum.
func (e EvidenceIngestResponseGatewayOutcome) Valid() bool {
	switch e {
	case EvidenceIngestResponseGatewayOutcomeABORT:
		return true
	case EvidenceIngestResponseGatewayOutcomeESCALATE:
		return true
	case EvidenceIngestResponseGatewayOutcomePROCEED:
		return true
	default:
		return false
	}
}

// Defines values for EvidenceIngestResponseGatewayRiskLevel.
const (
	EvidenceIngestResponseGatewayRiskLevelCRITICAL EvidenceIngestResponseGatewayRiskLevel = "CRITICAL"
	EvidenceIngestResponseGatewayRiskLevelHIGH     EvidenceIngestResponseGatewayRiskLevel = "HIGH"
	EvidenceIngestResponseGatewayRiskLevelLOW      EvidenceIngestResponseGatewayRiskLevel = "LOW"
	EvidenceIngestResponseGatewayRiskLevelMEDIUM   EvidenceIngestResponseGatewayRiskLevel = "MEDIUM"
)

// Valid indicates whether the value is a known member of the EvidenceIngestResponseGatewayRiskLevel enum.
func (e EvidenceIngestResponseGatewayRiskLevel) Valid() bool {
	switch e {
	case EvidenceIngestResponseGatewayRiskLevelCRITICAL:
		return true
	case EvidenceIngestResponseGatewayRiskLevelHIGH:
		return true
	case EvidenceIngestResponseGatewayRiskLevelLOW:
		return true
	case EvidenceIngestResponseGatewayRiskLevelMEDIUM:
		return true
	default:
		return false
	}
}

// Defines values for EvidenceLayer.
const (
	Agent   EvidenceLayer = "agent"
	Sandbox EvidenceLayer = "sandbox"
)

// Valid indicates whether the value is a known member of the EvidenceLayer enum.
func (e EvidenceLayer) Valid() bool {
	switch e {
	case Agent:
		return true
	case Sandbox:
		return true
	default:
		return false
	}
}

// Defines values for GatewayDecisionOutcome.
const (
	GatewayDecisionOutcomeABORT    GatewayDecisionOutcome = "ABORT"
	GatewayDecisionOutcomeESCALATE GatewayDecisionOutcome = "ESCALATE"
	GatewayDecisionOutcomePROCEED  GatewayDecisionOutcome = "PROCEED"
)

// Valid indicates whether the value is a known member of the GatewayDecisionOutcome enum.
func (e GatewayDecisionOutcome) Valid() bool {
	switch e {
	case GatewayDecisionOutcomeABORT:
		return true
	case GatewayDecisionOutcomeESCALATE:
		return true
	case GatewayDecisionOutcomePROCEED:
		return true
	default:
		return false
	}
}

// Defines values for GatewayDecisionRiskLevel.
const (
	GatewayDecisionRiskLevelCRITICAL GatewayDecisionRiskLevel = "CRITICAL"
	GatewayDecisionRiskLevelHIGH     GatewayDecisionRiskLevel = "HIGH"
	GatewayDecisionRiskLevelLOW      GatewayDecisionRiskLevel = "LOW"
	GatewayDecisionRiskLevelMEDIUM   GatewayDecisionRiskLevel = "MEDIUM"
)

// Valid indicates whether the value is a known member of the GatewayDecisionRiskLevel enum.
func (e GatewayDecisionRiskLevel) Valid() bool {
	switch e {
	case GatewayDecisionRiskLevelCRITICAL:
		return true
	case GatewayDecisionRiskLevelHIGH:
		return true
	case GatewayDecisionRiskLevelLOW:
		return true
	case GatewayDecisionRiskLevelMEDIUM:
		return true
	default:
		return false
	}
}

// Defines values for GatewayDecisionRequestRiskLevel.
const (
	GatewayDecisionRequestRiskLevelCRITICAL GatewayDecisionRequestRiskLevel = "CRITICAL"
	GatewayDecisionRequestRiskLevelHIGH     GatewayDecisionRequestRiskLevel = "HIGH"
	GatewayDecisionRequestRiskLevelLOW      GatewayDecisionRequestRiskLevel = "LOW"
	GatewayDecisionRequestRiskLevelMEDIUM   GatewayDecisionRequestRiskLevel = "MEDIUM"
)

// Valid indicates whether the value is a known member of the GatewayDecisionRequestRiskLevel enum.
func (e GatewayDecisionRequestRiskLevel) Valid() bool {
	switch e {
	case GatewayDecisionRequestRiskLevelCRITICAL:
		return true
	case GatewayDecisionRequestRiskLevelHIGH:
		return true
	case GatewayDecisionRequestRiskLevelLOW:
		return true
	case GatewayDecisionRequestRiskLevelMEDIUM:
		return true
	default:
		return false
	}
}

// Defines values for GatewayResolveRequestResolutionOutcome.
const (
	GatewayResolveRequestResolutionOutcomeABORT    GatewayResolveRequestResolutionOutcome = "ABORT"
	GatewayResolveRequestResolutionOutcomeESCALATE GatewayResolveRequestResolutionOutcome = "ESCALATE"
	GatewayResolveRequestResolutionOutcomePROCEED  GatewayResolveRequestResolutionOutcome = "PROCEED"
)

// Valid indicates whether the value is a known member of the GatewayResolveRequestResolutionOutcome enum.
func (e GatewayResolveRequestResolutionOutcome) Valid() bool {
	switch e {
	case GatewayResolveRequestResolutionOutcomeABORT:
		return true
	case GatewayResolveRequestResolutionOutcomeESCALATE:
		return true
	case GatewayResolveRequestResolutionOutcomePROCEED:
		return true
	default:
		return false
	}
}

// Defines values for GitCheckpointIngestRequestCheckpointDiffFilesStatus.
const (
	Added    GitCheckpointIngestRequestCheckpointDiffFilesStatus = "added"
	Copied   GitCheckpointIngestRequestCheckpointDiffFilesStatus = "copied"
	Deleted  GitCheckpointIngestRequestCheckpointDiffFilesStatus = "deleted"
	Modified GitCheckpointIngestRequestCheckpointDiffFilesStatus = "modified"
	Renamed  GitCheckpointIngestRequestCheckpointDiffFilesStatus = "renamed"
	Unmerged GitCheckpointIngestRequestCheckpointDiffFilesStatus = "unmerged"
)

// Valid indicates whether the value is a known member of the GitCheckpointIngestRequestCheckpointDiffFilesStatus enum.
func (e GitCheckpointIngestRequestCheckpointDiffFilesStatus) Valid() bool {
	switch e {
	case Added:
		return true
	case Copied:
		return true
	case Deleted:
		return true
	case Modified:
		return true
	case Renamed:
		return true
	case Unmerged:
		return true
	default:
		return false
	}
}

// Defines values for GitCheckpointIngestRequestCheckpointDiffFormat.
const (
	NameStatus GitCheckpointIngestRequestCheckpointDiffFormat = "name-status"
	None       GitCheckpointIngestRequestCheckpointDiffFormat = "none"
	Unified    GitCheckpointIngestRequestCheckpointDiffFormat = "unified"
)

// Valid indicates whether the value is a known member of the GitCheckpointIngestRequestCheckpointDiffFormat enum.
func (e GitCheckpointIngestRequestCheckpointDiffFormat) Valid() bool {
	switch e {
	case NameStatus:
		return true
	case None:
		return true
	case Unified:
		return true
	default:
		return false
	}
}

// Defines values for PolicyImportRequestScope.
const (
	PolicyImportRequestScopeCONNECTOR    PolicyImportRequestScope = "CONNECTOR"
	PolicyImportRequestScopeENVIRONMENT  PolicyImportRequestScope = "ENVIRONMENT"
	PolicyImportRequestScopeORGANIZATION PolicyImportRequestScope = "ORGANIZATION"
	PolicyImportRequestScopeWORKSPACE    PolicyImportRequestScope = "WORKSPACE"
)

// Valid indicates whether the value is a known member of the PolicyImportRequestScope enum.
func (e PolicyImportRequestScope) Valid() bool {
	switch e {
	case PolicyImportRequestScopeCONNECTOR:
		return true
	case PolicyImportRequestScopeENVIRONMENT:
		return true
	case PolicyImportRequestScopeORGANIZATION:
		return true
	case PolicyImportRequestScopeWORKSPACE:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeDecisionStatus.
const (
	RuntimeDecisionStatusALLOW    RuntimeDecisionStatus = "ALLOW"
	RuntimeDecisionStatusDENY     RuntimeDecisionStatus = "DENY"
	RuntimeDecisionStatusESCALATE RuntimeDecisionStatus = "ESCALATE"
	RuntimeDecisionStatusWARN     RuntimeDecisionStatus = "WARN"
)

// Valid indicates whether the value is a known member of the RuntimeDecisionStatus enum.
func (e RuntimeDecisionStatus) Valid() bool {
	switch e {
	case RuntimeDecisionStatusALLOW:
		return true
	case RuntimeDecisionStatusDENY:
		return true
	case RuntimeDecisionStatusESCALATE:
		return true
	case RuntimeDecisionStatusWARN:
		return true
	default:
		return false
	}
}

// Defines values for RuntimePolicyContextScope.
const (
	RuntimePolicyContextScopeCOMPANY      RuntimePolicyContextScope = "COMPANY"
	RuntimePolicyContextScopeCONNECTOR    RuntimePolicyContextScope = "CONNECTOR"
	RuntimePolicyContextScopeENVIRONMENT  RuntimePolicyContextScope = "ENVIRONMENT"
	RuntimePolicyContextScopeORGANIZATION RuntimePolicyContextScope = "ORGANIZATION"
	RuntimePolicyContextScopeWORKSPACE    RuntimePolicyContextScope = "WORKSPACE"
)

// Valid indicates whether the value is a known member of the RuntimePolicyContextScope enum.
func (e RuntimePolicyContextScope) Valid() bool {
	switch e {
	case RuntimePolicyContextScopeCOMPANY:
		return true
	case RuntimePolicyContextScopeCONNECTOR:
		return true
	case RuntimePolicyContextScopeENVIRONMENT:
		return true
	case RuntimePolicyContextScopeORGANIZATION:
		return true
	case RuntimePolicyContextScopeWORKSPACE:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStack.
const (
	RuntimeStackAUTOGEN      RuntimeStack = "AUTOGEN"
	RuntimeStackAWSBEDROCK   RuntimeStack = "AWS_BEDROCK"
	RuntimeStackAZUREAI      RuntimeStack = "AZURE_AI"
	RuntimeStackCLAUDECODE   RuntimeStack = "CLAUDE_CODE"
	RuntimeStackCLAUDECOWORK RuntimeStack = "CLAUDE_COWORK"
	RuntimeStackCREWAI       RuntimeStack = "CREWAI"
	RuntimeStackCUSTOM       RuntimeStack = "CUSTOM"
	RuntimeStackGOOGLEADK    RuntimeStack = "GOOGLE_ADK"
	RuntimeStackHERMES       RuntimeStack = "HERMES"
	RuntimeStackLANGCHAIN    RuntimeStack = "LANGCHAIN"
	RuntimeStackLANGGRAPH    RuntimeStack = "LANGGRAPH"
	RuntimeStackLOCAL        RuntimeStack = "LOCAL"
	RuntimeStackNEMOCLAW     RuntimeStack = "NEMOCLAW"
	RuntimeStackODYSSEUS     RuntimeStack = "ODYSSEUS"
	RuntimeStackOMNIGENT     RuntimeStack = "OMNIGENT"
	RuntimeStackOPENAIAGENTS RuntimeStack = "OPENAI_AGENTS"
	RuntimeStackOPENCLAW     RuntimeStack = "OPENCLAW"
	RuntimeStackOPENCODE     RuntimeStack = "OPENCODE"
	RuntimeStackPAPERCLIP    RuntimeStack = "PAPERCLIP"
)

// Valid indicates whether the value is a known member of the RuntimeStack enum.
func (e RuntimeStack) Valid() bool {
	switch e {
	case RuntimeStackAUTOGEN:
		return true
	case RuntimeStackAWSBEDROCK:
		return true
	case RuntimeStackAZUREAI:
		return true
	case RuntimeStackCLAUDECODE:
		return true
	case RuntimeStackCLAUDECOWORK:
		return true
	case RuntimeStackCREWAI:
		return true
	case RuntimeStackCUSTOM:
		return true
	case RuntimeStackGOOGLEADK:
		return true
	case RuntimeStackHERMES:
		return true
	case RuntimeStackLANGCHAIN:
		return true
	case RuntimeStackLANGGRAPH:
		return true
	case RuntimeStackLOCAL:
		return true
	case RuntimeStackNEMOCLAW:
		return true
	case RuntimeStackODYSSEUS:
		return true
	case RuntimeStackOMNIGENT:
		return true
	case RuntimeStackOPENAIAGENTS:
		return true
	case RuntimeStackOPENCLAW:
		return true
	case RuntimeStackOPENCODE:
		return true
	case RuntimeStackPAPERCLIP:
		return true
	default:
		return false
	}
}

// Defines values for TriggerKind.
const (
	GatewayMessage TriggerKind = "gateway_message"
	InboundWebhook TriggerKind = "inbound_webhook"
	Interactive    TriggerKind = "interactive"
	MobileDispatch TriggerKind = "mobile_dispatch"
	Routine        TriggerKind = "routine"
	Scheduled      TriggerKind = "scheduled"
)

// Valid indicates whether the value is a known member of the TriggerKind enum.
func (e TriggerKind) Valid() bool {
	switch e {
	case GatewayMessage:
		return true
	case InboundWebhook:
		return true
	case Interactive:
		return true
	case MobileDispatch:
		return true
	case Routine:
		return true
	case Scheduled:
		return true
	default:
		return false
	}
}

// Defines values for TrustEvaluateRequestConsequenceTier.
const (
	TrustEvaluateRequestConsequenceTierCRITICAL TrustEvaluateRequestConsequenceTier = "CRITICAL"
	TrustEvaluateRequestConsequenceTierHIGH     TrustEvaluateRequestConsequenceTier = "HIGH"
	TrustEvaluateRequestConsequenceTierLOW      TrustEvaluateRequestConsequenceTier = "LOW"
	TrustEvaluateRequestConsequenceTierMEDIUM   TrustEvaluateRequestConsequenceTier = "MEDIUM"
)

// Valid indicates whether the value is a known member of the TrustEvaluateRequestConsequenceTier enum.
func (e TrustEvaluateRequestConsequenceTier) Valid() bool {
	switch e {
	case TrustEvaluateRequestConsequenceTierCRITICAL:
		return true
	case TrustEvaluateRequestConsequenceTierHIGH:
		return true
	case TrustEvaluateRequestConsequenceTierLOW:
		return true
	case TrustEvaluateRequestConsequenceTierMEDIUM:
		return true
	default:
		return false
	}
}

// Defines values for TrustScoreIngestRequestSource.
const (
	EVIDENCEINGEST   TrustScoreIngestRequestSource = "EVIDENCE_INGEST"
	IDENTITYEVENT    TrustScoreIngestRequestSource = "IDENTITY_EVENT"
	MANUAL           TrustScoreIngestRequestSource = "MANUAL"
	POLICYEVALUATION TrustScoreIngestRequestSource = "POLICY_EVALUATION"
	SYSTEM           TrustScoreIngestRequestSource = "SYSTEM"
)

// Valid indicates whether the value is a known member of the TrustScoreIngestRequestSource enum.
func (e TrustScoreIngestRequestSource) Valid() bool {
	switch e {
	case EVIDENCEINGEST:
		return true
	case IDENTITYEVENT:
		return true
	case MANUAL:
		return true
	case POLICYEVALUATION:
		return true
	case SYSTEM:
		return true
	default:
		return false
	}
}

// Defines values for VerificationIngestRequestCompatibilityCheckOutcome.
const (
	VerificationIngestRequestCompatibilityCheckOutcomeFAIL VerificationIngestRequestCompatibilityCheckOutcome = "FAIL"
	VerificationIngestRequestCompatibilityCheckOutcomePASS VerificationIngestRequestCompatibilityCheckOutcome = "PASS"
	VerificationIngestRequestCompatibilityCheckOutcomeWARN VerificationIngestRequestCompatibilityCheckOutcome = "WARN"
)

// Valid indicates whether the value is a known member of the VerificationIngestRequestCompatibilityCheckOutcome enum.
func (e VerificationIngestRequestCompatibilityCheckOutcome) Valid() bool {
	switch e {
	case VerificationIngestRequestCompatibilityCheckOutcomeFAIL:
		return true
	case VerificationIngestRequestCompatibilityCheckOutcomePASS:
		return true
	case VerificationIngestRequestCompatibilityCheckOutcomeWARN:
		return true
	default:
		return false
	}
}

// Defines values for VerificationIngestRequestEscrowVerificationOutcome.
const (
	VerificationIngestRequestEscrowVerificationOutcomeFAIL VerificationIngestRequestEscrowVerificationOutcome = "FAIL"
	VerificationIngestRequestEscrowVerificationOutcomePASS VerificationIngestRequestEscrowVerificationOutcome = "PASS"
	VerificationIngestRequestEscrowVerificationOutcomeWARN VerificationIngestRequestEscrowVerificationOutcome = "WARN"
)

// Valid indicates whether the value is a known member of the VerificationIngestRequestEscrowVerificationOutcome enum.
func (e VerificationIngestRequestEscrowVerificationOutcome) Valid() bool {
	switch e {
	case VerificationIngestRequestEscrowVerificationOutcomeFAIL:
		return true
	case VerificationIngestRequestEscrowVerificationOutcomePASS:
		return true
	case VerificationIngestRequestEscrowVerificationOutcomeWARN:
		return true
	default:
		return false
	}
}

// Defines values for VerificationIngestRequestOutcome.
const (
	VerificationIngestRequestOutcomeFAIL VerificationIngestRequestOutcome = "FAIL"
	VerificationIngestRequestOutcomePASS VerificationIngestRequestOutcome = "PASS"
	VerificationIngestRequestOutcomeWARN VerificationIngestRequestOutcome = "WARN"
)

// Valid indicates whether the value is a known member of the VerificationIngestRequestOutcome enum.
func (e VerificationIngestRequestOutcome) Valid() bool {
	switch e {
	case VerificationIngestRequestOutcomeFAIL:
		return true
	case VerificationIngestRequestOutcomePASS:
		return true
	case VerificationIngestRequestOutcomeWARN:
		return true
	default:
		return false
	}
}

// Defines values for VerificationIngestRequestVerificationType.
const (
	VerificationIngestRequestVerificationTypeAGTLINTPOLICY     VerificationIngestRequestVerificationType = "AGT_LINT_POLICY"
	VerificationIngestRequestVerificationTypeAGTREDTEAM        VerificationIngestRequestVerificationType = "AGT_REDTEAM"
	VerificationIngestRequestVerificationTypeAGTREPLAY         VerificationIngestRequestVerificationType = "AGT_REPLAY"
	VerificationIngestRequestVerificationTypeAGTVERIFY         VerificationIngestRequestVerificationType = "AGT_VERIFY"
	VerificationIngestRequestVerificationTypeAGTVERIFYEVIDENCE VerificationIngestRequestVerificationType = "AGT_VERIFY_EVIDENCE"
	VerificationIngestRequestVerificationTypeCUSTOM            VerificationIngestRequestVerificationType = "CUSTOM"
)

// Valid indicates whether the value is a known member of the VerificationIngestRequestVerificationType enum.
func (e VerificationIngestRequestVerificationType) Valid() bool {
	switch e {
	case VerificationIngestRequestVerificationTypeAGTLINTPOLICY:
		return true
	case VerificationIngestRequestVerificationTypeAGTREDTEAM:
		return true
	case VerificationIngestRequestVerificationTypeAGTREPLAY:
		return true
	case VerificationIngestRequestVerificationTypeAGTVERIFY:
		return true
	case VerificationIngestRequestVerificationTypeAGTVERIFYEVIDENCE:
		return true
	case VerificationIngestRequestVerificationTypeCUSTOM:
		return true
	default:
		return false
	}
}

// Defines values for VerificationIngestResponseOutcome.
const (
	VerificationIngestResponseOutcomeFAIL VerificationIngestResponseOutcome = "FAIL"
	VerificationIngestResponseOutcomePASS VerificationIngestResponseOutcome = "PASS"
	VerificationIngestResponseOutcomeWARN VerificationIngestResponseOutcome = "WARN"
)

// Valid indicates whether the value is a known member of the VerificationIngestResponseOutcome enum.
func (e VerificationIngestResponseOutcome) Valid() bool {
	switch e {
	case VerificationIngestResponseOutcomeFAIL:
		return true
	case VerificationIngestResponseOutcomePASS:
		return true
	case VerificationIngestResponseOutcomeWARN:
		return true
	default:
		return false
	}
}

// Defines values for CloudOnlyPlan.
const (
	CloudOnlyPlanCloud CloudOnlyPlan = "cloud"
)

// Valid indicates whether the value is a known member of the CloudOnlyPlan enum.
func (e CloudOnlyPlan) Valid() bool {
	switch e {
	case CloudOnlyPlanCloud:
		return true
	default:
		return false
	}
}

// Defines values for ExportComplianceParamsFramework.
const (
	EuAiAct      ExportComplianceParamsFramework = "eu-ai-act"
	Gdpr         ExportComplianceParamsFramework = "gdpr"
	Hipaa        ExportComplianceParamsFramework = "hipaa"
	Iso27001     ExportComplianceParamsFramework = "iso27001"
	NistAiRmf    ExportComplianceParamsFramework = "nist-ai-rmf"
	PciDss       ExportComplianceParamsFramework = "pci-dss"
	PublicSector ExportComplianceParamsFramework = "public-sector"
	Soc2         ExportComplianceParamsFramework = "soc2"
)

// Valid indicates whether the value is a known member of the ExportComplianceParamsFramework enum.
func (e ExportComplianceParamsFramework) Valid() bool {
	switch e {
	case EuAiAct:
		return true
	case Gdpr:
		return true
	case Hipaa:
		return true
	case Iso27001:
		return true
	case NistAiRmf:
		return true
	case PciDss:
		return true
	case PublicSector:
		return true
	case Soc2:
		return true
	default:
		return false
	}
}

// Defines values for ExportComplianceParamsFormat.
const (
	JSON ExportComplianceParamsFormat = "json"
	Pdf  ExportComplianceParamsFormat = "pdf"
)

// Valid indicates whether the value is a known member of the ExportComplianceParamsFormat enum.
func (e ExportComplianceParamsFormat) Valid() bool {
	switch e {
	case JSON:
		return true
	case Pdf:
		return true
	default:
		return false
	}
}

// Defines values for ForensicEvidenceQuery402JSONResponseBodyPlan.
const (
	ForensicEvidenceQuery402JSONResponseBodyPlanCloud ForensicEvidenceQuery402JSONResponseBodyPlan = "cloud"
)

// Valid indicates whether the value is a known member of the ForensicEvidenceQuery402JSONResponseBodyPlan enum.
func (e ForensicEvidenceQuery402JSONResponseBodyPlan) Valid() bool {
	switch e {
	case ForensicEvidenceQuery402JSONResponseBodyPlanCloud:
		return true
	default:
		return false
	}
}

// Defines values for ScimListUsers402JSONResponseBodyPlan.
const (
	ScimListUsers402JSONResponseBodyPlanCloud ScimListUsers402JSONResponseBodyPlan = "cloud"
)

// Valid indicates whether the value is a known member of the ScimListUsers402JSONResponseBodyPlan enum.
func (e ScimListUsers402JSONResponseBodyPlan) Valid() bool {
	switch e {
	case ScimListUsers402JSONResponseBodyPlanCloud:
		return true
	default:
		return false
	}
}

// Defines values for ScimCreateUser402JSONResponseBodyPlan.
const (
	ScimCreateUser402JSONResponseBodyPlanCloud ScimCreateUser402JSONResponseBodyPlan = "cloud"
)

// Valid indicates whether the value is a known member of the ScimCreateUser402JSONResponseBodyPlan enum.
func (e ScimCreateUser402JSONResponseBodyPlan) Valid() bool {
	switch e {
	case ScimCreateUser402JSONResponseBodyPlanCloud:
		return true
	default:
		return false
	}
}

// APIError defines model for ApiError.
type APIError struct {
	// Error Human-readable error message.
	Error string `json:"error"`

	// Issues Field-level validation issues (present on 400 responses).
	Issues *[]struct {
		Message *string `json:"message,omitempty"`
		Path    *string `json:"path,omitempty"`
	} `json:"issues,omitempty"`
	Meta APIMeta `json:"meta"`
}

// APIMeta defines model for ApiMeta.
type APIMeta struct {
	// TraceID Correlation ID echoed from X-Request-ID or generated server-side.
	//
	// Examples: req_01j1x2y3z4
	TraceID string `json:"traceId"`

	// TS ISO timestamp of the response.
	TS time.Time `json:"ts"`

	// Version API version string.
	//
	// Examples: 2026-01
	Version string `json:"version"`
}

// ApprovalResponse defines model for ApprovalResponse.
type ApprovalResponse struct {
	// Approval The approval record for the requested revision.
	Approval map[string]interface{} `json:"approval"`
	Meta     APIMeta                `json:"meta"`
}

// BlueprintImportRequest defines model for BlueprintImportRequest.
type BlueprintImportRequest struct {
	// Source The raw declarative Blueprint source document (YAML or JSON): an envelope of name, agentId, message, and definition. The definition names its governing policy branch via policyBranchId (a branch name) and must not pin policyRevisionId.
	Source string `json:"source"`

	// SourcePath Provenance path recorded with the revision.
	SourcePath *string `json:"sourcePath,omitempty"`
}

// BlueprintImportResponse defines model for BlueprintImportResponse.
type BlueprintImportResponse struct {
	// AlreadyCurrent True when a revision with this exact bound definition already existed; no write was performed.
	AlreadyCurrent bool   `json:"alreadyCurrent"`
	BlueprintID    string `json:"blueprintId"`

	// Created True when a brand-new Blueprint was created (HTTP 201).
	Created bool `json:"created"`

	// DefinitionHash SHA-256 of the bound Blueprint definition.
	DefinitionHash string  `json:"definitionHash"`
	Meta           APIMeta `json:"meta"`

	// PolicyBranchID Resolved id of the governing policy branch.
	PolicyBranchID string `json:"policyBranchId"`

	// PolicyRevisionID Resolved id of the branch's published revision the Blueprint is bound to.
	PolicyRevisionID string `json:"policyRevisionId"`
	RevisionID       string `json:"revisionId"`
}

// BundleExportBlockedResponse defines model for BundleExportBlockedResponse.
type BundleExportBlockedResponse struct {
	Error    string               `json:"error"`
	Manifest BundleExportManifest `json:"manifest"`
	Meta     APIMeta              `json:"meta"`
}

// BundleExportEnvelope defines model for BundleExportEnvelope.
type BundleExportEnvelope struct {
	// Artifact Target artifact. String for text formats, object for JSON/bundle formats.
	Artifact BundleExportEnvelope_Artifact `json:"artifact"`
	Manifest BundleExportManifest          `json:"manifest"`
	Meta     APIMeta                       `json:"meta"`
}

// BundleExportEnvelopeArtifact0 defines model for BundleExportEnvelope.Artifact.0.
type BundleExportEnvelopeArtifact0 = string

// BundleExportEnvelopeArtifact1 defines model for BundleExportEnvelope.Artifact.1.
type BundleExportEnvelopeArtifact1 map[string]interface{}

// BundleExportEnvelope_Artifact Target artifact. String for text formats, object for JSON/bundle formats.
type BundleExportEnvelope_Artifact struct {
	union json.RawMessage
}

// BundleExportFormat defines model for BundleExportFormat.
type BundleExportFormat string

// BundleExportManifest defines model for BundleExportManifest.
type BundleExportManifest struct {
	ArtifactHash         string                                 `json:"artifactHash"`
	BlockingWarnings     []string                               `json:"blockingWarnings"`
	CompatibilityLevel   BundleExportManifestCompatibilityLevel `json:"compatibilityLevel"`
	CompiledArtifactHash string                                 `json:"compiledArtifactHash"`
	Format               BundleExportFormat                     `json:"format"`
	GeneratedAt          time.Time                              `json:"generatedAt"`
	Provenance           struct {
		BranchID     string                   `json:"branchId"`
		RevisionID   string                   `json:"revisionId"`
		SourceFormat string                   `json:"sourceFormat"`
		SourceHash   string                   `json:"sourceHash"`
		SourcePath   *string                  `json:"sourcePath,omitempty"`
		TargetStacks []map[string]interface{} `json:"targetStacks"`
		TenantID     string                   `json:"tenantId"`
		WorkspaceID  string                   `json:"workspaceId"`
	} `json:"provenance"`
	RuleCount           int      `json:"ruleCount"`
	SemanticWarnings    []string `json:"semanticWarnings"`
	Target              string   `json:"target"`
	VerificationTargets []string `json:"verificationTargets"`
}

// BundleExportManifestCompatibilityLevel defines model for BundleExportManifest.CompatibilityLevel.
type BundleExportManifestCompatibilityLevel string

// BundleExportPreviewResponse defines model for BundleExportPreviewResponse.
type BundleExportPreviewResponse struct {
	Formats []BundleExportManifest `json:"formats"`
	Meta    APIMeta                `json:"meta"`
}

// BundleExportVerification defines model for BundleExportVerification.
type BundleExportVerification struct {
	ActualHash   string   `json:"actualHash"`
	ExpectedHash string   `json:"expectedHash"`
	Issues       []string `json:"issues"`
	Ok           bool     `json:"ok"`
}

// BundleExportVerificationFailedResponse defines model for BundleExportVerificationFailedResponse.
type BundleExportVerificationFailedResponse struct {
	Error        string                   `json:"error"`
	Manifest     BundleExportManifest     `json:"manifest"`
	Meta         APIMeta                  `json:"meta"`
	Verification BundleExportVerification `json:"verification"`
}

// BundleResponse The latest published policy bundle for the workspace. Response headers carry `x-spctre-branch-id`, `x-spctre-revision-id`, `x-spctre-artifact-hash`, and `x-spctre-published-at`.
type BundleResponse map[string]interface{}

// ComplianceExportResponse defines model for ComplianceExportResponse.
type ComplianceExportResponse struct {
	Approvals           *[]map[string]interface{} `json:"approvals,omitempty"`
	Artifact            map[string]interface{}    `json:"artifact"`
	Escalations         []map[string]interface{}  `json:"escalations"`
	ExportedAt          time.Time                 `json:"exportedAt"`
	FrameworkAnnotation map[string]interface{}    `json:"frameworkAnnotation"`
	RetentionPlan       map[string]interface{}    `json:"retentionPlan"`

	// SchemaVersion Examples: spctre/v1
	SchemaVersion string `json:"schemaVersion"`
	Summary       struct {
		ApprovalCount           *int      `json:"approvalCount,omitempty"`
		DeniedDecisionCount     *int      `json:"deniedDecisionCount,omitempty"`
		EvidenceCount           *int      `json:"evidenceCount,omitempty"`
		PackageSections         *[]string `json:"packageSections,omitempty"`
		PolicyRefCount          *int      `json:"policyRefCount,omitempty"`
		ResolvedEscalationCount *int      `json:"resolvedEscalationCount,omitempty"`
		SimulationEventCount    *int      `json:"simulationEventCount,omitempty"`
		WarnedDecisionCount     *int      `json:"warnedDecisionCount,omitempty"`
	} `json:"summary"`
	Timeline            *[]map[string]interface{} `json:"timeline,omitempty"`
	VerificationResults map[string]interface{}    `json:"verificationResults"`
}

// ContextBudgetIngestRequest defines model for ContextBudgetIngestRequest.
type ContextBudgetIngestRequest struct {
	AgentID           string                                      `json:"agentId"`
	BudgetLimit       *int                                        `json:"budgetLimit,omitempty"`
	BudgetUtilization *float32                                    `json:"budgetUtilization,omitempty"`
	ContextSourceMix  *map[string]interface{}                     `json:"contextSourceMix,omitempty"`
	Environment       string                                      `json:"environment"`
	EventType         ContextBudgetIngestRequestEventType         `json:"eventType"`
	GovernanceAction  *ContextBudgetIngestRequestGovernanceAction `json:"governanceAction,omitempty"`
	PolicyRef         *string                                     `json:"policyRef,omitempty"`
	RuntimeStack      RuntimeStack                                `json:"runtimeStack"`
	SessionID         string                                      `json:"sessionId"`
	TokenCount        int                                         `json:"tokenCount"`
	TokenDelta        *int                                        `json:"tokenDelta,omitempty"`
}

// ContextBudgetIngestRequestEventType defines model for ContextBudgetIngestRequest.EventType.
type ContextBudgetIngestRequestEventType string

// ContextBudgetIngestRequestGovernanceAction defines model for ContextBudgetIngestRequest.GovernanceAction.
type ContextBudgetIngestRequestGovernanceAction string

// CredentialGrant defines model for CredentialGrant.
type CredentialGrant struct {
	CredentialType    string    `json:"credentialType"`
	CredentialValue   string    `json:"credentialValue"`
	ExpiresAt         time.Time `json:"expiresAt"`
	InjectedParameter string    `json:"injectedParameter"`
}

// EscalationQueueItem An open escalation queue item awaiting human review.
type EscalationQueueItem struct {
	AgentGuidance     *string    `json:"agentGuidance,omitempty"`
	CreatedAt         *time.Time `json:"createdAt,omitempty"`
	DecisionID        *string    `json:"decisionId,omitempty"`
	ID                *string    `json:"id,omitempty"`
	Outcome           *string    `json:"outcome,omitempty"`
	ResolutionOutcome *string    `json:"resolutionOutcome,omitempty"`
	ResolvedAt        *time.Time `json:"resolvedAt,omitempty"`
	RiskLevel         *string    `json:"riskLevel,omitempty"`
	SLADeadlineAt     *time.Time `json:"slaDeadlineAt,omitempty"`
}

// EscalationStatusResponse defines model for EscalationStatusResponse.
type EscalationStatusResponse struct {
	AgentGuidance *string `json:"agentGuidance,omitempty"`

	// ApprovedToolParameters Confirmation of the decision arguments a human reviewed — not an execution source. Sensitive keys are redacted and depth/size are bounded when the decision is recorded, so this is a lossy snapshot: execute from your own parameters and use this to confirm they match what was approved. Present only when the escalation is RESOLVED with a PROCEED outcome.
	ApprovedToolParameters *map[string]interface{}                    `json:"approvedToolParameters,omitempty"`
	CredentialGrant        *CredentialGrant                           `json:"credentialGrant,omitempty"`
	DecisionID             string                                     `json:"decisionId"`
	Meta                   APIMeta                                    `json:"meta"`
	ResolutionNote         *string                                    `json:"resolutionNote,omitempty"`
	ResolutionOutcome      *EscalationStatusResponseResolutionOutcome `json:"resolutionOutcome,omitempty"`
	ResolvedAt             *time.Time                                 `json:"resolvedAt,omitempty"`
	SLADueAt               *time.Time                                 `json:"slaDueAt,omitempty"`
	Status                 EscalationStatusResponseStatus             `json:"status"`
}

// EscalationStatusResponseResolutionOutcome defines model for EscalationStatusResponse.ResolutionOutcome.
type EscalationStatusResponseResolutionOutcome string

// EscalationStatusResponseStatus defines model for EscalationStatusResponse.Status.
type EscalationStatusResponseStatus string

// EvaluateRequest defines model for EvaluateRequest.
type EvaluateRequest struct {
	Action    string `json:"action"`
	Connector string `json:"connector"`

	// Domains Optional domain tags used for additional policy matching.
	Domains *[]string `json:"domains,omitempty"`

	// PlanSummary A high-level plan summary explicitly provided by the runtime.
	PlanSummary *string `json:"planSummary,omitempty"`

	// ToolIntent The explicitly declared intent or purpose of the tool call.
	ToolIntent *string `json:"toolIntent,omitempty"`

	// ToolParameters The structured arguments passed to the tool.
	ToolParameters *map[string]interface{} `json:"toolParameters,omitempty"`
}

// EvaluateResponse defines model for EvaluateResponse.
type EvaluateResponse struct {
	Action       string     `json:"action"`
	ArtifactHash *string    `json:"artifactHash,omitempty"`
	BranchID     *string    `json:"branchId,omitempty"`
	Connector    string     `json:"connector"`
	Domains      *[]string  `json:"domains,omitempty"`
	Meta         APIMeta    `json:"meta"`
	PublishedAt  *time.Time `json:"publishedAt,omitempty"`

	// Result Policy evaluation result from the published bundle.
	Result     map[string]interface{} `json:"result"`
	RevisionID *string                `json:"revisionId,omitempty"`
}

// EvidenceIngestRequest defines model for EvidenceIngestRequest.
type EvidenceIngestRequest struct {
	Action    string   `json:"action"`
	AgentID   string   `json:"agentId"`
	AmountUsd *float32 `json:"amountUsd,omitempty"`

	// ArtifactHash SHA-256 hash of the policy bundle artifact. Required in standard mode.
	ArtifactHash *string `json:"artifactHash,omitempty"`

	// CatalogProvider Catalog or skill provenance provider (e.g. Paperclip catalog-provenance identifier).
	CatalogProvider *string  `json:"catalogProvider,omitempty"`
	Confidence      *float32 `json:"confidence,omitempty"`
	Connector       string   `json:"connector"`
	Consequence     *string  `json:"consequence,omitempty"`
	ContextBudget   *int     `json:"contextBudget,omitempty"`

	// CreatedAt Decision timestamp. Defaults to server time when omitted.
	CreatedAt       *time.Time `json:"createdAt,omitempty"`
	CustomerTier    *string    `json:"customerTier,omitempty"`
	DataSensitivity *string    `json:"dataSensitivity,omitempty"`

	// DecisionID Unique ID for this governance decision (idempotency key).
	DecisionID    string  `json:"decisionId"`
	EngineVersion *string `json:"engineVersion,omitempty"`
	Environment   string  `json:"environment"`

	// ExecutionContext Execution surface identity plus sandbox/inference-router evidence references.
	ExecutionContext *EvidenceIngestRequest_ExecutionContext `json:"executionContext,omitempty"`

	// ExecutionTrace Execution trace for forensic replay.
	ExecutionTrace interface{} `json:"executionTrace,omitempty"`

	// IngestMode Use 'gateway' when posting from a gateway adapter; the server resolves policyRefs, artifactHash, and policyContext automatically.
	IngestMode *EvidenceIngestRequestIngestMode `json:"ingestMode,omitempty"`
	LatencyMs  *int                             `json:"latencyMs,omitempty"`

	// Layer Whether the evidence record originates from the agent layer (L7 tool calls) or sandbox layer (L3/L4 network policy).
	Layer *EvidenceLayer `json:"layer,omitempty"`

	// OrchestratorRef Orchestrator-platform reference (e.g. Paperclip companyId, issueId, goalId).
	OrchestratorRef *EvidenceIngestRequest_OrchestratorRef `json:"orchestratorRef,omitempty"`

	// ParentAgentID Agent ID of the parent when this evidence originates from a subagent.
	ParentAgentID *string `json:"parentAgentId,omitempty"`

	// PlanSummary A high-level plan summary explicitly provided by the runtime.
	PlanSummary *string `json:"planSummary,omitempty"`

	// PluginSource Plugin provenance dimension.
	PluginSource *EvidenceIngestRequestPluginSource `json:"pluginSource,omitempty"`

	// PolicyContext Required in standard mode; server resolves it in gateway mode.
	PolicyContext *[]RuntimePolicyContext `json:"policyContext,omitempty"`

	// PolicyRefs Required when ingestMode is omitted or 'standard'. Omit only when ingestMode is 'gateway'.
	PolicyRefs *[]string `json:"policyRefs,omitempty"`

	// RawEvidence Arbitrary key-value metadata attached to the evidence record.
	RawEvidence   *map[string]interface{} `json:"rawEvidence,omitempty"`
	Reason        string                  `json:"reason"`
	RuntimeTarget RuntimeTarget           `json:"runtimeTarget"`

	// SkillContext Prompt-level governance surface: active skills, instruction files, and prompt policy refs present when the decision was made.
	SkillContext *EvidenceIngestRequest_SkillContext `json:"skillContext,omitempty"`
	SourceType   *string                             `json:"sourceType,omitempty"`
	Status       RuntimeDecisionStatus               `json:"status"`

	// TenantID Optional tenant boundary hint. Empty string is treated as omitted. The x-spctre-tenant-id header takes precedence when both are present; otherwise inferred from the bearer token when omitted.
	TenantID *string `json:"tenantId,omitempty"`

	// ToolIntent The explicitly declared intent or purpose of the tool call.
	ToolIntent *string `json:"toolIntent,omitempty"`

	// ToolParameters The structured arguments passed to the tool.
	ToolParameters *map[string]interface{} `json:"toolParameters,omitempty"`

	// TraceID Distributed trace identifier linking related agent decisions across subagents.
	TraceID *string `json:"traceId,omitempty"`

	// TriggerKind The invocation origin of the agent tool call.
	TriggerKind *TriggerKind `json:"triggerKind,omitempty"`

	// TrustLevel Trust level assigned by the orchestration platform (e.g. Paperclip trust preset).
	TrustLevel *string  `json:"trustLevel,omitempty"`
	TrustScore *float32 `json:"trustScore,omitempty"`

	// WebhookSource Source identifier for inbound webhook triggers (present when triggerKind is inbound_webhook).
	WebhookSource *string `json:"webhookSource,omitempty"`

	// WorkspaceID Optional workspace boundary hint. Empty string is treated as omitted. The x-spctre-workspace-id header takes precedence when both are present; otherwise inferred from the bearer token when omitted.
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// EvidenceIngestRequest_ExecutionContext Execution surface identity plus sandbox/inference-router evidence references.
type EvidenceIngestRequest_ExecutionContext struct {
	Backend              *string                `json:"backend,omitempty"`
	InferenceProvider    *string                `json:"inferenceProvider,omitempty"`
	InferenceRouterRef   *string                `json:"inferenceRouterRef,omitempty"`
	SandboxName          *string                `json:"sandboxName,omitempty"`
	SandboxPolicyRef     *string                `json:"sandboxPolicyRef,omitempty"`
	SessionID            *string                `json:"sessionId,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// EvidenceIngestRequestIngestMode Use 'gateway' when posting from a gateway adapter; the server resolves policyRefs, artifactHash, and policyContext automatically.
type EvidenceIngestRequestIngestMode string

// EvidenceIngestRequest_OrchestratorRef Orchestrator-platform reference (e.g. Paperclip companyId, issueId, goalId).
type EvidenceIngestRequest_OrchestratorRef struct {
	CompanyID            *string                `json:"companyId,omitempty"`
	GoalID               *string                `json:"goalId,omitempty"`
	IssueID              *string                `json:"issueId,omitempty"`
	Platform             string                 `json:"platform"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// EvidenceIngestRequestPluginSource Plugin provenance dimension.
type EvidenceIngestRequestPluginSource string

// EvidenceIngestRequest_SkillContext Prompt-level governance surface: active skills, instruction files, and prompt policy refs present when the decision was made.
type EvidenceIngestRequest_SkillContext struct {
	ActiveSkills         *[]string              `json:"activeSkills,omitempty"`
	InstructionFiles     *[]string              `json:"instructionFiles,omitempty"`
	PromptPolicyRefs     *[]string              `json:"promptPolicyRefs,omitempty"`
	PromptSurface        *string                `json:"promptSurface,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// EvidenceIngestResponse defines model for EvidenceIngestResponse.
type EvidenceIngestResponse struct {
	// Deduplicated True when a record with the same decisionId already exists (200 response).
	Deduplicated *bool `json:"deduplicated,omitempty"`

	// Evidence The persisted evidence record (canonical shape).
	Evidence map[string]interface{} `json:"evidence"`

	// Gateway Gateway evaluation result, if the gateway is enabled.
	Gateway *struct {
		Outcome     *EvidenceIngestResponseGatewayOutcome   `json:"outcome,omitempty"`
		Reason      *string                                 `json:"reason,omitempty"`
		RiskLevel   *EvidenceIngestResponseGatewayRiskLevel `json:"riskLevel,omitempty"`
		ShouldQueue *bool                                   `json:"shouldQueue,omitempty"`
	} `json:"gateway,omitempty"`
	Meta APIMeta `json:"meta"`
}

// EvidenceIngestResponseGatewayOutcome defines model for EvidenceIngestResponse.Gateway.Outcome.
type EvidenceIngestResponseGatewayOutcome string

// EvidenceIngestResponseGatewayRiskLevel defines model for EvidenceIngestResponse.Gateway.RiskLevel.
type EvidenceIngestResponseGatewayRiskLevel string

// EvidenceLayer Whether the evidence record originates from the agent layer (L7 tool calls) or sandbox layer (L3/L4 network policy).
type EvidenceLayer string

// GatewayDecision defines model for GatewayDecision.
type GatewayDecision struct {
	CredentialGrant *CredentialGrant         `json:"credentialGrant,omitempty"`
	Outcome         GatewayDecisionOutcome   `json:"outcome"`
	Reason          string                   `json:"reason"`
	RiskLevel       GatewayDecisionRiskLevel `json:"riskLevel"`
	ShouldQueue     bool                     `json:"shouldQueue"`
	SLAHours        *int                     `json:"slaHours,omitempty"`
}

// GatewayDecisionOutcome defines model for GatewayDecision.Outcome.
type GatewayDecisionOutcome string

// GatewayDecisionRiskLevel defines model for GatewayDecision.RiskLevel.
type GatewayDecisionRiskLevel string

// GatewayDecisionRequest defines model for GatewayDecisionRequest.
type GatewayDecisionRequest struct {
	Action *string `json:"action,omitempty"`

	// AgentID Runtime agent identity used to link this decision to cross-surface evidence and governance history.
	AgentID         *string  `json:"agentId,omitempty"`
	AmountUsd       *float32 `json:"amountUsd,omitempty"`
	ArtifactHash    string   `json:"artifactHash"`
	Confidence      *float32 `json:"confidence,omitempty"`
	Connector       *string  `json:"connector,omitempty"`
	Consequence     *string  `json:"consequence,omitempty"`
	ContextBudget   *int     `json:"contextBudget,omitempty"`
	CustomerTier    *string  `json:"customerTier,omitempty"`
	DataSensitivity *string  `json:"dataSensitivity,omitempty"`
	DecisionID      string   `json:"decisionId"`

	// PlanSummary A high-level plan summary explicitly provided by the runtime.
	PlanSummary   *string                          `json:"planSummary,omitempty"`
	PolicyContext []RuntimePolicyContext           `json:"policyContext"`
	Reason        *string                          `json:"reason,omitempty"`
	RiskLevel     *GatewayDecisionRequestRiskLevel `json:"riskLevel,omitempty"`

	// SessionID Stable runtime session identifier used for Blueprint loop safeguards.
	SessionID *string `json:"sessionId,omitempty"`

	// TenantID Optional tenant boundary hint. Empty string is treated as omitted. The x-spctre-tenant-id header takes precedence when both are present; otherwise inferred from the bearer token when omitted.
	TenantID *string `json:"tenantId,omitempty"`

	// ToolIntent The explicitly declared intent or purpose of the tool call.
	ToolIntent *string `json:"toolIntent,omitempty"`

	// ToolParameters The structured arguments passed to the tool.
	ToolParameters *map[string]interface{} `json:"toolParameters,omitempty"`
	TrustScore     *float32                `json:"trustScore,omitempty"`

	// WorkspaceID Optional workspace boundary hint. Empty string is treated as omitted. The x-spctre-workspace-id header takes precedence when both are present; otherwise inferred from the bearer token when omitted.
	WorkspaceID *string `json:"workspaceId,omitempty"`
}

// GatewayDecisionRequestRiskLevel defines model for GatewayDecisionRequest.RiskLevel.
type GatewayDecisionRequestRiskLevel string

// GatewayDecisionResponse defines model for GatewayDecisionResponse.
type GatewayDecisionResponse struct {
	Decision       GatewayDecision `json:"decision"`
	GatewayEnabled bool            `json:"gatewayEnabled"`
	Meta           APIMeta         `json:"meta"`
	Mode           string          `json:"mode"`
	Persisted      bool            `json:"persisted"`
	Queued         bool            `json:"queued"`
}

// GatewayIngestResponse defines model for GatewayIngestResponse.
type GatewayIngestResponse struct {
	DecisionID string `json:"decisionId"`

	// Deduplicated True when the provider event was already ingested.
	Deduplicated bool    `json:"deduplicated"`
	Meta         APIMeta `json:"meta"`

	// ProvenanceGap True when Spctre could not fully link the gateway event to a published policy revision or connector mapping.
	ProvenanceGap bool `json:"provenanceGap"`
}

// GatewayResolveRequest defines model for GatewayResolveRequest.
type GatewayResolveRequest struct {
	AgentGuidance     *string                                `json:"agentGuidance,omitempty"`
	QueueID           string                                 `json:"queueId"`
	ResolutionNote    *string                                `json:"resolutionNote,omitempty"`
	ResolutionOutcome GatewayResolveRequestResolutionOutcome `json:"resolutionOutcome"`
}

// GatewayResolveRequestResolutionOutcome defines model for GatewayResolveRequest.ResolutionOutcome.
type GatewayResolveRequestResolutionOutcome string

// GatewayWebhookRequest Raw provider webhook payload from Portkey, Helicone, or LiteLLM. Spctre normalizes provider-specific fields into runtime evidence.
type GatewayWebhookRequest map[string]interface{}

// GitCheckpointIngestRequest Framework-agnostic Git checkpoint and diff evidence. Clients submit normalized Git facts; the server does not execute Git or access a caller repository.
type GitCheckpointIngestRequest struct {
	// Action Optional action label; defaults to checkpoint.ingest.
	Action *string `json:"action,omitempty"`
	Agent  *struct {
		Adapter *string `json:"adapter,omitempty"`
		ID      *string `json:"id,omitempty"`
	} `json:"agent,omitempty"`
	Checkpoint struct {
		BaseCommit *string   `json:"baseCommit,omitempty"`
		CreatedAt  time.Time `json:"createdAt"`
		Diff       struct {
			Content *string `json:"content,omitempty"`
			Files   *[]struct {
				Path         string                                               `json:"path"`
				PreviousPath *string                                              `json:"previousPath,omitempty"`
				Status       *GitCheckpointIngestRequestCheckpointDiffFilesStatus `json:"status,omitempty"`
			} `json:"files,omitempty"`
			Format GitCheckpointIngestRequestCheckpointDiffFormat `json:"format"`
			Sha256 *string                                        `json:"sha256,omitempty"`
		} `json:"diff"`
		HeadCommit string  `json:"headCommit"`
		ID         string  `json:"id"`
		Ref        *string `json:"ref,omitempty"`
		Repository struct {
			ID        string  `json:"id"`
			RemoteURL *string `json:"remoteUrl,omitempty"`
		} `json:"repository"`
	} `json:"checkpoint"`

	// Connector Optional client connector label; defaults to git.
	Connector   *string `json:"connector,omitempty"`
	Environment string  `json:"environment"`

	// IdempotencyKey Stable checkpoint submission key. Reuse it to safely retry.
	IdempotencyKey string                  `json:"idempotencyKey"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`

	// PolicyRefs Caller-supplied references retained as metadata. Policy context is resolved server-side.
	PolicyRefs *[]string             `json:"policyRefs,omitempty"`
	Reason     string                `json:"reason"`
	Status     RuntimeDecisionStatus `json:"status"`
}

// GitCheckpointIngestRequestCheckpointDiffFilesStatus defines model for GitCheckpointIngestRequest.Checkpoint.Diff.Files.Status.
type GitCheckpointIngestRequestCheckpointDiffFilesStatus string

// GitCheckpointIngestRequestCheckpointDiffFormat defines model for GitCheckpointIngestRequest.Checkpoint.Diff.Format.
type GitCheckpointIngestRequestCheckpointDiffFormat string

// Pagination defines model for Pagination.
type Pagination struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
	Total  int `json:"total"`
}

// PolicyImportRequest defines model for PolicyImportRequest.
type PolicyImportRequest struct {
	// BranchName Target branch name. Lowercase letters, digits, hyphens, and slashes; cannot start or end with a hyphen or slash.
	BranchName string `json:"branchName"`

	// Connector Connector id. Required when scope is CONNECTOR.
	Connector *string `json:"connector,omitempty"`

	// Environment Environment. Required when scope is ENVIRONMENT.
	Environment *string `json:"environment,omitempty"`

	// Scope Branch scope. Optional; the server defaults to WORKSPACE when omitted.
	Scope *PolicyImportRequestScope `json:"scope,omitempty"`

	// Source The raw AGT-compatible policy document (YAML or JSON).
	Source string `json:"source"`

	// SourcePath Provenance path recorded with the revision.
	SourcePath *string `json:"sourcePath,omitempty"`

	// TargetStacks Optional AGT-compatible export target stacks recorded with the revision.
	TargetStacks *[]string `json:"targetStacks,omitempty"`
}

// PolicyImportRequestScope Branch scope. Optional; the server defaults to WORKSPACE when omitted.
type PolicyImportRequestScope string

// PolicyImportResponse defines model for PolicyImportResponse.
type PolicyImportResponse struct {
	// AlreadyCurrent True when the branch head already carried this exact source; no write was performed.
	AlreadyCurrent bool   `json:"alreadyCurrent"`
	BranchID       string `json:"branchId"`

	// Created True when a brand-new branch was created (HTTP 201).
	Created    bool    `json:"created"`
	Meta       APIMeta `json:"meta"`
	RevisionID string  `json:"revisionId"`
	RuleCount  int     `json:"ruleCount"`

	// SourceHash SHA-256 (truncated) of the imported source.
	SourceHash string `json:"sourceHash"`
}

// RuntimeDecisionStatus defines model for RuntimeDecisionStatus.
type RuntimeDecisionStatus string

// RuntimePolicyContext defines model for RuntimePolicyContext.
type RuntimePolicyContext struct {
	ArtifactHash string                    `json:"artifactHash"`
	BranchID     string                    `json:"branchId"`
	PackID       *string                   `json:"packId,omitempty"`
	PackOwner    *string                   `json:"packOwner,omitempty"`
	PackVersion  *string                   `json:"packVersion,omitempty"`
	RevisionID   string                    `json:"revisionId"`
	Scope        RuntimePolicyContextScope `json:"scope"`
}

// RuntimePolicyContextScope defines model for RuntimePolicyContext.Scope.
type RuntimePolicyContextScope string

// RuntimeStack defines model for RuntimeStack.
type RuntimeStack string

// RuntimeTarget defines model for RuntimeTarget.
type RuntimeTarget struct {
	// Adapter Specific adapter within the stack.
	Adapter     *string `json:"adapter,omitempty"`
	Environment *string `json:"environment,omitempty"`

	// InferenceProvider Inference router/provider identifier for model-routing policy and evidence queries.
	InferenceProvider *string `json:"inferenceProvider,omitempty"`

	// SandboxName Runtime sandbox/deployment name for sandbox-layer policy and evidence queries.
	SandboxName *string      `json:"sandboxName,omitempty"`
	Stack       RuntimeStack `json:"stack"`
}

// TokenRefreshRequest defines model for TokenRefreshRequest.
type TokenRefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// TokenRefreshResponse defines model for TokenRefreshResponse.
type TokenRefreshResponse struct {
	AccessToken           string    `json:"accessToken"`
	AccessTokenExpiresAt  time.Time `json:"accessTokenExpiresAt"`
	Meta                  APIMeta   `json:"meta"`
	RefreshToken          string    `json:"refreshToken"`
	RefreshTokenExpiresAt time.Time `json:"refreshTokenExpiresAt"`
}

// TriggerKind The invocation origin of the agent tool call.
type TriggerKind string

// TrustEvaluateRequest defines model for TrustEvaluateRequest.
type TrustEvaluateRequest struct {
	AgentClass      *string                              `json:"agentClass,omitempty"`
	AgentID         *string                              `json:"agentId,omitempty"`
	BudgetLimit     *int                                 `json:"budgetLimit,omitempty"`
	Connector       *string                              `json:"connector,omitempty"`
	ConsequenceTier *TrustEvaluateRequestConsequenceTier `json:"consequenceTier,omitempty"`
	ContextTokens   *int                                 `json:"contextTokens,omitempty"`
	Environment     *string                              `json:"environment,omitempty"`
	RuntimeStack    *RuntimeStack                        `json:"runtimeStack,omitempty"`
	SessionID       *string                              `json:"sessionId,omitempty"`
	TrustScore      *float32                             `json:"trustScore,omitempty"`
}

// TrustEvaluateRequestConsequenceTier defines model for TrustEvaluateRequest.ConsequenceTier.
type TrustEvaluateRequestConsequenceTier string

// TrustScoreIngestRequest defines model for TrustScoreIngestRequest.
type TrustScoreIngestRequest struct {
	AgentID      string                        `json:"agentId"`
	Environment  string                        `json:"environment"`
	Reason       *string                       `json:"reason,omitempty"`
	RuntimeStack RuntimeStack                  `json:"runtimeStack"`
	Source       TrustScoreIngestRequestSource `json:"source"`
	SourceRef    *string                       `json:"sourceRef,omitempty"`
	TrustScore   float32                       `json:"trustScore"`
}

// TrustScoreIngestRequestSource defines model for TrustScoreIngestRequest.Source.
type TrustScoreIngestRequestSource string

// VerificationIngestRequest defines model for VerificationIngestRequest.
type VerificationIngestRequest struct {
	AgtPoliciesVersion        *string                                             `json:"agtPoliciesVersion,omitempty"`
	AgtVersion                *string                                             `json:"agtVersion,omitempty"`
	ApproverDid               *string                                             `json:"approverDid,omitempty"`
	ArgumentsHash             *string                                             `json:"argumentsHash,omitempty"`
	ArtifactHash              string                                              `json:"artifactHash"`
	CedarPolicyVersion        *string                                             `json:"cedarPolicyVersion,omitempty"`
	CompatibilityCheckOutcome *VerificationIngestRequestCompatibilityCheckOutcome `json:"compatibilityCheckOutcome,omitempty"`
	CompatibilityCheckedAt    *time.Time                                          `json:"compatibilityCheckedAt,omitempty"`
	CompletedAt               *time.Time                                          `json:"completedAt,omitempty"`
	EscrowKeyID               *string                                             `json:"escrowKeyId,omitempty"`
	EscrowSignature           *string                                             `json:"escrowSignature,omitempty"`
	EscrowSignerID            *string                                             `json:"escrowSignerId,omitempty"`
	EscrowVerificationOutcome *VerificationIngestRequestEscrowVerificationOutcome `json:"escrowVerificationOutcome,omitempty"`
	EscrowVerifiedAt          *time.Time                                          `json:"escrowVerifiedAt,omitempty"`
	IssuedAt                  *time.Time                                          `json:"issuedAt,omitempty"`
	Outcome                   VerificationIngestRequestOutcome                    `json:"outcome"`
	OutcomeHash               *string                                             `json:"outcomeHash,omitempty"`
	PolicyEngineVersion       *string                                             `json:"policyEngineVersion,omitempty"`
	PolicyVersion             *string                                             `json:"policyVersion,omitempty"`
	RevisionID                *string                                             `json:"revisionId,omitempty"`
	RuntimeVersion            *string                                             `json:"runtimeVersion,omitempty"`

	// Summary Arbitrary verification summary payload.
	Summary          *map[string]interface{}                   `json:"summary,omitempty"`
	VerificationType VerificationIngestRequestVerificationType `json:"verificationType"`
}

// VerificationIngestRequestCompatibilityCheckOutcome defines model for VerificationIngestRequest.CompatibilityCheckOutcome.
type VerificationIngestRequestCompatibilityCheckOutcome string

// VerificationIngestRequestEscrowVerificationOutcome defines model for VerificationIngestRequest.EscrowVerificationOutcome.
type VerificationIngestRequestEscrowVerificationOutcome string

// VerificationIngestRequestOutcome defines model for VerificationIngestRequest.Outcome.
type VerificationIngestRequestOutcome string

// VerificationIngestRequestVerificationType defines model for VerificationIngestRequest.VerificationType.
type VerificationIngestRequestVerificationType string

// VerificationIngestResponse defines model for VerificationIngestResponse.
type VerificationIngestResponse struct {
	ID      *string                           `json:"id,omitempty"`
	Meta    APIMeta                           `json:"meta"`
	Ok      bool                              `json:"ok"`
	Outcome VerificationIngestResponseOutcome `json:"outcome"`
}

// VerificationIngestResponseOutcome defines model for VerificationIngestResponse.Outcome.
type VerificationIngestResponseOutcome string

// BadRequest defines model for BadRequest.
type BadRequest = APIError

// CloudOnly defines model for CloudOnly.
type CloudOnly struct {
	// Error Human-readable error message.
	Error string `json:"error"`

	// Issues Field-level validation issues (present on 400 responses).
	Issues *[]struct {
		Message *string `json:"message,omitempty"`
		Path    *string `json:"path,omitempty"`
	} `json:"issues,omitempty"`
	Meta APIMeta `json:"meta"`

	// Plan Required plan tier.
	Plan *CloudOnlyPlan `json:"plan,omitempty"`
}

// CloudOnlyPlan Required plan tier.
type CloudOnlyPlan string

// Forbidden defines model for Forbidden.
type Forbidden = APIError

// NotFound defines model for NotFound.
type NotFound = APIError

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = APIError

// Unauthorized defines model for Unauthorized.
type Unauthorized = APIError

// GetBundleLatestParams defines parameters for GetBundleLatest.
type GetBundleLatestParams struct {
	// Format Optional target export format. Omit for the raw AGT-compatible bundle.
	Format *BundleExportFormat `form:"format,omitempty" json:"format,omitempty"`

	// Preview When true and format is omitted, returns manifests for all supported export targets without artifacts.
	Preview *bool `form:"preview,omitempty" json:"preview,omitempty"`
}

// GetBundleLatest200JSONResponseBody defines parameters for GetBundleLatest.
type GetBundleLatest200JSONResponseBody struct {
	union json.RawMessage
}

// ExportComplianceParams defines parameters for ExportCompliance.
type ExportComplianceParams struct {
	// Framework Framework to annotate the export for. When omitted the raw packet is returned without framework-specific annotations.
	Framework *ExportComplianceParamsFramework `form:"framework,omitempty" json:"framework,omitempty"`

	// Format Export format. PDF export is plan-gated.
	Format *ExportComplianceParamsFormat `form:"format,omitempty" json:"format,omitempty"`
}

// ExportComplianceParamsFramework defines parameters for ExportCompliance.
type ExportComplianceParamsFramework string

// ExportComplianceParamsFormat defines parameters for ExportCompliance.
type ExportComplianceParamsFormat string

// ForensicEvidenceQueryParams defines parameters for ForensicEvidenceQuery.
type ForensicEvidenceQueryParams struct {
	// From Start of the time window (inclusive).
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To End of the time window (exclusive).
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Cursor Pagination cursor from a previous response.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ForensicEvidenceQuery402JSONResponseBodyPlan defines parameters for ForensicEvidenceQuery.
type ForensicEvidenceQuery402JSONResponseBodyPlan string

// ListEscalationsParams defines parameters for ListEscalations.
type ListEscalationsParams struct {
	// Limit Maximum number of items to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetEscalationStatusParams defines parameters for GetEscalationStatus.
type GetEscalationStatusParams struct {
	// DecisionID The unique gateway decision ID.
	DecisionID string `form:"decisionId" json:"decisionId"`
}

// ScimListUsersParams defines parameters for ScimListUsers.
type ScimListUsersParams struct {
	Filter     *string `form:"filter,omitempty" json:"filter,omitempty"`
	StartIndex *int    `form:"startIndex,omitempty" json:"startIndex,omitempty"`
	Count      *int    `form:"count,omitempty" json:"count,omitempty"`
}

// ScimListUsers402JSONResponseBodyPlan defines parameters for ScimListUsers.
type ScimListUsers402JSONResponseBodyPlan string

// ScimCreateUserApplicationScimPlusJSONBody defines parameters for ScimCreateUser.
type ScimCreateUserApplicationScimPlusJSONBody = map[string]interface{}

// ScimCreateUser402JSONResponseBodyPlan defines parameters for ScimCreateUser.
type ScimCreateUser402JSONResponseBodyPlan string

// RefreshTokenParams defines parameters for RefreshToken.
type RefreshTokenParams struct {
	// IdempotencyKey Optional client-generated key for retrying a refresh request.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// ListVerificationsParams defines parameters for ListVerifications.
type ListVerificationsParams struct {
	RevisionID   *string `form:"revisionId,omitempty" json:"revisionId,omitempty"`
	ArtifactHash *string `form:"artifactHash,omitempty" json:"artifactHash,omitempty"`
	Limit        *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ImportBlueprintJSONRequestBody defines body for ImportBlueprint for application/json ContentType.
type ImportBlueprintJSONRequestBody = BlueprintImportRequest

// EvaluatePolicyJSONRequestBody defines body for EvaluatePolicy for application/json ContentType.
type EvaluatePolicyJSONRequestBody = EvaluateRequest

// IngestEvidenceJSONRequestBody defines body for IngestEvidence for application/json ContentType.
type IngestEvidenceJSONRequestBody = EvidenceIngestRequest

// IngestGitCheckpointJSONRequestBody defines body for IngestGitCheckpoint for application/json ContentType.
type IngestGitCheckpointJSONRequestBody = GitCheckpointIngestRequest

// IngestHeliconeGatewayEventJSONRequestBody defines body for IngestHeliconeGatewayEvent for application/json ContentType.
type IngestHeliconeGatewayEventJSONRequestBody = GatewayWebhookRequest

// IngestLiteLLMGatewayEventJSONRequestBody defines body for IngestLiteLLMGatewayEvent for application/json ContentType.
type IngestLiteLLMGatewayEventJSONRequestBody = GatewayWebhookRequest

// IngestNotionGatewayEventJSONRequestBody defines body for IngestNotionGatewayEvent for application/json ContentType.
type IngestNotionGatewayEventJSONRequestBody = GatewayWebhookRequest

// IngestPortkeyGatewayEventJSONRequestBody defines body for IngestPortkeyGatewayEvent for application/json ContentType.
type IngestPortkeyGatewayEventJSONRequestBody = GatewayWebhookRequest

// GatewayDecideJSONRequestBody defines body for GatewayDecide for application/json ContentType.
type GatewayDecideJSONRequestBody = GatewayDecisionRequest

// GatewayResolveJSONRequestBody defines body for GatewayResolve for application/json ContentType.
type GatewayResolveJSONRequestBody = GatewayResolveRequest

// ImportPolicyJSONRequestBody defines body for ImportPolicy for application/json ContentType.
type ImportPolicyJSONRequestBody = PolicyImportRequest

// ScimCreateUserApplicationScimPlusJSONRequestBody defines body for ScimCreateUser for application/scim+json ContentType.
type ScimCreateUserApplicationScimPlusJSONRequestBody = ScimCreateUserApplicationScimPlusJSONBody

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = TokenRefreshRequest

// IngestContextBudgetEventJSONRequestBody defines body for IngestContextBudgetEvent for application/json ContentType.
type IngestContextBudgetEventJSONRequestBody = ContextBudgetIngestRequest

// EvaluateTrustGovernanceJSONRequestBody defines body for EvaluateTrustGovernance for application/json ContentType.
type EvaluateTrustGovernanceJSONRequestBody = TrustEvaluateRequest

// IngestTrustScoreJSONRequestBody defines body for IngestTrustScore for application/json ContentType.
type IngestTrustScoreJSONRequestBody = TrustScoreIngestRequest

// IngestVerificationJSONRequestBody defines body for IngestVerification for application/json ContentType.
type IngestVerificationJSONRequestBody = VerificationIngestRequest

// Getter for additional properties for EvidenceIngestRequest_ExecutionContext. Returns the specified
// element and whether it was found
func (a EvidenceIngestRequest_ExecutionContext) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for EvidenceIngestRequest_ExecutionContext
func (a *EvidenceIngestRequest_ExecutionContext) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for EvidenceIngestRequest_ExecutionContext to handle AdditionalProperties
func (a *EvidenceIngestRequest_ExecutionContext) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["backend"]; found {
		err = json.Unmarshal(raw, &a.Backend)
		if err != nil {
			return fmt.Errorf("error reading 'backend': %w", err)
		}
		delete(object, "backend")
	}

	if raw, found := object["inferenceProvider"]; found {
		err = json.Unmarshal(raw, &a.InferenceProvider)
		if err != nil {
			return fmt.Errorf("error reading 'inferenceProvider': %w", err)
		}
		delete(object, "inferenceProvider")
	}

	if raw, found := object["inferenceRouterRef"]; found {
		err = json.Unmarshal(raw, &a.InferenceRouterRef)
		if err != nil {
			return fmt.Errorf("error reading 'inferenceRouterRef': %w", err)
		}
		delete(object, "inferenceRouterRef")
	}

	if raw, found := object["sandboxName"]; found {
		err = json.Unmarshal(raw, &a.SandboxName)
		if err != nil {
			return fmt.Errorf("error reading 'sandboxName': %w", err)
		}
		delete(object, "sandboxName")
	}

	if raw, found := object["sandboxPolicyRef"]; found {
		err = json.Unmarshal(raw, &a.SandboxPolicyRef)
		if err != nil {
			return fmt.Errorf("error reading 'sandboxPolicyRef': %w", err)
		}
		delete(object, "sandboxPolicyRef")
	}

	if raw, found := object["sessionId"]; found {
		err = json.Unmarshal(raw, &a.SessionID)
		if err != nil {
			return fmt.Errorf("error reading 'sessionId': %w", err)
		}
		delete(object, "sessionId")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for EvidenceIngestRequest_ExecutionContext to handle AdditionalProperties
func (a EvidenceIngestRequest_ExecutionContext) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Backend != nil {
		object["backend"], err = json.Marshal(a.Backend)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'backend': %w", err)
		}
	}

	if a.InferenceProvider != nil {
		object["inferenceProvider"], err = json.Marshal(a.InferenceProvider)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'inferenceProvider': %w", err)
		}
	}

	if a.InferenceRouterRef != nil {
		object["inferenceRouterRef"], err = json.Marshal(a.InferenceRouterRef)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'inferenceRouterRef': %w", err)
		}
	}

	if a.SandboxName != nil {
		object["sandboxName"], err = json.Marshal(a.SandboxName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sandboxName': %w", err)
		}
	}

	if a.SandboxPolicyRef != nil {
		object["sandboxPolicyRef"], err = json.Marshal(a.SandboxPolicyRef)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sandboxPolicyRef': %w", err)
		}
	}

	if a.SessionID != nil {
		object["sessionId"], err = json.Marshal(a.SessionID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sessionId': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for EvidenceIngestRequest_OrchestratorRef. Returns the specified
// element and whether it was found
func (a EvidenceIngestRequest_OrchestratorRef) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for EvidenceIngestRequest_OrchestratorRef
func (a *EvidenceIngestRequest_OrchestratorRef) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for EvidenceIngestRequest_OrchestratorRef to handle AdditionalProperties
func (a *EvidenceIngestRequest_OrchestratorRef) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["companyId"]; found {
		err = json.Unmarshal(raw, &a.CompanyID)
		if err != nil {
			return fmt.Errorf("error reading 'companyId': %w", err)
		}
		delete(object, "companyId")
	}

	if raw, found := object["goalId"]; found {
		err = json.Unmarshal(raw, &a.GoalID)
		if err != nil {
			return fmt.Errorf("error reading 'goalId': %w", err)
		}
		delete(object, "goalId")
	}

	if raw, found := object["issueId"]; found {
		err = json.Unmarshal(raw, &a.IssueID)
		if err != nil {
			return fmt.Errorf("error reading 'issueId': %w", err)
		}
		delete(object, "issueId")
	}

	if raw, found := object["platform"]; found {
		err = json.Unmarshal(raw, &a.Platform)
		if err != nil {
			return fmt.Errorf("error reading 'platform': %w", err)
		}
		delete(object, "platform")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for EvidenceIngestRequest_OrchestratorRef to handle AdditionalProperties
func (a EvidenceIngestRequest_OrchestratorRef) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CompanyID != nil {
		object["companyId"], err = json.Marshal(a.CompanyID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'companyId': %w", err)
		}
	}

	if a.GoalID != nil {
		object["goalId"], err = json.Marshal(a.GoalID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'goalId': %w", err)
		}
	}

	if a.IssueID != nil {
		object["issueId"], err = json.Marshal(a.IssueID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'issueId': %w", err)
		}
	}

	object["platform"], err = json.Marshal(a.Platform)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'platform': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for EvidenceIngestRequest_SkillContext. Returns the specified
// element and whether it was found
func (a EvidenceIngestRequest_SkillContext) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for EvidenceIngestRequest_SkillContext
func (a *EvidenceIngestRequest_SkillContext) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for EvidenceIngestRequest_SkillContext to handle AdditionalProperties
func (a *EvidenceIngestRequest_SkillContext) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["activeSkills"]; found {
		err = json.Unmarshal(raw, &a.ActiveSkills)
		if err != nil {
			return fmt.Errorf("error reading 'activeSkills': %w", err)
		}
		delete(object, "activeSkills")
	}

	if raw, found := object["instructionFiles"]; found {
		err = json.Unmarshal(raw, &a.InstructionFiles)
		if err != nil {
			return fmt.Errorf("error reading 'instructionFiles': %w", err)
		}
		delete(object, "instructionFiles")
	}

	if raw, found := object["promptPolicyRefs"]; found {
		err = json.Unmarshal(raw, &a.PromptPolicyRefs)
		if err != nil {
			return fmt.Errorf("error reading 'promptPolicyRefs': %w", err)
		}
		delete(object, "promptPolicyRefs")
	}

	if raw, found := object["promptSurface"]; found {
		err = json.Unmarshal(raw, &a.PromptSurface)
		if err != nil {
			return fmt.Errorf("error reading 'promptSurface': %w", err)
		}
		delete(object, "promptSurface")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for EvidenceIngestRequest_SkillContext to handle AdditionalProperties
func (a EvidenceIngestRequest_SkillContext) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ActiveSkills != nil {
		object["activeSkills"], err = json.Marshal(a.ActiveSkills)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'activeSkills': %w", err)
		}
	}

	if a.InstructionFiles != nil {
		object["instructionFiles"], err = json.Marshal(a.InstructionFiles)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instructionFiles': %w", err)
		}
	}

	if a.PromptPolicyRefs != nil {
		object["promptPolicyRefs"], err = json.Marshal(a.PromptPolicyRefs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'promptPolicyRefs': %w", err)
		}
	}

	if a.PromptSurface != nil {
		object["promptSurface"], err = json.Marshal(a.PromptSurface)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'promptSurface': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsBundleExportEnvelopeArtifact0 returns the union data inside the BundleExportEnvelope_Artifact as a BundleExportEnvelopeArtifact0
func (t BundleExportEnvelope_Artifact) AsBundleExportEnvelopeArtifact0() (BundleExportEnvelopeArtifact0, error) {
	var body BundleExportEnvelopeArtifact0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBundleExportEnvelopeArtifact0 overwrites any union data inside the BundleExportEnvelope_Artifact as the provided BundleExportEnvelopeArtifact0
func (t *BundleExportEnvelope_Artifact) FromBundleExportEnvelopeArtifact0(v BundleExportEnvelopeArtifact0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBundleExportEnvelopeArtifact0 performs a merge with any union data inside the BundleExportEnvelope_Artifact, using the provided BundleExportEnvelopeArtifact0
func (t *BundleExportEnvelope_Artifact) MergeBundleExportEnvelopeArtifact0(v BundleExportEnvelopeArtifact0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBundleExportEnvelopeArtifact1 returns the union data inside the BundleExportEnvelope_Artifact as a BundleExportEnvelopeArtifact1
func (t BundleExportEnvelope_Artifact) AsBundleExportEnvelopeArtifact1() (BundleExportEnvelopeArtifact1, error) {
	var body BundleExportEnvelopeArtifact1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBundleExportEnvelopeArtifact1 overwrites any union data inside the BundleExportEnvelope_Artifact as the provided BundleExportEnvelopeArtifact1
func (t *BundleExportEnvelope_Artifact) FromBundleExportEnvelopeArtifact1(v BundleExportEnvelopeArtifact1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBundleExportEnvelopeArtifact1 performs a merge with any union data inside the BundleExportEnvelope_Artifact, using the provided BundleExportEnvelopeArtifact1
func (t *BundleExportEnvelope_Artifact) MergeBundleExportEnvelopeArtifact1(v BundleExportEnvelopeArtifact1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BundleExportEnvelope_Artifact) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *BundleExportEnvelope_Artifact) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsBundleResponse returns the union data inside the GetBundleLatest200JSONResponseBody as a BundleResponse
func (t GetBundleLatest200JSONResponseBody) AsBundleResponse() (BundleResponse, error) {
	var body BundleResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBundleResponse overwrites any union data inside the GetBundleLatest200JSONResponseBody as the provided BundleResponse
func (t *GetBundleLatest200JSONResponseBody) FromBundleResponse(v BundleResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBundleResponse performs a merge with any union data inside the GetBundleLatest200JSONResponseBody, using the provided BundleResponse
func (t *GetBundleLatest200JSONResponseBody) MergeBundleResponse(v BundleResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBundleExportEnvelope returns the union data inside the GetBundleLatest200JSONResponseBody as a BundleExportEnvelope
func (t GetBundleLatest200JSONResponseBody) AsBundleExportEnvelope() (BundleExportEnvelope, error) {
	var body BundleExportEnvelope
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBundleExportEnvelope overwrites any union data inside the GetBundleLatest200JSONResponseBody as the provided BundleExportEnvelope
func (t *GetBundleLatest200JSONResponseBody) FromBundleExportEnvelope(v BundleExportEnvelope) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBundleExportEnvelope performs a merge with any union data inside the GetBundleLatest200JSONResponseBody, using the provided BundleExportEnvelope
func (t *GetBundleLatest200JSONResponseBody) MergeBundleExportEnvelope(v BundleExportEnvelope) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBundleExportPreviewResponse returns the union data inside the GetBundleLatest200JSONResponseBody as a BundleExportPreviewResponse
func (t GetBundleLatest200JSONResponseBody) AsBundleExportPreviewResponse() (BundleExportPreviewResponse, error) {
	var body BundleExportPreviewResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBundleExportPreviewResponse overwrites any union data inside the GetBundleLatest200JSONResponseBody as the provided BundleExportPreviewResponse
func (t *GetBundleLatest200JSONResponseBody) FromBundleExportPreviewResponse(v BundleExportPreviewResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBundleExportPreviewResponse performs a merge with any union data inside the GetBundleLatest200JSONResponseBody, using the provided BundleExportPreviewResponse
func (t *GetBundleLatest200JSONResponseBody) MergeBundleExportPreviewResponse(v BundleExportPreviewResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t GetBundleLatest200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *GetBundleLatest200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
