import type { PolicyPack } from "../types";

// Framework packs are hand-authored because agent frameworks expose different
// failure modes: delegation, recursive execution, tool blast radius, retrieval
// scope, and provenance gaps cannot be represented by generated connector
// templates alone.
export const CREWAI_GOVERNANCE_PACK: PolicyPack = {
  id: "crewai-governance-v1",
  name: "CrewAI Governance Pack",
  connector: "crewai",
  description:
    "Governance rules for agents built with CrewAI. Blocks unapproved delegation to undeclared agents, warns on high-blast-radius tools and runaway crew iteration patterns, applies rate-limit and data sensitivity defaults to tool calls, requires declared consequence tiers for mutating actions, and surfaces provenance gaps when policy context cannot be resolved at call time.",
  riskLevel: "HIGH",
  tags: ["crewai", "multi-agent", "delegation", "tool-calls", "rate-limits", "data-sensitivity", "ai"],
  domains: ["tool-calls", "delegation", "crew-execution", "data", "limits", "provenance"],
  metadata: {
    name: "CrewAI Governance Pack",
    version: "1.0.0",
    connector: "crewai",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "HIGH",
    riskTags: ["multi-agent", "tool-calls", "delegation", "blast-radius"],
    generated: false,
    category: "Framework runtime governance",
    compatibilityTargets: ["AGT_PREVIEW", "CREWAI", "LANGCHAIN", "OPENAI_AGENTS", "AUTOGEN", "CUSTOM"],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-11",
        summary: "Initial pack: delegation block, blast-radius warn, iteration limit warn, rate-limit warn, sensitivity warn, consequence-tier block, and provenance gap rules.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "crewai.delegation.block_unknown_agent",
      title: "Block delegation to CrewAI agents not declared in the workspace registry",
      effect: "DENY",
      domains: ["delegation", "crew-execution"],
      connectors: ["crewai"],
      actions: ["agent.delegate", "agent.transfer", "crew.kickoff_delegated"],
      immutable: true,
    },
    {
      stableRuleId: "crewai.tools.warn_high_blast_radius",
      title: "Warn when CrewAI tool execution involves high-blast-radius file, network, or shell operations",
      effect: "WARN",
      domains: ["tool-calls", "requests"],
      connectors: ["crewai"],
      actions: ["tool.shell", "tool.file_write", "tool.file_delete", "tool.http_request", "tool.browser"],
      immutable: false,
    },
    {
      stableRuleId: "crewai.crew.warn_unbounded_iteration",
      title: "Warn when a crew or task loop runs without a declared max iteration boundary",
      effect: "WARN",
      domains: ["crew-execution", "tool-calls"],
      connectors: ["crewai"],
      actions: ["crew.kickoff", "task.execute", "agent.iterate"],
      immutable: false,
    },
    {
      stableRuleId: "crewai.tools.warn_rate_limit_missing",
      title: "Warn when a CrewAI tool call has no rate-limit budget or throttle policy",
      effect: "WARN",
      domains: ["limits", "tool-calls"],
      connectors: ["crewai"],
      actions: ["tool.call", "tool.invoke", "tool.rate_limit_unset"],
      immutable: false,
    },
    {
      stableRuleId: "crewai.data.warn_sensitivity_unclassified",
      title: "Warn when CrewAI tool input or output lacks a data sensitivity classification",
      effect: "WARN",
      domains: ["data", "tool-calls"],
      connectors: ["crewai"],
      actions: ["tool.call", "tool.output", "data.unclassified"],
      immutable: false,
    },
    {
      stableRuleId: "crewai.tools.require_consequence_tier_for_mutation",
      title: "Require a declared consequence tier before CrewAI tools perform mutating operations",
      effect: "DENY",
      domains: ["tool-calls", "requests"],
      connectors: ["crewai"],
      actions: ["tool.write", "tool.update", "tool.delete", "tool.mutation_without_tier"],
      immutable: true,
    },
    {
      stableRuleId: "crewai.provenance.warn_gap",
      title: "Warn on tool call events where policy context could not be resolved",
      effect: "WARN",
      domains: ["provenance", "tool-calls"],
      connectors: ["crewai"],
      actions: ["tool.invoke", "tool.call", "crew.kickoff"],
      immutable: false,
    },
  ],
};

export const LANGCHAIN_GOVERNANCE_PACK: PolicyPack = {
  id: "langchain-governance-v1",
  name: "LangChain / LangGraph Governance Pack",
  connector: "langchain",
  description:
    "Governance rules for agents built with LangChain or LangGraph. Blocks unapproved shell-level tool execution, warns on high-blast-radius tool categories, flags potentially unbounded recursive chain patterns, guards against unscoped vector store queries in multi-tenant RAG deployments, and surfaces provenance gaps when policy context cannot be resolved at call time.",
  riskLevel: "HIGH",
  tags: ["langchain", "langgraph", "tool-calls", "rag", "ai", "chains", "multi-agent"],
  domains: ["tool-calls", "chains", "retrieval", "requests", "provenance"],
  metadata: {
    name: "LangChain / LangGraph Governance Pack",
    version: "1.0.0",
    connector: "langchain",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "HIGH",
    riskTags: ["tool-calls", "chains", "rag", "blast-radius"],
    generated: false,
    category: "Framework runtime governance",
    compatibilityTargets: ["AGT_PREVIEW", "LANGCHAIN", "CREWAI", "OPENAI_AGENTS", "AUTOGEN", "CUSTOM"],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-11",
        summary: "Initial pack: shell tool block, blast-radius warn, unbounded-recursion warn, unscoped RAG warn, and provenance gap rules.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "langchain.tools.block_unapproved_shell",
      title: "Block shell and system-level tool execution without human-in-the-loop approval",
      effect: "DENY",
      domains: ["tool-calls", "requests"],
      connectors: ["langchain"],
      actions: ["tool.bash", "tool.shell", "tool.terminal", "tool.execute", "tool.run_process"],
      immutable: true,
    },
    {
      stableRuleId: "langchain.tools.warn_high_blast_radius",
      title: "Warn when tool execution involves high-blast-radius file or network operations",
      effect: "WARN",
      domains: ["tool-calls", "requests"],
      connectors: ["langchain"],
      actions: [
        "tool.file_write",
        "tool.file_delete",
        "tool.http_request",
        "tool.computer",
        "tool.browser",
      ],
      immutable: false,
    },
    {
      stableRuleId: "langchain.chains.warn_unbounded_recursion",
      title: "Warn when a chain or agent node invokes itself without a declared stop condition",
      effect: "WARN",
      domains: ["chains", "requests"],
      connectors: ["langchain"],
      actions: ["chain.self_call", "agent.recursive_step", "graph.cycle_detected"],
      immutable: false,
    },
    {
      stableRuleId: "langchain.retrieval.warn_unscoped_vector_query",
      title: "Warn on vector store queries that lack a workspace or tenant scope filter",
      effect: "WARN",
      domains: ["retrieval", "requests"],
      connectors: ["langchain"],
      actions: ["retrieval.vector_search", "retrieval.similarity_search", "retrieval.mmr_search"],
      immutable: false,
    },
    {
      stableRuleId: "langchain.tools.warn_rate_limit_missing",
      title: "Warn when a LangChain or LangGraph tool has no rate-limit budget or throttle policy",
      effect: "WARN",
      domains: ["limits", "tool-calls"],
      connectors: ["langchain"],
      actions: ["tool.invoke", "tool.ainvoke", "tool.rate_limit_unset"],
      immutable: false,
    },
    {
      stableRuleId: "langchain.data.warn_sensitivity_unclassified",
      title: "Warn when tool input, retrieval output, or chain state lacks a data sensitivity classification",
      effect: "WARN",
      domains: ["data", "retrieval", "tool-calls"],
      connectors: ["langchain"],
      actions: ["tool.invoke", "retrieval.vector_search", "data.unclassified"],
      immutable: false,
    },
    {
      stableRuleId: "langchain.tools.require_consequence_tier_for_mutation",
      title: "Require a declared consequence tier before tools perform mutating operations",
      effect: "DENY",
      domains: ["tool-calls", "requests"],
      connectors: ["langchain"],
      actions: ["tool.file_write", "tool.file_delete", "tool.api_post", "tool.mutation_without_tier"],
      immutable: true,
    },
    {
      stableRuleId: "langchain.provenance.warn_gap",
      title: "Warn on tool call events where policy context could not be resolved",
      effect: "WARN",
      domains: ["provenance", "requests"],
      connectors: ["langchain"],
      actions: ["tool.invoke", "tool.ainvoke", "chain.run"],
      immutable: false,
    },
  ],
};

export const OPENAI_AGENTS_GOVERNANCE_PACK: PolicyPack = {
  id: "openai-agents-governance-v1",
  name: "OpenAI Agents SDK Governance Pack",
  connector: "openai-agents",
  description:
    "Governance rules for agents built with the OpenAI Agents SDK. Blocks unapproved handoffs to unknown agent identities, warns on tool calls that exceed declared output size bounds, flags high-blast-radius tool types, requires human-in-the-loop approval before production data writes, and surfaces provenance gaps when policy context cannot be resolved.",
  riskLevel: "HIGH",
  tags: ["openai", "agents", "tool-calls", "handoffs", "ai", "function-calling"],
  domains: ["tool-calls", "handoffs", "requests", "outputs", "provenance"],
  metadata: {
    name: "OpenAI Agents SDK Governance Pack",
    version: "1.0.0",
    connector: "openai-agents",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "HIGH",
    riskTags: ["tool-calls", "handoffs", "blast-radius", "data-write"],
    generated: false,
    category: "Framework runtime governance",
    compatibilityTargets: ["AGT_PREVIEW", "OPENAI_AGENTS", "LANGCHAIN", "CREWAI", "AUTOGEN", "CUSTOM"],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-11",
        summary: "Initial pack: unknown-agent handoff block, output size warn, blast-radius warn, production write HITL, and provenance gap rules.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "openai-agents.handoffs.block_unknown_agent",
      title: "Block handoffs to agent identities not declared in the workspace agent registry",
      effect: "DENY",
      domains: ["handoffs", "requests"],
      connectors: ["openai-agents"],
      actions: ["agent.handoff", "agent.transfer", "agent.delegate"],
      immutable: true,
    },
    {
      stableRuleId: "openai-agents.tools.warn_high_blast_radius",
      title: "Warn when tool calls involve high-blast-radius system operations",
      effect: "WARN",
      domains: ["tool-calls", "requests"],
      connectors: ["openai-agents"],
      actions: ["tool.bash", "tool.shell", "tool.computer", "tool.file_write", "tool.execute"],
      immutable: false,
    },
    {
      stableRuleId: "openai-agents.outputs.warn_large_tool_output",
      title: "Warn when a tool returns an unusually large output that could inflate downstream context",
      effect: "WARN",
      domains: ["outputs", "requests"],
      connectors: ["openai-agents"],
      actions: ["tool.on_invoke_tool", "function.call"],
      immutable: false,
    },
    {
      stableRuleId: "openai-agents.data.require_hitl_production_write",
      title: "Require human-in-the-loop approval for production data write operations",
      effect: "DENY",
      domains: ["tool-calls", "requests"],
      connectors: ["openai-agents"],
      actions: ["tool.database_write", "tool.file_write", "tool.api_post", "tool.api_put", "tool.api_delete"],
      immutable: true,
    },
    {
      stableRuleId: "openai-agents.tools.warn_rate_limit_missing",
      title: "Warn when an OpenAI Agents tool has no rate-limit budget or throttle policy",
      effect: "WARN",
      domains: ["limits", "tool-calls"],
      connectors: ["openai-agents"],
      actions: ["tool.on_invoke_tool", "function.call", "tool.rate_limit_unset"],
      immutable: false,
    },
    {
      stableRuleId: "openai-agents.data.warn_sensitivity_unclassified",
      title: "Warn when tool inputs, outputs, or handoff context lack a data sensitivity classification",
      effect: "WARN",
      domains: ["data", "outputs", "handoffs"],
      connectors: ["openai-agents"],
      actions: ["tool.on_invoke_tool", "function.call", "data.unclassified"],
      immutable: false,
    },
    {
      stableRuleId: "openai-agents.tools.require_consequence_tier_for_mutation",
      title: "Require a declared consequence tier before tools perform mutating operations",
      effect: "DENY",
      domains: ["tool-calls", "requests"],
      connectors: ["openai-agents"],
      actions: ["tool.database_write", "tool.file_write", "tool.api_delete", "tool.mutation_without_tier"],
      immutable: true,
    },
    {
      stableRuleId: "openai-agents.provenance.warn_gap",
      title: "Warn on tool call events where policy context could not be resolved",
      effect: "WARN",
      domains: ["provenance", "requests"],
      connectors: ["openai-agents"],
      actions: ["tool.on_invoke_tool", "agent.handoff"],
      immutable: false,
    },
  ],
};

export const AUTOGEN_GOVERNANCE_PACK: PolicyPack = {
  id: "autogen-governance-v1",
  name: "AutoGen Governance Pack",
  connector: "autogen",
  description:
    "Governance rules for multi-agent workflows built with AutoGen. Blocks unapproved code execution in sandboxed or Docker environments, warns on group-chat consensus patterns without quorum requirements, flags agents operating without declared termination conditions, and surfaces provenance gaps. Covers both AutoGen v0.2 and v0.4+.",
  riskLevel: "HIGH",
  tags: ["autogen", "multi-agent", "code-execution", "group-chat", "ai", "microsoft"],
  domains: ["code-execution", "group-chat", "tool-calls", "termination", "provenance"],
  metadata: {
    name: "AutoGen Governance Pack",
    version: "1.0.0",
    connector: "autogen",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "HIGH",
    riskTags: ["code-execution", "group-chat", "blast-radius", "termination"],
    generated: false,
    category: "Framework runtime governance",
    compatibilityTargets: ["AGT_PREVIEW", "AUTOGEN", "LANGCHAIN", "OPENAI_AGENTS", "CUSTOM"],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-11",
        summary: "Initial pack: code execution block, group-chat quorum warn, unbounded loop warn, data exfil warn, and provenance gap rules.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "autogen.code.block_unapproved_execution",
      title: "Block unapproved code execution in Docker or shell sandbox environments",
      effect: "DENY",
      domains: ["code-execution", "tool-calls"],
      connectors: ["autogen"],
      actions: ["code.execute", "code.run_in_docker", "shell.execute", "docker.run"],
      immutable: true,
    },
    {
      stableRuleId: "autogen.group_chat.warn_no_quorum",
      title: "Warn on group-chat workflows without a declared minimum speaker or approval quorum",
      effect: "WARN",
      domains: ["group-chat", "tool-calls"],
      connectors: ["autogen"],
      actions: ["group_chat.initiate", "group_chat.send", "group_chat.consensus"],
      immutable: false,
    },
    {
      stableRuleId: "autogen.agents.warn_unbounded_loop",
      title: "Warn when an agent conversation loop lacks a declared max-turn or termination condition",
      effect: "WARN",
      domains: ["termination", "tool-calls"],
      connectors: ["autogen"],
      actions: ["agent.loop", "agent.initiate_chat", "conversation.continue"],
      immutable: false,
    },
    {
      stableRuleId: "autogen.data.warn_exfiltration_pattern",
      title: "Warn when agent function calls include file export or outbound HTTP send patterns",
      effect: "WARN",
      domains: ["code-execution", "tool-calls"],
      connectors: ["autogen"],
      actions: ["tool.file_export", "tool.http_send", "tool.upload", "function.call"],
      immutable: false,
    },
    {
      stableRuleId: "autogen.tools.warn_rate_limit_missing",
      title: "Warn when an AutoGen function tool has no rate-limit budget or throttle policy",
      effect: "WARN",
      domains: ["limits", "tool-calls"],
      connectors: ["autogen"],
      actions: ["tool.execute_function", "tool.run_json", "tool.rate_limit_unset"],
      immutable: false,
    },
    {
      stableRuleId: "autogen.data.warn_sensitivity_unclassified",
      title: "Warn when function-call inputs, outputs, or shared agent memory lack a data sensitivity classification",
      effect: "WARN",
      domains: ["data", "group-chat", "tool-calls"],
      connectors: ["autogen"],
      actions: ["function.call", "tool.run_json", "data.unclassified"],
      immutable: false,
    },
    {
      stableRuleId: "autogen.tools.require_consequence_tier_for_mutation",
      title: "Require a declared consequence tier before AutoGen tools perform mutating operations",
      effect: "DENY",
      domains: ["tool-calls", "code-execution"],
      connectors: ["autogen"],
      actions: ["tool.file_export", "tool.http_send", "code.execute", "tool.mutation_without_tier"],
      immutable: true,
    },
    {
      stableRuleId: "autogen.provenance.warn_gap",
      title: "Warn on tool execution events where policy context could not be resolved",
      effect: "WARN",
      domains: ["provenance", "tool-calls"],
      connectors: ["autogen"],
      actions: ["tool.execute_function", "tool.run_json", "function.call"],
      immutable: false,
    },
  ],
};

export const GOOGLE_ADK_GOVERNANCE_PACK: PolicyPack = {
  id: "google-adk-governance-v1",
  name: "Google ADK Governance Pack",
  connector: "google-adk",
  description:
    "Governance rules for agents built with the Google Agent Development Kit (ADK). Guards against tool calls to non-allowlisted external services, warns on Vertex AI resource access without declared workspace scope, flags high-blast-radius tool categories, and escalates multi-turn sessions that exceed context budget thresholds.",
  riskLevel: "HIGH",
  tags: ["google", "adk", "gemini", "tool-calls", "vertex-ai", "ai", "multi-turn"],
  domains: ["tool-calls", "vertex-ai", "requests", "sessions", "provenance"],
  metadata: {
    name: "Google ADK Governance Pack",
    version: "1.0.0",
    connector: "google-adk",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "HIGH",
    riskTags: ["tool-calls", "vertex-ai", "blast-radius", "context-budget"],
    generated: false,
    category: "Framework runtime governance",
    compatibilityTargets: ["AGT_PREVIEW", "GOOGLE_ADK", "LANGCHAIN", "OPENAI_AGENTS", "CUSTOM"],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-11",
        summary: "Initial pack: non-allowlisted service block, Vertex scope warn, blast-radius warn, context budget warn, and provenance gap rules.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "google-adk.tools.block_non_allowlisted_service",
      title: "Block tool calls that target external services not declared in the workspace allowlist",
      effect: "DENY",
      domains: ["tool-calls", "requests"],
      connectors: ["google-adk"],
      actions: ["tool.http_call", "tool.api_call", "tool.external_service"],
      immutable: true,
    },
    {
      stableRuleId: "google-adk.vertex.warn_unscoped_resource_access",
      title: "Warn on Vertex AI resource access without an explicit workspace or project scope declaration",
      effect: "WARN",
      domains: ["vertex-ai", "requests"],
      connectors: ["google-adk"],
      actions: ["vertex.model_invoke", "vertex.dataset_access", "vertex.endpoint_call"],
      immutable: false,
    },
    {
      stableRuleId: "google-adk.tools.warn_high_blast_radius",
      title: "Warn when tool calls involve high-blast-radius file or compute operations",
      effect: "WARN",
      domains: ["tool-calls", "requests"],
      connectors: ["google-adk"],
      actions: ["tool.file_write", "tool.shell", "tool.code_execution", "tool.browser"],
      immutable: false,
    },
    {
      stableRuleId: "google-adk.sessions.warn_context_budget_exceeded",
      title: "Warn when a multi-turn session exceeds the declared context token budget",
      effect: "WARN",
      domains: ["sessions", "requests"],
      connectors: ["google-adk"],
      actions: ["session.turn", "session.continue", "llm_call"],
      immutable: false,
    },
    {
      stableRuleId: "google-adk.tools.warn_rate_limit_missing",
      title: "Warn when a Google ADK tool has no rate-limit budget or throttle policy",
      effect: "WARN",
      domains: ["limits", "tool-calls"],
      connectors: ["google-adk"],
      actions: ["tool.run_async", "tool.call", "tool.rate_limit_unset"],
      immutable: false,
    },
    {
      stableRuleId: "google-adk.data.warn_sensitivity_unclassified",
      title: "Warn when tool input, output, or session context lacks a data sensitivity classification",
      effect: "WARN",
      domains: ["data", "sessions", "tool-calls"],
      connectors: ["google-adk"],
      actions: ["tool.run_async", "session.turn", "data.unclassified"],
      immutable: false,
    },
    {
      stableRuleId: "google-adk.tools.require_consequence_tier_for_mutation",
      title: "Require a declared consequence tier before Google ADK tools perform mutating operations",
      effect: "DENY",
      domains: ["tool-calls", "requests"],
      connectors: ["google-adk"],
      actions: ["tool.file_write", "tool.api_call", "tool.external_service", "tool.mutation_without_tier"],
      immutable: true,
    },
    {
      stableRuleId: "google-adk.provenance.warn_gap",
      title: "Warn on tool call events where policy context could not be resolved",
      effect: "WARN",
      domains: ["provenance", "requests"],
      connectors: ["google-adk"],
      actions: ["tool.run_async", "tool.call"],
      immutable: false,
    },
  ],
};

export const STRANDS_GOVERNANCE_PACK: PolicyPack = {
  id: "strands-governance-v1",
  name: "Strands Agents Governance Pack",
  connector: "strands",
  description:
    "Governance rules for agents built with AWS Strands Agents. Blocks unapproved high-privilege AWS service calls (IAM, S3 destructive, EC2 mutations), warns on Bedrock model invocations outside the approved model list, flags tool calls without a declared consequence tier, and guards against cross-account resource access patterns.",
  riskLevel: "HIGH",
  tags: ["strands", "aws", "bedrock", "iam", "s3", "tool-calls", "ai"],
  domains: ["tool-calls", "aws", "bedrock", "iam", "provenance"],
  metadata: {
    name: "Strands Agents Governance Pack",
    version: "1.0.0",
    connector: "strands",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "HIGH",
    riskTags: ["aws", "iam", "bedrock", "cross-account"],
    generated: false,
    category: "Framework runtime governance",
    compatibilityTargets: ["AGT_PREVIEW", "AWS_BEDROCK", "LANGCHAIN", "CUSTOM"],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 2,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-11",
        summary: "Initial pack: IAM/S3/EC2 block, unapproved Bedrock model warn, missing consequence tier warn, cross-account warn, and provenance gap rules.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "strands.aws.block_high_privilege_service_calls",
      title: "Block unapproved calls to high-privilege AWS services (IAM mutations, S3 deletes, EC2 mutations)",
      effect: "DENY",
      domains: ["aws", "tool-calls"],
      connectors: ["strands"],
      actions: ["aws.iam.create_role", "aws.iam.attach_policy", "aws.s3.delete_object", "aws.ec2.terminate_instance"],
      immutable: true,
    },
    {
      stableRuleId: "strands.bedrock.warn_unapproved_model",
      title: "Warn when a Bedrock model invocation uses a model not in the workspace approved model list",
      effect: "WARN",
      domains: ["bedrock", "tool-calls"],
      connectors: ["strands"],
      actions: ["bedrock.invoke_model", "bedrock.converse", "llm_call"],
      immutable: false,
    },
    {
      stableRuleId: "strands.tools.warn_missing_consequence_tier",
      title: "Warn when a tool call does not declare a consequence tier in its invocation context",
      effect: "WARN",
      domains: ["tool-calls", "aws"],
      connectors: ["strands"],
      actions: ["tool.call", "tool.run", "tool.invoke"],
      immutable: false,
    },
    {
      stableRuleId: "strands.aws.warn_cross_account_access",
      title: "Warn when an AWS tool call targets a resource in a different account than the declared workspace account",
      effect: "WARN",
      domains: ["aws", "iam"],
      connectors: ["strands"],
      actions: ["aws.sts.assume_role", "aws.s3.cross_account_access", "aws.resource.cross_account"],
      immutable: false,
    },
    {
      stableRuleId: "strands.tools.warn_rate_limit_missing",
      title: "Warn when a Strands tool has no rate-limit budget or throttle policy",
      effect: "WARN",
      domains: ["limits", "tool-calls"],
      connectors: ["strands"],
      actions: ["tool.process", "tool.call", "tool.rate_limit_unset"],
      immutable: false,
    },
    {
      stableRuleId: "strands.data.warn_sensitivity_unclassified",
      title: "Warn when Strands tool input, output, or AWS resource context lacks a data sensitivity classification",
      effect: "WARN",
      domains: ["data", "aws", "tool-calls"],
      connectors: ["strands"],
      actions: ["tool.process", "tool.call", "data.unclassified"],
      immutable: false,
    },
    {
      stableRuleId: "strands.provenance.warn_gap",
      title: "Warn on tool call events where policy context could not be resolved",
      effect: "WARN",
      domains: ["provenance", "tool-calls"],
      connectors: ["strands"],
      actions: ["tool.process", "tool.call"],
      immutable: false,
    },
  ],
};

export const GOOGLE_ANTIGRAVITY_GOVERNANCE_PACK: PolicyPack = {
  id: "google-antigravity-governance-v1",
  name: "Google Antigravity Governance Pack",
  connector: "google-antigravity",
  description:
    "Governance rules for Python agents built with the google-antigravity SDK. Guards against tool calls to non-allowlisted external services, warns on Vertex AI resource access without declared workspace scope, flags high-blast-radius tool categories, and escalates multi-turn sessions that exceed context budget thresholds. The Antigravity CLI (agy) harness is governed separately through install-hook.",
  riskLevel: "HIGH",
  tags: ["antigravity", "google-antigravity", "tool-calls", "vertex-ai", "ai", "multi-turn"],
  domains: ["tool-calls", "vertex-ai", "requests", "sessions", "provenance"],
  metadata: {
    name: "Google Antigravity Governance Pack",
    version: "1.1.0",
    connector: "google-antigravity",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "HIGH",
    riskTags: ["tool-calls", "vertex-ai", "blast-radius", "context-budget"],
    generated: false,
    category: "Framework runtime governance",
    compatibilityTargets: ["AGT_PREVIEW", "GOOGLE_ADK", "LANGCHAIN", "OPENAI_AGENTS", "CUSTOM"],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-19",
        summary: "Initial pack (as antigravity-cli-governance-v1): non-allowlisted service block, Vertex scope warn, blast-radius warn, context budget warn, and provenance gap rules.",
      },
      {
        version: "1.1.0",
        date: "2026-07-15",
        summary: "Repointed from the retired antigravity-cli runtime adapter to the google-antigravity Python SDK connector; rule actions updated from BaseTool.run_async to ToolRunner.execute patch targets.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "google-antigravity.tools.block_non_allowlisted_service",
      title: "Block tool calls that target external services not declared in the workspace allowlist",
      effect: "DENY",
      domains: ["tool-calls", "requests"],
      connectors: ["google-antigravity"],
      actions: ["tool.http_call", "tool.api_call", "tool.external_service"],
      immutable: true,
    },
    {
      stableRuleId: "google-antigravity.vertex.warn_unscoped_resource_access",
      title: "Warn on Vertex AI resource access without an explicit workspace or project scope declaration",
      effect: "WARN",
      domains: ["vertex-ai", "requests"],
      connectors: ["google-antigravity"],
      actions: ["vertex.model_invoke", "vertex.dataset_access", "vertex.endpoint_call"],
      immutable: false,
    },
    {
      stableRuleId: "google-antigravity.tools.warn_high_blast_radius",
      title: "Warn when tool calls involve high-blast-radius file or compute operations",
      effect: "WARN",
      domains: ["tool-calls", "requests"],
      connectors: ["google-antigravity"],
      actions: ["tool.file_write", "tool.shell", "tool.code_execution", "tool.browser"],
      immutable: false,
    },
    {
      stableRuleId: "google-antigravity.sessions.warn_context_budget_exceeded",
      title: "Warn when a multi-turn session exceeds the declared context token budget",
      effect: "WARN",
      domains: ["sessions", "requests"],
      connectors: ["google-antigravity"],
      actions: ["session.turn", "session.continue", "llm_call"],
      immutable: false,
    },
    {
      stableRuleId: "google-antigravity.tools.warn_rate_limit_missing",
      title: "Warn when an Antigravity tool has no rate-limit budget or throttle policy",
      effect: "WARN",
      domains: ["limits", "tool-calls"],
      connectors: ["google-antigravity"],
      actions: ["tool.execute", "tool.call", "tool.rate_limit_unset"],
      immutable: false,
    },
    {
      stableRuleId: "google-antigravity.data.warn_sensitivity_unclassified",
      title: "Warn when tool input, output, or session context lacks a data sensitivity classification",
      effect: "WARN",
      domains: ["data", "sessions", "tool-calls"],
      connectors: ["google-antigravity"],
      actions: ["tool.execute", "session.turn", "data.unclassified"],
      immutable: false,
    },
    {
      stableRuleId: "google-antigravity.tools.require_consequence_tier_for_mutation",
      title: "Require a declared consequence tier before Antigravity tools perform mutating operations",
      effect: "DENY",
      domains: ["tool-calls", "requests"],
      connectors: ["google-antigravity"],
      actions: ["tool.file_write", "tool.api_call", "tool.external_service", "tool.mutation_without_tier"],
      immutable: true,
    },
    {
      stableRuleId: "google-antigravity.provenance.warn_gap",
      title: "Warn on tool call events where policy context could not be resolved",
      effect: "WARN",
      domains: ["provenance", "requests"],
      connectors: ["google-antigravity"],
      actions: ["tool.execute", "tool.call"],
      immutable: false,
    },
  ],
};

export const CLAUDE_AGENT_SDK_GOVERNANCE_PACK: PolicyPack = {
  id: "claude-agent-sdk-governance-v1",
  name: "Claude Agent SDK Governance Pack",
  connector: "claude-agent-sdk",
  description:
    "Governance rules for Python agents built with Anthropic's Claude Agent SDK. Controls native tool hooks, tool blast radius, permission configuration, context budgets, and provenance without conflating this framework adapter with the Claude Code harness hook.",
  riskLevel: "HIGH",
  tags: ["claude", "anthropic", "agent-sdk", "tool-calls", "permissions", "context-budget"],
  domains: ["tool-calls", "permissions", "sessions", "data", "limits", "provenance"],
  metadata: {
    name: "Claude Agent SDK Governance Pack",
    version: "1.0.0",
    connector: "claude-agent-sdk",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "HIGH",
    riskTags: ["tool-calls", "permissions", "blast-radius", "context-budget"],
    generated: false,
    category: "Framework runtime governance",
    compatibilityTargets: ["AGT_PREVIEW", "CUSTOM"],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [{ version: "1.0.0", date: "2026-07-16", summary: "Initial native-hook governance pack for the Claude Agent SDK Python adapter." }],
  },
  rules: [
    { stableRuleId: "claude-agent-sdk.tools.block_unapproved_external_service", title: "Block Claude Agent SDK tools that target services outside the workspace allowlist", effect: "DENY", domains: ["tool-calls", "permissions"], connectors: ["claude-agent-sdk"], actions: ["tool.http_call", "tool.api_call", "tool.external_service"], immutable: true },
    { stableRuleId: "claude-agent-sdk.tools.warn_high_blast_radius", title: "Warn on high-blast-radius Claude Agent SDK file, shell, browser, or MCP tool calls", effect: "WARN", domains: ["tool-calls", "permissions"], connectors: ["claude-agent-sdk"], actions: ["tool.shell", "tool.file_write", "tool.file_delete", "tool.browser", "tool.mcp"], immutable: false },
    { stableRuleId: "claude-agent-sdk.permissions.require_consequence_tier_for_mutation", title: "Require a declared consequence tier before Claude Agent SDK tools mutate systems", effect: "DENY", domains: ["permissions", "tool-calls"], connectors: ["claude-agent-sdk"], actions: ["tool.write", "tool.update", "tool.delete", "tool.mutation_without_tier"], immutable: true },
    { stableRuleId: "claude-agent-sdk.sessions.warn_context_budget_exceeded", title: "Warn when a Claude Agent SDK session exceeds its declared context budget", effect: "WARN", domains: ["sessions", "limits"], connectors: ["claude-agent-sdk"], actions: ["session.turn", "session.continue", "llm_call"], immutable: false },
    { stableRuleId: "claude-agent-sdk.tools.warn_rate_limit_missing", title: "Warn when a Claude Agent SDK tool has no rate-limit budget or throttle policy", effect: "WARN", domains: ["limits", "tool-calls"], connectors: ["claude-agent-sdk"], actions: ["tool.call", "tool.invoke", "tool.rate_limit_unset"], immutable: false },
    { stableRuleId: "claude-agent-sdk.data.warn_sensitivity_unclassified", title: "Warn when Claude Agent SDK tool input or output lacks a data sensitivity classification", effect: "WARN", domains: ["data", "tool-calls"], connectors: ["claude-agent-sdk"], actions: ["tool.call", "tool.output", "data.unclassified"], immutable: false },
    { stableRuleId: "claude-agent-sdk.provenance.warn_gap", title: "Warn on Claude Agent SDK tool events whose policy context cannot be resolved", effect: "WARN", domains: ["provenance", "tool-calls"], connectors: ["claude-agent-sdk"], actions: ["tool.call", "tool.invoke", "session.turn"], immutable: false },
  ],
};
