import type { PolicyPack } from "../types";

// Gateway packs govern proxy-layer LLM telemetry where Spctre may see cost,
// token, tool declaration, routing, and provenance signals without direct
// framework instrumentation.
export const GATEWAY_PORTKEY_PACK: PolicyPack = {
  id: "gateway-portkey-v1",
  name: "Portkey Gateway Governance Pack",
  connector: "gateway-portkey",
  description:
    "Governance rules for agents routing LLM calls through Portkey. Enforces spend limits, flags high-token requests, escalates high-blast-radius tool declarations, and surfaces provenance gaps when policy context cannot be resolved at event time.",
  riskLevel: "MEDIUM",
  tags: ["llm", "gateway", "observability", "ai", "portkey", "cost", "tokens"],
  domains: ["requests", "tool-calls", "routing", "cost", "tokens"],
  metadata: {
    name: "Portkey Gateway Governance Pack",
    version: "1.0.0",
    connector: "gateway-portkey",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "MEDIUM",
    riskTags: ["llm", "gateway", "cost", "tokens"],
    generated: false,
    category: "LLM gateway governance",
    compatibilityTargets: [
      "AGT_PREVIEW",
      "CREWAI",
      "LANGCHAIN",
      "OPENAI_AGENTS",
      "AUTOGEN",
      "CUSTOM",
    ],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-11",
        summary:
          "Initial pack: spend cap, token budget, tool blast-radius, provenance gap, and virtual-key audit rules.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "gateway-portkey.cost.block_high_spend",
      title: "Block requests exceeding per-call spend cap",
      effect: "DENY",
      domains: ["cost", "requests"],
      connectors: ["gateway-portkey"],
      actions: ["llm_call", "chat.completions", "completions"],
      immutable: true,
    },
    {
      stableRuleId: "gateway-portkey.tokens.warn_high_usage",
      title: "Warn when total token count exceeds session budget",
      effect: "WARN",
      domains: ["tokens", "requests"],
      connectors: ["gateway-portkey"],
      actions: ["llm_call", "chat.completions", "completions"],
      immutable: false,
    },
    {
      stableRuleId: "gateway-portkey.tools.warn_high_blast_radius",
      title: "Warn when tool declarations include high-blast-radius system tools",
      effect: "WARN",
      domains: ["tool-calls", "requests"],
      connectors: ["gateway-portkey"],
      actions: ["tool.bash", "tool.shell", "tool.computer", "tool.file_write", "tool.execute"],
      immutable: true,
    },
    {
      stableRuleId: "gateway-portkey.provenance.warn_gap",
      title: "Warn on gateway events where policy context could not be resolved",
      effect: "WARN",
      domains: ["requests", "routing"],
      connectors: ["gateway-portkey"],
      actions: ["llm_call", "chat.completions"],
      immutable: false,
    },
    {
      stableRuleId: "gateway-portkey.routing.warn_unverified_key",
      title: "Warn when request routes through an unrecognized virtual key",
      effect: "WARN",
      domains: ["routing", "requests"],
      connectors: ["gateway-portkey"],
      actions: ["routing.virtual_key", "routing.fallback"],
      immutable: false,
    },
  ],
};

export const GATEWAY_HELICONE_PACK: PolicyPack = {
  id: "gateway-helicone-v1",
  name: "Helicone Gateway Governance Pack",
  connector: "gateway-helicone",
  description:
    "Governance rules for agents routing LLM calls through Helicone. Controls per-call cost, token volume, high-blast-radius tool scope, long-running session risk, and provenance gaps — surfaced in the Evidence ledger alongside runtime decision records.",
  riskLevel: "MEDIUM",
  tags: ["llm", "gateway", "observability", "ai", "helicone", "cost", "sessions"],
  domains: ["requests", "tool-calls", "prompts", "cost", "tokens"],
  metadata: {
    name: "Helicone Gateway Governance Pack",
    version: "1.0.0",
    connector: "gateway-helicone",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "MEDIUM",
    riskTags: ["llm", "gateway", "cost", "sessions"],
    generated: false,
    category: "LLM gateway governance",
    compatibilityTargets: [
      "AGT_PREVIEW",
      "CREWAI",
      "LANGCHAIN",
      "OPENAI_AGENTS",
      "AUTOGEN",
      "CUSTOM",
    ],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-11",
        summary:
          "Initial pack: spend cap, token budget, tool blast-radius, long-running session escalation, and provenance gap rules.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "gateway-helicone.cost.block_high_spend",
      title: "Block requests exceeding per-call spend cap",
      effect: "DENY",
      domains: ["cost", "requests"],
      connectors: ["gateway-helicone"],
      actions: ["llm_call", "chat.completions", "completions"],
      immutable: true,
    },
    {
      stableRuleId: "gateway-helicone.tokens.warn_high_usage",
      title: "Warn when total token count exceeds session budget",
      effect: "WARN",
      domains: ["tokens", "requests"],
      connectors: ["gateway-helicone"],
      actions: ["llm_call", "chat.completions", "completions"],
      immutable: false,
    },
    {
      stableRuleId: "gateway-helicone.tools.warn_high_blast_radius",
      title: "Warn when tool declarations include high-blast-radius system tools",
      effect: "WARN",
      domains: ["tool-calls", "requests"],
      connectors: ["gateway-helicone"],
      actions: ["tool.bash", "tool.shell", "tool.computer", "tool.file_write", "tool.execute"],
      immutable: true,
    },
    {
      stableRuleId: "gateway-helicone.session.warn_long_running",
      title: "Warn on session IDs that have accumulated an unusually high call count",
      effect: "WARN",
      domains: ["prompts", "requests"],
      connectors: ["gateway-helicone"],
      actions: ["session.call", "llm_call"],
      immutable: false,
    },
    {
      stableRuleId: "gateway-helicone.provenance.warn_gap",
      title: "Warn on gateway events where policy context could not be resolved",
      effect: "WARN",
      domains: ["requests", "prompts"],
      connectors: ["gateway-helicone"],
      actions: ["llm_call", "chat.completions"],
      immutable: false,
    },
  ],
};

export const GATEWAY_LITELLM_PACK: PolicyPack = {
  id: "gateway-litellm-v1",
  name: "LiteLLM Gateway Governance Pack",
  connector: "gateway-litellm",
  description:
    "Governance rules for agents routing LLM calls through LiteLLM. Enforces per-call spend limits, token budgets, high-blast-radius tool escalation, fallback model routing warnings, and provenance gap surfacing — enabling compliance coverage for proxy-layer agent deployments without code changes.",
  riskLevel: "MEDIUM",
  tags: ["llm", "gateway", "observability", "ai", "litellm", "spend", "routing"],
  domains: ["requests", "tool-calls", "routing", "spend", "tokens"],
  metadata: {
    name: "LiteLLM Gateway Governance Pack",
    version: "1.0.0",
    connector: "gateway-litellm",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "MEDIUM",
    riskTags: ["llm", "gateway", "spend", "routing"],
    generated: false,
    category: "LLM gateway governance",
    compatibilityTargets: [
      "AGT_PREVIEW",
      "CREWAI",
      "LANGCHAIN",
      "OPENAI_AGENTS",
      "AUTOGEN",
      "CUSTOM",
    ],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-11",
        summary:
          "Initial pack: spend cap, token budget, tool blast-radius, fallback model routing, and provenance gap rules.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "gateway-litellm.spend.block_high_spend",
      title: "Block requests exceeding per-call spend cap",
      effect: "DENY",
      domains: ["spend", "requests"],
      connectors: ["gateway-litellm"],
      actions: ["llm_call", "chat.completions", "completions"],
      immutable: true,
    },
    {
      stableRuleId: "gateway-litellm.tokens.warn_high_usage",
      title: "Warn when total token count exceeds session budget",
      effect: "WARN",
      domains: ["tokens", "requests"],
      connectors: ["gateway-litellm"],
      actions: ["llm_call", "chat.completions", "completions"],
      immutable: false,
    },
    {
      stableRuleId: "gateway-litellm.tools.warn_high_blast_radius",
      title: "Warn when tool declarations include high-blast-radius system tools",
      effect: "WARN",
      domains: ["tool-calls", "requests"],
      connectors: ["gateway-litellm"],
      actions: ["tool.bash", "tool.shell", "tool.computer", "tool.file_write", "tool.execute"],
      immutable: true,
    },
    {
      stableRuleId: "gateway-litellm.routing.warn_fallback_model",
      title: "Warn when LiteLLM routes a request to a fallback or non-primary model",
      effect: "WARN",
      domains: ["routing", "requests"],
      connectors: ["gateway-litellm"],
      actions: ["routing.fallback", "routing.model_switch", "llm_call"],
      immutable: false,
    },
    {
      stableRuleId: "gateway-litellm.provenance.warn_gap",
      title: "Warn on gateway events where policy context could not be resolved",
      effect: "WARN",
      domains: ["requests", "routing"],
      connectors: ["gateway-litellm"],
      actions: ["llm_call", "chat.completions"],
      immutable: false,
    },
  ],
};

export const GATEWAY_NOTION_PACK: PolicyPack = {
  id: "gateway-notion-v1",
  name: "Notion Webhook Gateway Governance Pack",
  connector: "gateway-notion",
  description:
    "Governance rules for Notion Worker webhook payloads received via the /api/gateway/ingest/notion receiver. Controls cost, token volume, high-blast-radius tool scope, and surfaces provenance gaps — consistent with the Portkey, Helicone, and LiteLLM gateway packs but scoped to the Notion webhook ingest surface specifically.",
  riskLevel: "MEDIUM",
  tags: ["notion", "gateway", "webhook", "workers", "observability", "cost", "tokens"],
  domains: ["requests", "tool-calls", "routing", "cost", "tokens"],
  metadata: {
    name: "Notion Webhook Gateway Governance Pack",
    version: "1.0.0",
    connector: "gateway-notion",
    author: "spctre",
    owner: "spctre-pack-security",
    riskLevel: "MEDIUM",
    riskTags: ["notion", "gateway", "webhook", "cost", "tokens"],
    generated: false,
    category: "LLM gateway governance",
    compatibilityTargets: [
      "AGT_PREVIEW",
      "CREWAI",
      "LANGCHAIN",
      "OPENAI_AGENTS",
      "AUTOGEN",
      "CUSTOM",
    ],
    reviewRoles: ["SECURITY", "COMPLIANCE"],
    minimumApprovals: 1,
    changelog: [
      {
        version: "1.0.0",
        date: "2026-05-18",
        summary:
          "Initial pack: spend cap, token budget, tool blast-radius, and provenance gap rules for the Notion webhook receiver surface.",
      },
    ],
  },
  rules: [
    {
      stableRuleId: "gateway-notion.cost.block_high_spend",
      title: "Block Notion Worker webhook events exceeding per-call spend cap",
      effect: "DENY",
      domains: ["cost", "requests"],
      connectors: ["gateway-notion"],
      actions: ["llm_call", "worker.execute", "agent.action"],
      immutable: true,
    },
    {
      stableRuleId: "gateway-notion.tokens.warn_high_usage",
      title: "Warn when total token count in a Notion Worker event exceeds session budget",
      effect: "WARN",
      domains: ["tokens", "requests"],
      connectors: ["gateway-notion"],
      actions: ["llm_call", "worker.execute"],
      immutable: false,
    },
    {
      stableRuleId: "gateway-notion.tools.warn_high_blast_radius",
      title: "Warn when Notion Worker tool declarations include high-blast-radius system tools",
      effect: "WARN",
      domains: ["tool-calls", "requests"],
      connectors: ["gateway-notion"],
      actions: ["tool.bash", "tool.shell", "tool.computer", "tool.file_write", "tool.execute"],
      immutable: true,
    },
    {
      stableRuleId: "gateway-notion.provenance.warn_gap",
      title: "Warn on Notion webhook events where policy context could not be resolved",
      effect: "WARN",
      domains: ["requests", "routing"],
      connectors: ["gateway-notion"],
      actions: ["worker.execute", "agent.action"],
      immutable: false,
    },
  ],
};
